// Code generated by MockGen. DO NOT EDIT.
// Source: identity.go
//
// Generated by this command:
//
//	mockgen -source=identity.go -destination=mock_document_store_test.go -package=sync
//

// Package sync is a generated GoMock package.
package sync

import (
	context "context"
	reflect "reflect"

	memory "github.com/ZanzyTHEbar/dragonscale/pkg/memory"
	gomock "go.uber.org/mock/gomock"
)

// MockDocumentStore is a mock of DocumentStore interface.
type MockDocumentStore struct {
	ctrl     *gomock.Controller
	recorder *MockDocumentStoreMockRecorder
	isgomock struct{}
}

// MockDocumentStoreMockRecorder is the mock recorder for MockDocumentStore.
type MockDocumentStoreMockRecorder struct {
	mock *MockDocumentStore
}

// NewMockDocumentStore creates a new mock instance.
func NewMockDocumentStore(ctrl *gomock.Controller) *MockDocumentStore {
	mock := &MockDocumentStore{ctrl: ctrl}
	mock.recorder = &MockDocumentStoreMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockDocumentStore) EXPECT() *MockDocumentStoreMockRecorder {
	return m.recorder
}

// GetKV mocks base method.
func (m *MockDocumentStore) GetKV(ctx context.Context, agentID, key string) (string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetKV", ctx, agentID, key)
	ret0, _ := ret[0].(string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetKV indicates an expected call of GetKV.
func (mr *MockDocumentStoreMockRecorder) GetKV(ctx, agentID, key any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetKV", reflect.TypeOf((*MockDocumentStore)(nil).GetKV), ctx, agentID, key)
}

// ListDocumentsByCategory mocks base method.
func (m *MockDocumentStore) ListDocumentsByCategory(ctx context.Context, agentID, category string) ([]*memory.AgentDocument, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListDocumentsByCategory", ctx, agentID, category)
	ret0, _ := ret[0].([]*memory.AgentDocument)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListDocumentsByCategory indicates an expected call of ListDocumentsByCategory.
func (mr *MockDocumentStoreMockRecorder) ListDocumentsByCategory(ctx, agentID, category any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListDocumentsByCategory", reflect.TypeOf((*MockDocumentStore)(nil).ListDocumentsByCategory), ctx, agentID, category)
}

// UpsertDocument mocks base method.
func (m *MockDocumentStore) UpsertDocument(ctx context.Context, doc *memory.AgentDocument) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpsertDocument", ctx, doc)
	ret0, _ := ret[0].(error)
	return ret0
}

// UpsertDocument indicates an expected call of UpsertDocument.
func (mr *MockDocumentStoreMockRecorder) UpsertDocument(ctx, doc any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpsertDocument", reflect.TypeOf((*MockDocumentStore)(nil).UpsertDocument), ctx, doc)
}

// UpsertKV mocks base method.
func (m *MockDocumentStore) UpsertKV(ctx context.Context, agentID, key, value string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpsertKV", ctx, agentID, key, value)
	ret0, _ := ret[0].(error)
	return ret0
}

// UpsertKV indicates an expected call of UpsertKV.
func (mr *MockDocumentStoreMockRecorder) UpsertKV(ctx, agentID, key, value any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpsertKV", reflect.TypeOf((*MockDocumentStore)(nil).UpsertKV), ctx, agentID, key, value)
}
