// Code generated by MockGen. DO NOT EDIT.
// Source: model.go
//
// Generated by this command:
//
//	mockgen -source=model.go -destination=mock_language_model_test.go -package=fantasy
//

// Package fantasy is a generated GoMock package.
package fantasy

import (
	context "context"
	reflect "reflect"

	gomock "go.uber.org/mock/gomock"
)

// MockLanguageModel is a mock of LanguageModel interface.
type MockLanguageModel struct {
	ctrl     *gomock.Controller
	recorder *MockLanguageModelMockRecorder
	isgomock struct{}
}

// MockLanguageModelMockRecorder is the mock recorder for MockLanguageModel.
type MockLanguageModelMockRecorder struct {
	mock *MockLanguageModel
}

// NewMockLanguageModel creates a new mock instance.
func NewMockLanguageModel(ctrl *gomock.Controller) *MockLanguageModel {
	mock := &MockLanguageModel{ctrl: ctrl}
	mock.recorder = &MockLanguageModelMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockLanguageModel) EXPECT() *MockLanguageModelMockRecorder {
	return m.recorder
}

// Generate mocks base method.
func (m *MockLanguageModel) Generate(arg0 context.Context, arg1 Call) (*Response, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Generate", arg0, arg1)
	ret0, _ := ret[0].(*Response)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Generate indicates an expected call of Generate.
func (mr *MockLanguageModelMockRecorder) Generate(arg0, arg1 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Generate", reflect.TypeOf((*MockLanguageModel)(nil).Generate), arg0, arg1)
}

// GenerateObject mocks base method.
func (m *MockLanguageModel) GenerateObject(arg0 context.Context, arg1 ObjectCall) (*ObjectResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GenerateObject", arg0, arg1)
	ret0, _ := ret[0].(*ObjectResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GenerateObject indicates an expected call of GenerateObject.
func (mr *MockLanguageModelMockRecorder) GenerateObject(arg0, arg1 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GenerateObject", reflect.TypeOf((*MockLanguageModel)(nil).GenerateObject), arg0, arg1)
}

// Model mocks base method.
func (m *MockLanguageModel) Model() string {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Model")
	ret0, _ := ret[0].(string)
	return ret0
}

// Model indicates an expected call of Model.
func (mr *MockLanguageModelMockRecorder) Model() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Model", reflect.TypeOf((*MockLanguageModel)(nil).Model))
}

// Provider mocks base method.
func (m *MockLanguageModel) Provider() string {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Provider")
	ret0, _ := ret[0].(string)
	return ret0
}

// Provider indicates an expected call of Provider.
func (mr *MockLanguageModelMockRecorder) Provider() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Provider", reflect.TypeOf((*MockLanguageModel)(nil).Provider))
}

// Stream mocks base method.
func (m *MockLanguageModel) Stream(arg0 context.Context, arg1 Call) (StreamResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Stream", arg0, arg1)
	ret0, _ := ret[0].(StreamResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Stream indicates an expected call of Stream.
func (mr *MockLanguageModelMockRecorder) Stream(arg0, arg1 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Stream", reflect.TypeOf((*MockLanguageModel)(nil).Stream), arg0, arg1)
}

// StreamObject mocks base method.
func (m *MockLanguageModel) StreamObject(arg0 context.Context, arg1 ObjectCall) (ObjectStreamResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "StreamObject", arg0, arg1)
	ret0, _ := ret[0].(ObjectStreamResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// StreamObject indicates an expected call of StreamObject.
func (mr *MockLanguageModelMockRecorder) StreamObject(arg0, arg1 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "StreamObject", reflect.TypeOf((*MockLanguageModel)(nil).StreamObject), arg0, arg1)
}
