// Code generated by MockGen. DO NOT EDIT.
// Source: tool_runtime.go
//
// Generated by this command:
//
//	mockgen -source=tool_runtime.go -destination=mock_tool_runtime_test.go -package=fantasy
//

// Package fantasy is a generated GoMock package.
package fantasy

import (
	context "context"
	reflect "reflect"

	gomock "go.uber.org/mock/gomock"
)

// MockToolRuntime is a mock of ToolRuntime interface.
type MockToolRuntime struct {
	ctrl     *gomock.Controller
	recorder *MockToolRuntimeMockRecorder
	isgomock struct{}
}

// MockToolRuntimeMockRecorder is the mock recorder for MockToolRuntime.
type MockToolRuntimeMockRecorder struct {
	mock *MockToolRuntime
}

// NewMockToolRuntime creates a new mock instance.
func NewMockToolRuntime(ctrl *gomock.Controller) *MockToolRuntime {
	mock := &MockToolRuntime{ctrl: ctrl}
	mock.recorder = &MockToolRuntimeMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockToolRuntime) EXPECT() *MockToolRuntimeMockRecorder {
	return m.recorder
}

// Execute mocks base method.
func (m *MockToolRuntime) Execute(ctx context.Context, tools []AgentTool, execProviderTools []ExecutableProviderTool, toolCalls []ToolCallContent, toolResultCallback func(ToolResultContent) error) ([]ToolResultContent, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Execute", ctx, tools, execProviderTools, toolCalls, toolResultCallback)
	ret0, _ := ret[0].([]ToolResultContent)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Execute indicates an expected call of Execute.
func (mr *MockToolRuntimeMockRecorder) Execute(ctx, tools, execProviderTools, toolCalls, toolResultCallback any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Execute", reflect.TypeOf((*MockToolRuntime)(nil).Execute), ctx, tools, execProviderTools, toolCalls, toolResultCallback)
}
