package ids

import (
	"encoding/hex"
	"errors"
	"strings"
)

// ToBytes converts a canonical UUID string (8-4-4-4-12) into its 16-byte form.
func ToBytes(u string) ([16]byte, error) {
	var out [16]byte
	// Strip hyphens
	s := strings.ReplaceAll(u, "-", "")
	if len(s) != 32 {
		return out, errors.New("invalid uuid length")
	}
	b, err := hex.DecodeString(s)
	if err != nil {
		return out, err
	}
	copy(out[:], b)
	return out, nil
}

// MustToBytes converts string to bytes and panics on error. Safe for ids generated by New().
func MustToBytes(u string) []byte {
	b, err := ToBytes(u)
	if err != nil {
		panic(err)
	}
	return b[:]
}

// FromBytes converts 16 raw bytes into UUID type.
func FromBytes(b []byte) UUID {
	var out UUID
	copy(out[:], b)
	return out
}

// FromString is an alias for MustParse. Panics on invalid input.
func FromString(s string) UUID {
	return MustParse(s)
}
