// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: agent_threads.sql

package sqlc

import (
	"context"
	"encoding/json"

	"github.com/sipeed/picoclaw/pkg/ids"
)

const AddAgentThreadMessage = `-- name: AddAgentThreadMessage :one
INSERT INTO agent_thread_messages (id, thread_id, role, content, metadata_json)
VALUES (?, ?, ?, ?, ?)
RETURNING id, thread_id, role, content, metadata_json, created_at, updated_at
`

type AddAgentThreadMessageParams struct {
	ID           ids.UUID        `db:"id" json:"id"`
	ThreadID     ids.UUID        `db:"thread_id" json:"thread_id"`
	Role         string          `db:"role" json:"role"`
	Content      string          `db:"content" json:"content"`
	MetadataJson json.RawMessage `db:"metadata_json" json:"metadata_json"`
}

// AddAgentThreadMessage
//
//	INSERT INTO agent_thread_messages (id, thread_id, role, content, metadata_json)
//	VALUES (?, ?, ?, ?, ?)
//	RETURNING id, thread_id, role, content, metadata_json, created_at, updated_at
func (q *Queries) AddAgentThreadMessage(ctx context.Context, arg AddAgentThreadMessageParams) (AgentThreadMessage, error) {
	row := q.db.QueryRowContext(ctx, AddAgentThreadMessage,
		arg.ID,
		arg.ThreadID,
		arg.Role,
		arg.Content,
		arg.MetadataJson,
	)
	var i AgentThreadMessage
	err := row.Scan(
		&i.ID,
		&i.ThreadID,
		&i.Role,
		&i.Content,
		&i.MetadataJson,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const CreateAgentThread = `-- name: CreateAgentThread :one
INSERT INTO agent_threads (id, conversation_id, title, metadata_json)
VALUES (?, ?, ?, ?)
RETURNING id, conversation_id, title, metadata_json, created_at, updated_at
`

type CreateAgentThreadParams struct {
	ID             ids.UUID        `db:"id" json:"id"`
	ConversationID ids.UUID        `db:"conversation_id" json:"conversation_id"`
	Title          *string         `db:"title" json:"title"`
	MetadataJson   json.RawMessage `db:"metadata_json" json:"metadata_json"`
}

// CreateAgentThread
//
//	INSERT INTO agent_threads (id, conversation_id, title, metadata_json)
//	VALUES (?, ?, ?, ?)
//	RETURNING id, conversation_id, title, metadata_json, created_at, updated_at
func (q *Queries) CreateAgentThread(ctx context.Context, arg CreateAgentThreadParams) (AgentThread, error) {
	row := q.db.QueryRowContext(ctx, CreateAgentThread,
		arg.ID,
		arg.ConversationID,
		arg.Title,
		arg.MetadataJson,
	)
	var i AgentThread
	err := row.Scan(
		&i.ID,
		&i.ConversationID,
		&i.Title,
		&i.MetadataJson,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const ListAgentThreadMessagesByThreadID = `-- name: ListAgentThreadMessagesByThreadID :many
SELECT id, thread_id, role, content, metadata_json, created_at, updated_at FROM agent_thread_messages
WHERE thread_id = ?
ORDER BY created_at ASC
`

type ListAgentThreadMessagesByThreadIDParams struct {
	ThreadID ids.UUID `db:"thread_id" json:"thread_id"`
}

// ListAgentThreadMessagesByThreadID
//
//	SELECT id, thread_id, role, content, metadata_json, created_at, updated_at FROM agent_thread_messages
//	WHERE thread_id = ?
//	ORDER BY created_at ASC
func (q *Queries) ListAgentThreadMessagesByThreadID(ctx context.Context, arg ListAgentThreadMessagesByThreadIDParams) ([]AgentThreadMessage, error) {
	rows, err := q.db.QueryContext(ctx, ListAgentThreadMessagesByThreadID, arg.ThreadID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []AgentThreadMessage{}
	for rows.Next() {
		var i AgentThreadMessage
		if err := rows.Scan(
			&i.ID,
			&i.ThreadID,
			&i.Role,
			&i.Content,
			&i.MetadataJson,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const ListAgentThreadMessagesByThreadIDDescLimit = `-- name: ListAgentThreadMessagesByThreadIDDescLimit :many
SELECT id, thread_id, role, content, metadata_json, created_at, updated_at FROM agent_thread_messages
WHERE thread_id = ?
ORDER BY created_at DESC
LIMIT ?
`

type ListAgentThreadMessagesByThreadIDDescLimitParams struct {
	ThreadID ids.UUID `db:"thread_id" json:"thread_id"`
	Limit    int64    `db:"limit" json:"limit"`
}

// ListAgentThreadMessagesByThreadIDDescLimit
//
//	SELECT id, thread_id, role, content, metadata_json, created_at, updated_at FROM agent_thread_messages
//	WHERE thread_id = ?
//	ORDER BY created_at DESC
//	LIMIT ?
func (q *Queries) ListAgentThreadMessagesByThreadIDDescLimit(ctx context.Context, arg ListAgentThreadMessagesByThreadIDDescLimitParams) ([]AgentThreadMessage, error) {
	rows, err := q.db.QueryContext(ctx, ListAgentThreadMessagesByThreadIDDescLimit, arg.ThreadID, arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []AgentThreadMessage{}
	for rows.Next() {
		var i AgentThreadMessage
		if err := rows.Scan(
			&i.ID,
			&i.ThreadID,
			&i.Role,
			&i.Content,
			&i.MetadataJson,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const ListAgentThreadsByConversationID = `-- name: ListAgentThreadsByConversationID :many
SELECT id, conversation_id, title, metadata_json, created_at, updated_at FROM agent_threads
WHERE conversation_id = ?
ORDER BY created_at DESC
LIMIT ?2
`

type ListAgentThreadsByConversationIDParams struct {
	ConversationID ids.UUID `db:"conversation_id" json:"conversation_id"`
	Lim            int64    `db:"lim" json:"lim"`
}

// ListAgentThreadsByConversationID
//
//	SELECT id, conversation_id, title, metadata_json, created_at, updated_at FROM agent_threads
//	WHERE conversation_id = ?
//	ORDER BY created_at DESC
//	LIMIT ?2
func (q *Queries) ListAgentThreadsByConversationID(ctx context.Context, arg ListAgentThreadsByConversationIDParams) ([]AgentThread, error) {
	rows, err := q.db.QueryContext(ctx, ListAgentThreadsByConversationID, arg.ConversationID, arg.Lim)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []AgentThread{}
	for rows.Next() {
		var i AgentThread
		if err := rows.Scan(
			&i.ID,
			&i.ConversationID,
			&i.Title,
			&i.MetadataJson,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
