// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: agent_message_revisions.sql

package sqlc

import (
	"context"
	"encoding/json"

	"github.com/ZanzyTHEbar/dragonscale/pkg/ids"
)

const AddAgentMessageRevision = `-- name: AddAgentMessageRevision :one
INSERT INTO agent_message_revisions (
        id,
        message_id,
        editor,
        old_content,
        new_content,
        metadata_json
    )
VALUES (?, ?, ?, ?, ?, ?)
RETURNING id, message_id, editor, old_content, new_content, metadata_json, created_at, updated_at
`

type AddAgentMessageRevisionParams struct {
	ID           ids.UUID        `db:"id" json:"id"`
	MessageID    ids.UUID        `db:"message_id" json:"message_id"`
	Editor       string          `db:"editor" json:"editor"`
	OldContent   string          `db:"old_content" json:"old_content"`
	NewContent   string          `db:"new_content" json:"new_content"`
	MetadataJson json.RawMessage `db:"metadata_json" json:"metadata_json"`
}

// AddAgentMessageRevision
//
//	INSERT INTO agent_message_revisions (
//	        id,
//	        message_id,
//	        editor,
//	        old_content,
//	        new_content,
//	        metadata_json
//	    )
//	VALUES (?, ?, ?, ?, ?, ?)
//	RETURNING id, message_id, editor, old_content, new_content, metadata_json, created_at, updated_at
func (q *Queries) AddAgentMessageRevision(ctx context.Context, arg AddAgentMessageRevisionParams) (AgentMessageRevision, error) {
	row := q.db.QueryRowContext(ctx, AddAgentMessageRevision,
		arg.ID,
		arg.MessageID,
		arg.Editor,
		arg.OldContent,
		arg.NewContent,
		arg.MetadataJson,
	)
	var i AgentMessageRevision
	err := row.Scan(
		&i.ID,
		&i.MessageID,
		&i.Editor,
		&i.OldContent,
		&i.NewContent,
		&i.MetadataJson,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const ListAgentMessageRevisionsByMessageID = `-- name: ListAgentMessageRevisionsByMessageID :many
SELECT id, message_id, editor, old_content, new_content, metadata_json, created_at, updated_at
FROM agent_message_revisions
WHERE message_id = ?
ORDER BY created_at DESC
LIMIT ?2
`

type ListAgentMessageRevisionsByMessageIDParams struct {
	MessageID ids.UUID `db:"message_id" json:"message_id"`
	Lim       int64    `db:"lim" json:"lim"`
}

// ListAgentMessageRevisionsByMessageID
//
//	SELECT id, message_id, editor, old_content, new_content, metadata_json, created_at, updated_at
//	FROM agent_message_revisions
//	WHERE message_id = ?
//	ORDER BY created_at DESC
//	LIMIT ?2
func (q *Queries) ListAgentMessageRevisionsByMessageID(ctx context.Context, arg ListAgentMessageRevisionsByMessageIDParams) ([]AgentMessageRevision, error) {
	rows, err := q.db.QueryContext(ctx, ListAgentMessageRevisionsByMessageID, arg.MessageID, arg.Lim)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []AgentMessageRevision{}
	for rows.Next() {
		var i AgentMessageRevision
		if err := rows.Scan(
			&i.ID,
			&i.MessageID,
			&i.Editor,
			&i.OldContent,
			&i.NewContent,
			&i.MetadataJson,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
