// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: agent_conversations.sql

package sqlc

import (
	"context"

	"github.com/ZanzyTHEbar/dragonscale/pkg/ids"
)

const CreateAgentConversation = `-- name: CreateAgentConversation :one
INSERT INTO agent_conversations (id, title)
VALUES (?, ?)
RETURNING id, title, created_at, updated_at
`

type CreateAgentConversationParams struct {
	ID    ids.UUID `db:"id" json:"id"`
	Title *string  `db:"title" json:"title"`
}

// CreateAgentConversation
//
//	INSERT INTO agent_conversations (id, title)
//	VALUES (?, ?)
//	RETURNING id, title, created_at, updated_at
func (q *Queries) CreateAgentConversation(ctx context.Context, arg CreateAgentConversationParams) (AgentConversation, error) {
	row := q.db.QueryRowContext(ctx, CreateAgentConversation, arg.ID, arg.Title)
	var i AgentConversation
	err := row.Scan(
		&i.ID,
		&i.Title,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const GetAgentConversation = `-- name: GetAgentConversation :one
SELECT id, title, created_at, updated_at
FROM agent_conversations
WHERE id = ?
LIMIT 1
`

type GetAgentConversationParams struct {
	ID ids.UUID `db:"id" json:"id"`
}

// GetAgentConversation
//
//	SELECT id, title, created_at, updated_at
//	FROM agent_conversations
//	WHERE id = ?
//	LIMIT 1
func (q *Queries) GetAgentConversation(ctx context.Context, arg GetAgentConversationParams) (AgentConversation, error) {
	row := q.db.QueryRowContext(ctx, GetAgentConversation, arg.ID)
	var i AgentConversation
	err := row.Scan(
		&i.ID,
		&i.Title,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const GetLatestAgentConversationByTitle = `-- name: GetLatestAgentConversationByTitle :one
SELECT id, title, created_at, updated_at
FROM agent_conversations
WHERE title = ?
ORDER BY created_at DESC
LIMIT 1
`

type GetLatestAgentConversationByTitleParams struct {
	Title *string `db:"title" json:"title"`
}

// GetLatestAgentConversationByTitle
//
//	SELECT id, title, created_at, updated_at
//	FROM agent_conversations
//	WHERE title = ?
//	ORDER BY created_at DESC
//	LIMIT 1
func (q *Queries) GetLatestAgentConversationByTitle(ctx context.Context, arg GetLatestAgentConversationByTitleParams) (AgentConversation, error) {
	row := q.db.QueryRowContext(ctx, GetLatestAgentConversationByTitle, arg.Title)
	var i AgentConversation
	err := row.Scan(
		&i.ID,
		&i.Title,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const ListAgentConversations = `-- name: ListAgentConversations :many
SELECT id, title, created_at, updated_at
FROM agent_conversations
ORDER BY created_at DESC
LIMIT ?
`

type ListAgentConversationsParams struct {
	Limit int64 `db:"limit" json:"limit"`
}

// ListAgentConversations
//
//	SELECT id, title, created_at, updated_at
//	FROM agent_conversations
//	ORDER BY created_at DESC
//	LIMIT ?
func (q *Queries) ListAgentConversations(ctx context.Context, arg ListAgentConversationsParams) ([]AgentConversation, error) {
	rows, err := q.db.QueryContext(ctx, ListAgentConversations, arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []AgentConversation{}
	for rows.Next() {
		var i AgentConversation
		if err := rows.Scan(
			&i.ID,
			&i.Title,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const UpdateAgentConversationTitle = `-- name: UpdateAgentConversationTitle :one
UPDATE agent_conversations
SET title = ?,
    updated_at = (strftime('%Y-%m-%dT%H:%M:%fZ', 'now'))
WHERE id = ?
RETURNING id, title, created_at, updated_at
`

type UpdateAgentConversationTitleParams struct {
	Title *string  `db:"title" json:"title"`
	ID    ids.UUID `db:"id" json:"id"`
}

// UpdateAgentConversationTitle
//
//	UPDATE agent_conversations
//	SET title = ?,
//	    updated_at = (strftime('%Y-%m-%dT%H:%M:%fZ', 'now'))
//	WHERE id = ?
//	RETURNING id, title, created_at, updated_at
func (q *Queries) UpdateAgentConversationTitle(ctx context.Context, arg UpdateAgentConversationTitleParams) (AgentConversation, error) {
	row := q.db.QueryRowContext(ctx, UpdateAgentConversationTitle, arg.Title, arg.ID)
	var i AgentConversation
	err := row.Scan(
		&i.ID,
		&i.Title,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
