// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: agent_conversation_forks.sql

package sqlc

import (
	"context"
	"encoding/json"

	"github.com/sipeed/picoclaw/pkg/ids"
)

const CreateAgentConversationFork = `-- name: CreateAgentConversationFork :one
INSERT INTO agent_conversation_forks (
    id, parent_conversation_id, child_conversation_id, checkpoint_id, metadata_json
)
VALUES (?, ?, ?, ?, ?)
RETURNING id, parent_conversation_id, child_conversation_id, checkpoint_id, metadata_json, created_at, updated_at
`

type CreateAgentConversationForkParams struct {
	ID                   ids.UUID        `db:"id" json:"id"`
	ParentConversationID ids.UUID        `db:"parent_conversation_id" json:"parent_conversation_id"`
	ChildConversationID  ids.UUID        `db:"child_conversation_id" json:"child_conversation_id"`
	CheckpointID         ids.UUID        `db:"checkpoint_id" json:"checkpoint_id"`
	MetadataJson         json.RawMessage `db:"metadata_json" json:"metadata_json"`
}

// CreateAgentConversationFork
//
//	INSERT INTO agent_conversation_forks (
//	    id, parent_conversation_id, child_conversation_id, checkpoint_id, metadata_json
//	)
//	VALUES (?, ?, ?, ?, ?)
//	RETURNING id, parent_conversation_id, child_conversation_id, checkpoint_id, metadata_json, created_at, updated_at
func (q *Queries) CreateAgentConversationFork(ctx context.Context, arg CreateAgentConversationForkParams) (AgentConversationFork, error) {
	row := q.db.QueryRowContext(ctx, CreateAgentConversationFork,
		arg.ID,
		arg.ParentConversationID,
		arg.ChildConversationID,
		arg.CheckpointID,
		arg.MetadataJson,
	)
	var i AgentConversationFork
	err := row.Scan(
		&i.ID,
		&i.ParentConversationID,
		&i.ChildConversationID,
		&i.CheckpointID,
		&i.MetadataJson,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const GetAgentConversationForkByChildConversationID = `-- name: GetAgentConversationForkByChildConversationID :one
SELECT id, parent_conversation_id, child_conversation_id, checkpoint_id, metadata_json, created_at, updated_at FROM agent_conversation_forks
WHERE child_conversation_id = ?
LIMIT 1
`

type GetAgentConversationForkByChildConversationIDParams struct {
	ChildConversationID ids.UUID `db:"child_conversation_id" json:"child_conversation_id"`
}

// GetAgentConversationForkByChildConversationID
//
//	SELECT id, parent_conversation_id, child_conversation_id, checkpoint_id, metadata_json, created_at, updated_at FROM agent_conversation_forks
//	WHERE child_conversation_id = ?
//	LIMIT 1
func (q *Queries) GetAgentConversationForkByChildConversationID(ctx context.Context, arg GetAgentConversationForkByChildConversationIDParams) (AgentConversationFork, error) {
	row := q.db.QueryRowContext(ctx, GetAgentConversationForkByChildConversationID, arg.ChildConversationID)
	var i AgentConversationFork
	err := row.Scan(
		&i.ID,
		&i.ParentConversationID,
		&i.ChildConversationID,
		&i.CheckpointID,
		&i.MetadataJson,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const ListAgentConversationForksByParentConversationID = `-- name: ListAgentConversationForksByParentConversationID :many
SELECT id, parent_conversation_id, child_conversation_id, checkpoint_id, metadata_json, created_at, updated_at FROM agent_conversation_forks
WHERE parent_conversation_id = ?
ORDER BY created_at DESC
LIMIT ?2
`

type ListAgentConversationForksByParentConversationIDParams struct {
	ParentConversationID ids.UUID `db:"parent_conversation_id" json:"parent_conversation_id"`
	Lim                  int64    `db:"lim" json:"lim"`
}

// ListAgentConversationForksByParentConversationID
//
//	SELECT id, parent_conversation_id, child_conversation_id, checkpoint_id, metadata_json, created_at, updated_at FROM agent_conversation_forks
//	WHERE parent_conversation_id = ?
//	ORDER BY created_at DESC
//	LIMIT ?2
func (q *Queries) ListAgentConversationForksByParentConversationID(ctx context.Context, arg ListAgentConversationForksByParentConversationIDParams) ([]AgentConversationFork, error) {
	rows, err := q.db.QueryContext(ctx, ListAgentConversationForksByParentConversationID, arg.ParentConversationID, arg.Lim)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []AgentConversationFork{}
	for rows.Next() {
		var i AgentConversationFork
		if err := rows.Scan(
			&i.ID,
			&i.ParentConversationID,
			&i.ChildConversationID,
			&i.CheckpointID,
			&i.MetadataJson,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
