// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: agent_state.sql

package sqlc

import (
	"context"
	"encoding/json"
	"time"

	"github.com/sipeed/picoclaw/pkg/ids"
)

const AddAgentRunState = `-- name: AddAgentRunState :one
INSERT INTO agent_run_states (id, run_id, step_index, state, snapshot_json)
VALUES (?, ?, ?, ?, ?)
RETURNING id, run_id, step_index, state, snapshot_json, created_at, updated_at
`

type AddAgentRunStateParams struct {
	ID           ids.UUID        `db:"id" json:"id"`
	RunID        ids.UUID        `db:"run_id" json:"run_id"`
	StepIndex    int64           `db:"step_index" json:"step_index"`
	State        string          `db:"state" json:"state"`
	SnapshotJson json.RawMessage `db:"snapshot_json" json:"snapshot_json"`
}

// AddAgentRunState
//
//	INSERT INTO agent_run_states (id, run_id, step_index, state, snapshot_json)
//	VALUES (?, ?, ?, ?, ?)
//	RETURNING id, run_id, step_index, state, snapshot_json, created_at, updated_at
func (q *Queries) AddAgentRunState(ctx context.Context, arg AddAgentRunStateParams) (AgentRunState, error) {
	row := q.db.QueryRowContext(ctx, AddAgentRunState,
		arg.ID,
		arg.RunID,
		arg.StepIndex,
		arg.State,
		arg.SnapshotJson,
	)
	var i AgentRunState
	err := row.Scan(
		&i.ID,
		&i.RunID,
		&i.StepIndex,
		&i.State,
		&i.SnapshotJson,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const AddAgentStateTransition = `-- name: AddAgentStateTransition :one
INSERT INTO agent_state_transitions (
    id, run_id, step_index, from_state, to_state, trigger, at, meta_json, error
)
VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?)
RETURNING id, run_id, step_index, from_state, to_state, "trigger", at, meta_json, error, created_at, updated_at
`

type AddAgentStateTransitionParams struct {
	ID        ids.UUID        `db:"id" json:"id"`
	RunID     ids.UUID        `db:"run_id" json:"run_id"`
	StepIndex int64           `db:"step_index" json:"step_index"`
	FromState string          `db:"from_state" json:"from_state"`
	ToState   string          `db:"to_state" json:"to_state"`
	Trigger   string          `db:"trigger" json:"trigger"`
	At        time.Time       `db:"at" json:"at"`
	MetaJson  json.RawMessage `db:"meta_json" json:"meta_json"`
	Error     *string         `db:"error" json:"error"`
}

// AddAgentStateTransition
//
//	INSERT INTO agent_state_transitions (
//	    id, run_id, step_index, from_state, to_state, trigger, at, meta_json, error
//	)
//	VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?)
//	RETURNING id, run_id, step_index, from_state, to_state, "trigger", at, meta_json, error, created_at, updated_at
func (q *Queries) AddAgentStateTransition(ctx context.Context, arg AddAgentStateTransitionParams) (AgentStateTransition, error) {
	row := q.db.QueryRowContext(ctx, AddAgentStateTransition,
		arg.ID,
		arg.RunID,
		arg.StepIndex,
		arg.FromState,
		arg.ToState,
		arg.Trigger,
		arg.At,
		arg.MetaJson,
		arg.Error,
	)
	var i AgentStateTransition
	err := row.Scan(
		&i.ID,
		&i.RunID,
		&i.StepIndex,
		&i.FromState,
		&i.ToState,
		&i.Trigger,
		&i.At,
		&i.MetaJson,
		&i.Error,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const CreateAgentCheckpoint = `-- name: CreateAgentCheckpoint :one
INSERT INTO agent_checkpoints (id, conversation_id, name, run_state_id, metadata_json)
VALUES (?, ?, ?, ?, ?)
RETURNING id, conversation_id, name, run_state_id, metadata_json, created_at, updated_at
`

type CreateAgentCheckpointParams struct {
	ID             ids.UUID        `db:"id" json:"id"`
	ConversationID ids.UUID        `db:"conversation_id" json:"conversation_id"`
	Name           string          `db:"name" json:"name"`
	RunStateID     ids.UUID        `db:"run_state_id" json:"run_state_id"`
	MetadataJson   json.RawMessage `db:"metadata_json" json:"metadata_json"`
}

// CreateAgentCheckpoint
//
//	INSERT INTO agent_checkpoints (id, conversation_id, name, run_state_id, metadata_json)
//	VALUES (?, ?, ?, ?, ?)
//	RETURNING id, conversation_id, name, run_state_id, metadata_json, created_at, updated_at
func (q *Queries) CreateAgentCheckpoint(ctx context.Context, arg CreateAgentCheckpointParams) (AgentCheckpoint, error) {
	row := q.db.QueryRowContext(ctx, CreateAgentCheckpoint,
		arg.ID,
		arg.ConversationID,
		arg.Name,
		arg.RunStateID,
		arg.MetadataJson,
	)
	var i AgentCheckpoint
	err := row.Scan(
		&i.ID,
		&i.ConversationID,
		&i.Name,
		&i.RunStateID,
		&i.MetadataJson,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const CreateAgentRun = `-- name: CreateAgentRun :one
INSERT INTO agent_runs (id, conversation_id, status, metadata_json)
VALUES (?, ?, ?, ?)
RETURNING id, conversation_id, status, metadata_json, created_at, updated_at
`

type CreateAgentRunParams struct {
	ID             ids.UUID        `db:"id" json:"id"`
	ConversationID ids.UUID        `db:"conversation_id" json:"conversation_id"`
	Status         string          `db:"status" json:"status"`
	MetadataJson   json.RawMessage `db:"metadata_json" json:"metadata_json"`
}

// CreateAgentRun
//
//	INSERT INTO agent_runs (id, conversation_id, status, metadata_json)
//	VALUES (?, ?, ?, ?)
//	RETURNING id, conversation_id, status, metadata_json, created_at, updated_at
func (q *Queries) CreateAgentRun(ctx context.Context, arg CreateAgentRunParams) (AgentRun, error) {
	row := q.db.QueryRowContext(ctx, CreateAgentRun,
		arg.ID,
		arg.ConversationID,
		arg.Status,
		arg.MetadataJson,
	)
	var i AgentRun
	err := row.Scan(
		&i.ID,
		&i.ConversationID,
		&i.Status,
		&i.MetadataJson,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const GetAgentCheckpointByConversationIDAndName = `-- name: GetAgentCheckpointByConversationIDAndName :one
SELECT id, conversation_id, name, run_state_id, metadata_json, created_at, updated_at FROM agent_checkpoints
WHERE conversation_id = ? AND name = ?
LIMIT 1
`

type GetAgentCheckpointByConversationIDAndNameParams struct {
	ConversationID ids.UUID `db:"conversation_id" json:"conversation_id"`
	Name           string   `db:"name" json:"name"`
}

// GetAgentCheckpointByConversationIDAndName
//
//	SELECT id, conversation_id, name, run_state_id, metadata_json, created_at, updated_at FROM agent_checkpoints
//	WHERE conversation_id = ? AND name = ?
//	LIMIT 1
func (q *Queries) GetAgentCheckpointByConversationIDAndName(ctx context.Context, arg GetAgentCheckpointByConversationIDAndNameParams) (AgentCheckpoint, error) {
	row := q.db.QueryRowContext(ctx, GetAgentCheckpointByConversationIDAndName, arg.ConversationID, arg.Name)
	var i AgentCheckpoint
	err := row.Scan(
		&i.ID,
		&i.ConversationID,
		&i.Name,
		&i.RunStateID,
		&i.MetadataJson,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const GetAgentRunStateByID = `-- name: GetAgentRunStateByID :one
SELECT id, run_id, step_index, state, snapshot_json, created_at, updated_at FROM agent_run_states
WHERE id = ?
LIMIT 1
`

type GetAgentRunStateByIDParams struct {
	ID ids.UUID `db:"id" json:"id"`
}

// GetAgentRunStateByID
//
//	SELECT id, run_id, step_index, state, snapshot_json, created_at, updated_at FROM agent_run_states
//	WHERE id = ?
//	LIMIT 1
func (q *Queries) GetAgentRunStateByID(ctx context.Context, arg GetAgentRunStateByIDParams) (AgentRunState, error) {
	row := q.db.QueryRowContext(ctx, GetAgentRunStateByID, arg.ID)
	var i AgentRunState
	err := row.Scan(
		&i.ID,
		&i.RunID,
		&i.StepIndex,
		&i.State,
		&i.SnapshotJson,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const GetLatestAgentRunByConversationID = `-- name: GetLatestAgentRunByConversationID :one
SELECT id, conversation_id, status, metadata_json, created_at, updated_at FROM agent_runs
WHERE conversation_id = ?
ORDER BY created_at DESC
LIMIT 1
`

type GetLatestAgentRunByConversationIDParams struct {
	ConversationID ids.UUID `db:"conversation_id" json:"conversation_id"`
}

// GetLatestAgentRunByConversationID
//
//	SELECT id, conversation_id, status, metadata_json, created_at, updated_at FROM agent_runs
//	WHERE conversation_id = ?
//	ORDER BY created_at DESC
//	LIMIT 1
func (q *Queries) GetLatestAgentRunByConversationID(ctx context.Context, arg GetLatestAgentRunByConversationIDParams) (AgentRun, error) {
	row := q.db.QueryRowContext(ctx, GetLatestAgentRunByConversationID, arg.ConversationID)
	var i AgentRun
	err := row.Scan(
		&i.ID,
		&i.ConversationID,
		&i.Status,
		&i.MetadataJson,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const GetLatestAgentRunStateByRunID = `-- name: GetLatestAgentRunStateByRunID :one
SELECT id, run_id, step_index, state, snapshot_json, created_at, updated_at FROM agent_run_states
WHERE run_id = ?
ORDER BY step_index DESC
LIMIT 1
`

type GetLatestAgentRunStateByRunIDParams struct {
	RunID ids.UUID `db:"run_id" json:"run_id"`
}

// GetLatestAgentRunStateByRunID
//
//	SELECT id, run_id, step_index, state, snapshot_json, created_at, updated_at FROM agent_run_states
//	WHERE run_id = ?
//	ORDER BY step_index DESC
//	LIMIT 1
func (q *Queries) GetLatestAgentRunStateByRunID(ctx context.Context, arg GetLatestAgentRunStateByRunIDParams) (AgentRunState, error) {
	row := q.db.QueryRowContext(ctx, GetLatestAgentRunStateByRunID, arg.RunID)
	var i AgentRunState
	err := row.Scan(
		&i.ID,
		&i.RunID,
		&i.StepIndex,
		&i.State,
		&i.SnapshotJson,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const ListAgentCheckpointsByConversationID = `-- name: ListAgentCheckpointsByConversationID :many
SELECT id, conversation_id, name, run_state_id, metadata_json, created_at, updated_at FROM agent_checkpoints
WHERE conversation_id = ?
ORDER BY created_at DESC
LIMIT ?2
`

type ListAgentCheckpointsByConversationIDParams struct {
	ConversationID ids.UUID `db:"conversation_id" json:"conversation_id"`
	Lim            int64    `db:"lim" json:"lim"`
}

// ListAgentCheckpointsByConversationID
//
//	SELECT id, conversation_id, name, run_state_id, metadata_json, created_at, updated_at FROM agent_checkpoints
//	WHERE conversation_id = ?
//	ORDER BY created_at DESC
//	LIMIT ?2
func (q *Queries) ListAgentCheckpointsByConversationID(ctx context.Context, arg ListAgentCheckpointsByConversationIDParams) ([]AgentCheckpoint, error) {
	rows, err := q.db.QueryContext(ctx, ListAgentCheckpointsByConversationID, arg.ConversationID, arg.Lim)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []AgentCheckpoint{}
	for rows.Next() {
		var i AgentCheckpoint
		if err := rows.Scan(
			&i.ID,
			&i.ConversationID,
			&i.Name,
			&i.RunStateID,
			&i.MetadataJson,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const ListAgentRunStatesByRunID = `-- name: ListAgentRunStatesByRunID :many
SELECT id, run_id, step_index, state, snapshot_json, created_at, updated_at FROM agent_run_states
WHERE run_id = ?
ORDER BY step_index ASC
LIMIT ?2
`

type ListAgentRunStatesByRunIDParams struct {
	RunID ids.UUID `db:"run_id" json:"run_id"`
	Lim   int64    `db:"lim" json:"lim"`
}

// ListAgentRunStatesByRunID
//
//	SELECT id, run_id, step_index, state, snapshot_json, created_at, updated_at FROM agent_run_states
//	WHERE run_id = ?
//	ORDER BY step_index ASC
//	LIMIT ?2
func (q *Queries) ListAgentRunStatesByRunID(ctx context.Context, arg ListAgentRunStatesByRunIDParams) ([]AgentRunState, error) {
	rows, err := q.db.QueryContext(ctx, ListAgentRunStatesByRunID, arg.RunID, arg.Lim)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []AgentRunState{}
	for rows.Next() {
		var i AgentRunState
		if err := rows.Scan(
			&i.ID,
			&i.RunID,
			&i.StepIndex,
			&i.State,
			&i.SnapshotJson,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const ListAgentStateTransitionsByRunID = `-- name: ListAgentStateTransitionsByRunID :many
SELECT id, run_id, step_index, from_state, to_state, "trigger", at, meta_json, error, created_at, updated_at FROM agent_state_transitions
WHERE run_id = ?
ORDER BY at ASC
LIMIT ?2
`

type ListAgentStateTransitionsByRunIDParams struct {
	RunID ids.UUID `db:"run_id" json:"run_id"`
	Lim   int64    `db:"lim" json:"lim"`
}

// ListAgentStateTransitionsByRunID
//
//	SELECT id, run_id, step_index, from_state, to_state, "trigger", at, meta_json, error, created_at, updated_at FROM agent_state_transitions
//	WHERE run_id = ?
//	ORDER BY at ASC
//	LIMIT ?2
func (q *Queries) ListAgentStateTransitionsByRunID(ctx context.Context, arg ListAgentStateTransitionsByRunIDParams) ([]AgentStateTransition, error) {
	rows, err := q.db.QueryContext(ctx, ListAgentStateTransitionsByRunID, arg.RunID, arg.Lim)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []AgentStateTransition{}
	for rows.Next() {
		var i AgentStateTransition
		if err := rows.Scan(
			&i.ID,
			&i.RunID,
			&i.StepIndex,
			&i.FromState,
			&i.ToState,
			&i.Trigger,
			&i.At,
			&i.MetaJson,
			&i.Error,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const UpdateAgentRunStatus = `-- name: UpdateAgentRunStatus :one
UPDATE agent_runs
SET status = ?,
    metadata_json = ?,
    updated_at = (strftime('%Y-%m-%dT%H:%M:%fZ', 'now'))
WHERE id = ?
RETURNING id, conversation_id, status, metadata_json, created_at, updated_at
`

type UpdateAgentRunStatusParams struct {
	Status       string          `db:"status" json:"status"`
	MetadataJson json.RawMessage `db:"metadata_json" json:"metadata_json"`
	ID           ids.UUID        `db:"id" json:"id"`
}

// UpdateAgentRunStatus
//
//	UPDATE agent_runs
//	SET status = ?,
//	    metadata_json = ?,
//	    updated_at = (strftime('%Y-%m-%dT%H:%M:%fZ', 'now'))
//	WHERE id = ?
//	RETURNING id, conversation_id, status, metadata_json, created_at, updated_at
func (q *Queries) UpdateAgentRunStatus(ctx context.Context, arg UpdateAgentRunStatusParams) (AgentRun, error) {
	row := q.db.QueryRowContext(ctx, UpdateAgentRunStatus, arg.Status, arg.MetadataJson, arg.ID)
	var i AgentRun
	err := row.Scan(
		&i.ID,
		&i.ConversationID,
		&i.Status,
		&i.MetadataJson,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
