// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: agent_audit_log.sql

package sqlc

import (
	"context"
	"time"

	"github.com/ZanzyTHEbar/dragonscale/pkg/ids"
)

const CountAuditEntries = `-- name: CountAuditEntries :one
SELECT COUNT(*)
FROM agent_audit_log
WHERE agent_id = ?1
`

type CountAuditEntriesParams struct {
	AgentID string `db:"agent_id" json:"agent_id"`
}

// CountAuditEntries
//
//	SELECT COUNT(*)
//	FROM agent_audit_log
//	WHERE agent_id = ?1
func (q *Queries) CountAuditEntries(ctx context.Context, arg CountAuditEntriesParams) (int64, error) {
	row := q.db.QueryRowContext(ctx, CountAuditEntries, arg.AgentID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const CountAuditEntriesByAction = `-- name: CountAuditEntriesByAction :one
SELECT COUNT(*)
FROM agent_audit_log
WHERE agent_id = ?1
    AND action = ?2
`

type CountAuditEntriesByActionParams struct {
	AgentID string `db:"agent_id" json:"agent_id"`
	Action  string `db:"action" json:"action"`
}

// CountAuditEntriesByAction
//
//	SELECT COUNT(*)
//	FROM agent_audit_log
//	WHERE agent_id = ?1
//	    AND action = ?2
func (q *Queries) CountAuditEntriesByAction(ctx context.Context, arg CountAuditEntriesByActionParams) (int64, error) {
	row := q.db.QueryRowContext(ctx, CountAuditEntriesByAction, arg.AgentID, arg.Action)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const InsertAuditEntry = `-- name: InsertAuditEntry :one
INSERT INTO agent_audit_log (
        id,
        agent_id,
        session_key,
        action,
        target,
        input,
        output,
        duration_ms,
        created_at
    )
VALUES (
        ?1,
        ?2,
        ?3,
        ?4,
        ?5,
        ?6,
        ?7,
        ?8,
        strftime('%Y-%m-%dT%H:%M:%fZ', 'now')
    )
RETURNING id,
    agent_id,
    session_key,
    action,
    target,
    input,
    output,
    duration_ms,
    created_at
`

type InsertAuditEntryParams struct {
	ID         ids.UUID `db:"id" json:"id"`
	AgentID    string   `db:"agent_id" json:"agent_id"`
	SessionKey string   `db:"session_key" json:"session_key"`
	Action     string   `db:"action" json:"action"`
	Target     string   `db:"target" json:"target"`
	Input      *string  `db:"input" json:"input"`
	Output     *string  `db:"output" json:"output"`
	DurationMs *int64   `db:"duration_ms" json:"duration_ms"`
}

// Agent Audit Log queries
//
//	INSERT INTO agent_audit_log (
//	        id,
//	        agent_id,
//	        session_key,
//	        action,
//	        target,
//	        input,
//	        output,
//	        duration_ms,
//	        created_at
//	    )
//	VALUES (
//	        ?1,
//	        ?2,
//	        ?3,
//	        ?4,
//	        ?5,
//	        ?6,
//	        ?7,
//	        ?8,
//	        strftime('%Y-%m-%dT%H:%M:%fZ', 'now')
//	    )
//	RETURNING id,
//	    agent_id,
//	    session_key,
//	    action,
//	    target,
//	    input,
//	    output,
//	    duration_ms,
//	    created_at
func (q *Queries) InsertAuditEntry(ctx context.Context, arg InsertAuditEntryParams) (AgentAuditLog, error) {
	row := q.db.QueryRowContext(ctx, InsertAuditEntry,
		arg.ID,
		arg.AgentID,
		arg.SessionKey,
		arg.Action,
		arg.Target,
		arg.Input,
		arg.Output,
		arg.DurationMs,
	)
	var i AgentAuditLog
	err := row.Scan(
		&i.ID,
		&i.AgentID,
		&i.SessionKey,
		&i.Action,
		&i.Target,
		&i.Input,
		&i.Output,
		&i.DurationMs,
		&i.CreatedAt,
	)
	return i, err
}

const ListAuditEntries = `-- name: ListAuditEntries :many
SELECT id,
    agent_id,
    session_key,
    action,
    target,
    input,
    output,
    duration_ms,
    created_at
FROM agent_audit_log
WHERE agent_id = ?1
ORDER BY created_at DESC
LIMIT ?2
`

type ListAuditEntriesParams struct {
	AgentID string `db:"agent_id" json:"agent_id"`
	Lim     int64  `db:"lim" json:"lim"`
}

// ListAuditEntries
//
//	SELECT id,
//	    agent_id,
//	    session_key,
//	    action,
//	    target,
//	    input,
//	    output,
//	    duration_ms,
//	    created_at
//	FROM agent_audit_log
//	WHERE agent_id = ?1
//	ORDER BY created_at DESC
//	LIMIT ?2
func (q *Queries) ListAuditEntries(ctx context.Context, arg ListAuditEntriesParams) ([]AgentAuditLog, error) {
	rows, err := q.db.QueryContext(ctx, ListAuditEntries, arg.AgentID, arg.Lim)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []AgentAuditLog{}
	for rows.Next() {
		var i AgentAuditLog
		if err := rows.Scan(
			&i.ID,
			&i.AgentID,
			&i.SessionKey,
			&i.Action,
			&i.Target,
			&i.Input,
			&i.Output,
			&i.DurationMs,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const ListAuditEntriesByAction = `-- name: ListAuditEntriesByAction :many
SELECT id,
    agent_id,
    session_key,
    action,
    target,
    input,
    output,
    duration_ms,
    created_at
FROM agent_audit_log
WHERE agent_id = ?1
    AND action = ?2
ORDER BY created_at DESC
LIMIT ?3
`

type ListAuditEntriesByActionParams struct {
	AgentID string `db:"agent_id" json:"agent_id"`
	Action  string `db:"action" json:"action"`
	Lim     int64  `db:"lim" json:"lim"`
}

// ListAuditEntriesByAction
//
//	SELECT id,
//	    agent_id,
//	    session_key,
//	    action,
//	    target,
//	    input,
//	    output,
//	    duration_ms,
//	    created_at
//	FROM agent_audit_log
//	WHERE agent_id = ?1
//	    AND action = ?2
//	ORDER BY created_at DESC
//	LIMIT ?3
func (q *Queries) ListAuditEntriesByAction(ctx context.Context, arg ListAuditEntriesByActionParams) ([]AgentAuditLog, error) {
	rows, err := q.db.QueryContext(ctx, ListAuditEntriesByAction, arg.AgentID, arg.Action, arg.Lim)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []AgentAuditLog{}
	for rows.Next() {
		var i AgentAuditLog
		if err := rows.Scan(
			&i.ID,
			&i.AgentID,
			&i.SessionKey,
			&i.Action,
			&i.Target,
			&i.Input,
			&i.Output,
			&i.DurationMs,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const ListAuditEntriesBySession = `-- name: ListAuditEntriesBySession :many
SELECT id,
    agent_id,
    session_key,
    action,
    target,
    input,
    output,
    duration_ms,
    created_at
FROM agent_audit_log
WHERE agent_id = ?1
    AND session_key = ?2
ORDER BY created_at DESC
LIMIT ?3
`

type ListAuditEntriesBySessionParams struct {
	AgentID    string `db:"agent_id" json:"agent_id"`
	SessionKey string `db:"session_key" json:"session_key"`
	Lim        int64  `db:"lim" json:"lim"`
}

// ListAuditEntriesBySession
//
//	SELECT id,
//	    agent_id,
//	    session_key,
//	    action,
//	    target,
//	    input,
//	    output,
//	    duration_ms,
//	    created_at
//	FROM agent_audit_log
//	WHERE agent_id = ?1
//	    AND session_key = ?2
//	ORDER BY created_at DESC
//	LIMIT ?3
func (q *Queries) ListAuditEntriesBySession(ctx context.Context, arg ListAuditEntriesBySessionParams) ([]AgentAuditLog, error) {
	rows, err := q.db.QueryContext(ctx, ListAuditEntriesBySession, arg.AgentID, arg.SessionKey, arg.Lim)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []AgentAuditLog{}
	for rows.Next() {
		var i AgentAuditLog
		if err := rows.Scan(
			&i.ID,
			&i.AgentID,
			&i.SessionKey,
			&i.Action,
			&i.Target,
			&i.Input,
			&i.Output,
			&i.DurationMs,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const ListAuditEntriesGlobal = `-- name: ListAuditEntriesGlobal :many
SELECT id,
    agent_id,
    session_key,
    action,
    target,
    input,
    output,
    duration_ms,
    created_at
FROM agent_audit_log
ORDER BY created_at DESC
LIMIT ?1
`

type ListAuditEntriesGlobalParams struct {
	Lim int64 `db:"lim" json:"lim"`
}

// ListAuditEntriesGlobal
//
//	SELECT id,
//	    agent_id,
//	    session_key,
//	    action,
//	    target,
//	    input,
//	    output,
//	    duration_ms,
//	    created_at
//	FROM agent_audit_log
//	ORDER BY created_at DESC
//	LIMIT ?1
func (q *Queries) ListAuditEntriesGlobal(ctx context.Context, arg ListAuditEntriesGlobalParams) ([]AgentAuditLog, error) {
	rows, err := q.db.QueryContext(ctx, ListAuditEntriesGlobal, arg.Lim)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []AgentAuditLog{}
	for rows.Next() {
		var i AgentAuditLog
		if err := rows.Scan(
			&i.ID,
			&i.AgentID,
			&i.SessionKey,
			&i.Action,
			&i.Target,
			&i.Input,
			&i.Output,
			&i.DurationMs,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const ListAuditEntriesGlobalSincePaged = `-- name: ListAuditEntriesGlobalSincePaged :many
SELECT id,
    agent_id,
    session_key,
    action,
    target,
    input,
    output,
    duration_ms,
    created_at
FROM agent_audit_log
WHERE julianday(created_at) > julianday(?1)
ORDER BY created_at ASC, id ASC
LIMIT ?3 OFFSET ?2
`

type ListAuditEntriesGlobalSincePagedParams struct {
	Since interface{} `db:"since" json:"since"`
	Off   int64       `db:"off" json:"off"`
	Lim   int64       `db:"lim" json:"lim"`
}

// ListAuditEntriesGlobalSincePaged
//
//	SELECT id,
//	    agent_id,
//	    session_key,
//	    action,
//	    target,
//	    input,
//	    output,
//	    duration_ms,
//	    created_at
//	FROM agent_audit_log
//	WHERE julianday(created_at) > julianday(?1)
//	ORDER BY created_at ASC, id ASC
//	LIMIT ?3 OFFSET ?2
func (q *Queries) ListAuditEntriesGlobalSincePaged(ctx context.Context, arg ListAuditEntriesGlobalSincePagedParams) ([]AgentAuditLog, error) {
	rows, err := q.db.QueryContext(ctx, ListAuditEntriesGlobalSincePaged, arg.Since, arg.Off, arg.Lim)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []AgentAuditLog{}
	for rows.Next() {
		var i AgentAuditLog
		if err := rows.Scan(
			&i.ID,
			&i.AgentID,
			&i.SessionKey,
			&i.Action,
			&i.Target,
			&i.Input,
			&i.Output,
			&i.DurationMs,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const PruneOldAuditEntries = `-- name: PruneOldAuditEntries :exec
DELETE FROM agent_audit_log
WHERE agent_id = ?1
    AND created_at < ?2
`

type PruneOldAuditEntriesParams struct {
	AgentID string    `db:"agent_id" json:"agent_id"`
	Before  time.Time `db:"before" json:"before"`
}

// PruneOldAuditEntries
//
//	DELETE FROM agent_audit_log
//	WHERE agent_id = ?1
//	    AND created_at < ?2
func (q *Queries) PruneOldAuditEntries(ctx context.Context, arg PruneOldAuditEntriesParams) error {
	_, err := q.db.ExecContext(ctx, PruneOldAuditEntries, arg.AgentID, arg.Before)
	return err
}
