// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: agent_conversation_links.sql

package sqlc

import (
	"context"
	"encoding/json"

	"github.com/sipeed/picoclaw/pkg/ids"
)

const CreateAgentConversationLink = `-- name: CreateAgentConversationLink :one
INSERT INTO agent_conversation_links (
    id, conversation_id, linked_conversation_id, kind, metadata_json
)
VALUES (?, ?, ?, ?, ?)
RETURNING id, conversation_id, linked_conversation_id, kind, metadata_json, created_at, updated_at
`

type CreateAgentConversationLinkParams struct {
	ID                   ids.UUID        `db:"id" json:"id"`
	ConversationID       ids.UUID        `db:"conversation_id" json:"conversation_id"`
	LinkedConversationID ids.UUID        `db:"linked_conversation_id" json:"linked_conversation_id"`
	Kind                 string          `db:"kind" json:"kind"`
	MetadataJson         json.RawMessage `db:"metadata_json" json:"metadata_json"`
}

// CreateAgentConversationLink
//
//	INSERT INTO agent_conversation_links (
//	    id, conversation_id, linked_conversation_id, kind, metadata_json
//	)
//	VALUES (?, ?, ?, ?, ?)
//	RETURNING id, conversation_id, linked_conversation_id, kind, metadata_json, created_at, updated_at
func (q *Queries) CreateAgentConversationLink(ctx context.Context, arg CreateAgentConversationLinkParams) (AgentConversationLink, error) {
	row := q.db.QueryRowContext(ctx, CreateAgentConversationLink,
		arg.ID,
		arg.ConversationID,
		arg.LinkedConversationID,
		arg.Kind,
		arg.MetadataJson,
	)
	var i AgentConversationLink
	err := row.Scan(
		&i.ID,
		&i.ConversationID,
		&i.LinkedConversationID,
		&i.Kind,
		&i.MetadataJson,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const DeleteAgentConversationLink = `-- name: DeleteAgentConversationLink :exec
DELETE FROM agent_conversation_links
WHERE conversation_id = ? AND linked_conversation_id = ? AND kind = ?
`

type DeleteAgentConversationLinkParams struct {
	ConversationID       ids.UUID `db:"conversation_id" json:"conversation_id"`
	LinkedConversationID ids.UUID `db:"linked_conversation_id" json:"linked_conversation_id"`
	Kind                 string   `db:"kind" json:"kind"`
}

// DeleteAgentConversationLink
//
//	DELETE FROM agent_conversation_links
//	WHERE conversation_id = ? AND linked_conversation_id = ? AND kind = ?
func (q *Queries) DeleteAgentConversationLink(ctx context.Context, arg DeleteAgentConversationLinkParams) error {
	_, err := q.db.ExecContext(ctx, DeleteAgentConversationLink, arg.ConversationID, arg.LinkedConversationID, arg.Kind)
	return err
}

const ListAgentConversationLinksByConversationID = `-- name: ListAgentConversationLinksByConversationID :many
SELECT id, conversation_id, linked_conversation_id, kind, metadata_json, created_at, updated_at FROM agent_conversation_links
WHERE conversation_id = ?
ORDER BY created_at DESC
LIMIT ?2
`

type ListAgentConversationLinksByConversationIDParams struct {
	ConversationID ids.UUID `db:"conversation_id" json:"conversation_id"`
	Lim            int64    `db:"lim" json:"lim"`
}

// ListAgentConversationLinksByConversationID
//
//	SELECT id, conversation_id, linked_conversation_id, kind, metadata_json, created_at, updated_at FROM agent_conversation_links
//	WHERE conversation_id = ?
//	ORDER BY created_at DESC
//	LIMIT ?2
func (q *Queries) ListAgentConversationLinksByConversationID(ctx context.Context, arg ListAgentConversationLinksByConversationIDParams) ([]AgentConversationLink, error) {
	rows, err := q.db.QueryContext(ctx, ListAgentConversationLinksByConversationID, arg.ConversationID, arg.Lim)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []AgentConversationLink{}
	for rows.Next() {
		var i AgentConversationLink
		if err := rows.Scan(
			&i.ID,
			&i.ConversationID,
			&i.LinkedConversationID,
			&i.Kind,
			&i.MetadataJson,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
