// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: agent_messages.sql

package sqlc

import (
	"context"
	"encoding/json"

	"github.com/ZanzyTHEbar/dragonscale/pkg/ids"
)

const AddAgentMessage = `-- name: AddAgentMessage :one
INSERT INTO agent_messages (
        id,
        conversation_id,
        role,
        content,
        metadata_json
    )
VALUES (?, ?, ?, ?, ?)
RETURNING id, conversation_id, role, content, metadata_json, created_at, updated_at
`

type AddAgentMessageParams struct {
	ID             ids.UUID        `db:"id" json:"id"`
	ConversationID ids.UUID        `db:"conversation_id" json:"conversation_id"`
	Role           string          `db:"role" json:"role"`
	Content        string          `db:"content" json:"content"`
	MetadataJson   json.RawMessage `db:"metadata_json" json:"metadata_json"`
}

// AddAgentMessage
//
//	INSERT INTO agent_messages (
//	        id,
//	        conversation_id,
//	        role,
//	        content,
//	        metadata_json
//	    )
//	VALUES (?, ?, ?, ?, ?)
//	RETURNING id, conversation_id, role, content, metadata_json, created_at, updated_at
func (q *Queries) AddAgentMessage(ctx context.Context, arg AddAgentMessageParams) (AgentMessage, error) {
	row := q.db.QueryRowContext(ctx, AddAgentMessage,
		arg.ID,
		arg.ConversationID,
		arg.Role,
		arg.Content,
		arg.MetadataJson,
	)
	var i AgentMessage
	err := row.Scan(
		&i.ID,
		&i.ConversationID,
		&i.Role,
		&i.Content,
		&i.MetadataJson,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const GetAgentMessageByID = `-- name: GetAgentMessageByID :one
SELECT id, conversation_id, role, content, metadata_json, created_at, updated_at
FROM agent_messages
WHERE id = ?
LIMIT 1
`

type GetAgentMessageByIDParams struct {
	ID ids.UUID `db:"id" json:"id"`
}

// GetAgentMessageByID
//
//	SELECT id, conversation_id, role, content, metadata_json, created_at, updated_at
//	FROM agent_messages
//	WHERE id = ?
//	LIMIT 1
func (q *Queries) GetAgentMessageByID(ctx context.Context, arg GetAgentMessageByIDParams) (AgentMessage, error) {
	row := q.db.QueryRowContext(ctx, GetAgentMessageByID, arg.ID)
	var i AgentMessage
	err := row.Scan(
		&i.ID,
		&i.ConversationID,
		&i.Role,
		&i.Content,
		&i.MetadataJson,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const ListAgentMessagesByConversationID = `-- name: ListAgentMessagesByConversationID :many
SELECT id, conversation_id, role, content, metadata_json, created_at, updated_at
FROM agent_messages
WHERE conversation_id = ?
ORDER BY created_at ASC
`

type ListAgentMessagesByConversationIDParams struct {
	ConversationID ids.UUID `db:"conversation_id" json:"conversation_id"`
}

// ListAgentMessagesByConversationID
//
//	SELECT id, conversation_id, role, content, metadata_json, created_at, updated_at
//	FROM agent_messages
//	WHERE conversation_id = ?
//	ORDER BY created_at ASC
func (q *Queries) ListAgentMessagesByConversationID(ctx context.Context, arg ListAgentMessagesByConversationIDParams) ([]AgentMessage, error) {
	rows, err := q.db.QueryContext(ctx, ListAgentMessagesByConversationID, arg.ConversationID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []AgentMessage{}
	for rows.Next() {
		var i AgentMessage
		if err := rows.Scan(
			&i.ID,
			&i.ConversationID,
			&i.Role,
			&i.Content,
			&i.MetadataJson,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const ListAgentMessagesByConversationIDLimit = `-- name: ListAgentMessagesByConversationIDLimit :many
SELECT id, conversation_id, role, content, metadata_json, created_at, updated_at
FROM agent_messages
WHERE conversation_id = ?
ORDER BY created_at ASC
LIMIT ?
`

type ListAgentMessagesByConversationIDLimitParams struct {
	ConversationID ids.UUID `db:"conversation_id" json:"conversation_id"`
	Limit          int64    `db:"limit" json:"limit"`
}

// ListAgentMessagesByConversationIDLimit
//
//	SELECT id, conversation_id, role, content, metadata_json, created_at, updated_at
//	FROM agent_messages
//	WHERE conversation_id = ?
//	ORDER BY created_at ASC
//	LIMIT ?
func (q *Queries) ListAgentMessagesByConversationIDLimit(ctx context.Context, arg ListAgentMessagesByConversationIDLimitParams) ([]AgentMessage, error) {
	rows, err := q.db.QueryContext(ctx, ListAgentMessagesByConversationIDLimit, arg.ConversationID, arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []AgentMessage{}
	for rows.Next() {
		var i AgentMessage
		if err := rows.Scan(
			&i.ID,
			&i.ConversationID,
			&i.Role,
			&i.Content,
			&i.MetadataJson,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const UpdateAgentMessageContent = `-- name: UpdateAgentMessageContent :one
UPDATE agent_messages
SET content = ?
WHERE id = ?
RETURNING id, conversation_id, role, content, metadata_json, created_at, updated_at
`

type UpdateAgentMessageContentParams struct {
	Content string   `db:"content" json:"content"`
	ID      ids.UUID `db:"id" json:"id"`
}

// UpdateAgentMessageContent
//
//	UPDATE agent_messages
//	SET content = ?
//	WHERE id = ?
//	RETURNING id, conversation_id, role, content, metadata_json, created_at, updated_at
func (q *Queries) UpdateAgentMessageContent(ctx context.Context, arg UpdateAgentMessageContentParams) (AgentMessage, error) {
	row := q.db.QueryRowContext(ctx, UpdateAgentMessageContent, arg.Content, arg.ID)
	var i AgentMessage
	err := row.Scan(
		&i.ID,
		&i.ConversationID,
		&i.Role,
		&i.Content,
		&i.MetadataJson,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
