// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: agent_documents.sql

package sqlc

import (
	"context"

	"github.com/sipeed/picoclaw/pkg/ids"
)

const DeleteDocument = `-- name: DeleteDocument :exec
DELETE FROM agent_documents
WHERE agent_id = ?1
    AND name = ?2
`

type DeleteDocumentParams struct {
	AgentID string `json:"agent_id"`
	Name    string `json:"name"`
}

// DeleteDocument
//
//	DELETE FROM agent_documents
//	WHERE agent_id = ?1
//	    AND name = ?2
func (q *Queries) DeleteDocument(ctx context.Context, arg DeleteDocumentParams) error {
	_, err := q.db.ExecContext(ctx, DeleteDocument, arg.AgentID, arg.Name)
	return err
}

const GetDocument = `-- name: GetDocument :one
SELECT id,
    agent_id,
    name,
    category,
    content,
    version,
    is_active,
    created_at,
    updated_at
FROM agent_documents
WHERE agent_id = ?1
    AND name = ?2
`

type GetDocumentParams struct {
	AgentID string `json:"agent_id"`
	Name    string `json:"name"`
}

// Agent Documents queries
//
//	SELECT id,
//	    agent_id,
//	    name,
//	    category,
//	    content,
//	    version,
//	    is_active,
//	    created_at,
//	    updated_at
//	FROM agent_documents
//	WHERE agent_id = ?1
//	    AND name = ?2
func (q *Queries) GetDocument(ctx context.Context, arg GetDocumentParams) (AgentDocument, error) {
	row := q.db.QueryRowContext(ctx, GetDocument, arg.AgentID, arg.Name)
	var i AgentDocument
	err := row.Scan(
		&i.ID,
		&i.AgentID,
		&i.Name,
		&i.Category,
		&i.Content,
		&i.Version,
		&i.IsActive,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const ListAllDocuments = `-- name: ListAllDocuments :many
SELECT id,
    agent_id,
    name,
    category,
    content,
    version,
    is_active,
    created_at,
    updated_at
FROM agent_documents
WHERE agent_id = ?1
    AND is_active = 1
ORDER BY category,
    name
`

type ListAllDocumentsParams struct {
	AgentID string `json:"agent_id"`
}

// ListAllDocuments
//
//	SELECT id,
//	    agent_id,
//	    name,
//	    category,
//	    content,
//	    version,
//	    is_active,
//	    created_at,
//	    updated_at
//	FROM agent_documents
//	WHERE agent_id = ?1
//	    AND is_active = 1
//	ORDER BY category,
//	    name
func (q *Queries) ListAllDocuments(ctx context.Context, arg ListAllDocumentsParams) ([]AgentDocument, error) {
	rows, err := q.db.QueryContext(ctx, ListAllDocuments, arg.AgentID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []AgentDocument{}
	for rows.Next() {
		var i AgentDocument
		if err := rows.Scan(
			&i.ID,
			&i.AgentID,
			&i.Name,
			&i.Category,
			&i.Content,
			&i.Version,
			&i.IsActive,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const ListDocumentsByCategory = `-- name: ListDocumentsByCategory :many
SELECT id,
    agent_id,
    name,
    category,
    content,
    version,
    is_active,
    created_at,
    updated_at
FROM agent_documents
WHERE agent_id = ?1
    AND category = ?2
    AND is_active = 1
ORDER BY name
`

type ListDocumentsByCategoryParams struct {
	AgentID  string `json:"agent_id"`
	Category string `json:"category"`
}

// ListDocumentsByCategory
//
//	SELECT id,
//	    agent_id,
//	    name,
//	    category,
//	    content,
//	    version,
//	    is_active,
//	    created_at,
//	    updated_at
//	FROM agent_documents
//	WHERE agent_id = ?1
//	    AND category = ?2
//	    AND is_active = 1
//	ORDER BY name
func (q *Queries) ListDocumentsByCategory(ctx context.Context, arg ListDocumentsByCategoryParams) ([]AgentDocument, error) {
	rows, err := q.db.QueryContext(ctx, ListDocumentsByCategory, arg.AgentID, arg.Category)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []AgentDocument{}
	for rows.Next() {
		var i AgentDocument
		if err := rows.Scan(
			&i.ID,
			&i.AgentID,
			&i.Name,
			&i.Category,
			&i.Content,
			&i.Version,
			&i.IsActive,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const UpsertDocument = `-- name: UpsertDocument :exec
INSERT INTO agent_documents (
        id,
        agent_id,
        name,
        category,
        content,
        version,
        is_active,
        created_at,
        updated_at
    )
VALUES (
        ?1,
        ?2,
        ?3,
        ?4,
        ?5,
        1,
        1,
        datetime('now'),
        datetime('now')
    ) ON CONFLICT (agent_id, name) DO
UPDATE
SET content = excluded.content,
    category = excluded.category,
    version = agent_documents.version + 1,
    is_active = 1,
    updated_at = datetime('now')
`

type UpsertDocumentParams struct {
	ID       ids.UUID `json:"id"`
	AgentID  string   `json:"agent_id"`
	Name     string   `json:"name"`
	Category string   `json:"category"`
	Content  string   `json:"content"`
}

// UpsertDocument
//
//	INSERT INTO agent_documents (
//	        id,
//	        agent_id,
//	        name,
//	        category,
//	        content,
//	        version,
//	        is_active,
//	        created_at,
//	        updated_at
//	    )
//	VALUES (
//	        ?1,
//	        ?2,
//	        ?3,
//	        ?4,
//	        ?5,
//	        1,
//	        1,
//	        datetime('now'),
//	        datetime('now')
//	    ) ON CONFLICT (agent_id, name) DO
//	UPDATE
//	SET content = excluded.content,
//	    category = excluded.category,
//	    version = agent_documents.version + 1,
//	    is_active = 1,
//	    updated_at = datetime('now')
func (q *Queries) UpsertDocument(ctx context.Context, arg UpsertDocumentParams) error {
	_, err := q.db.ExecContext(ctx, UpsertDocument,
		arg.ID,
		arg.AgentID,
		arg.Name,
		arg.Category,
		arg.Content,
	)
	return err
}
