// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: agent_kv.sql

package sqlc

import (
	"context"
)

const DeleteKV = `-- name: DeleteKV :exec
DELETE FROM agent_kv
WHERE agent_id = ?1
    AND key = ?2
`

type DeleteKVParams struct {
	AgentID string `db:"agent_id" json:"agent_id"`
	Key     string `db:"key" json:"key"`
}

// DeleteKV
//
//	DELETE FROM agent_kv
//	WHERE agent_id = ?1
//	    AND key = ?2
func (q *Queries) DeleteKV(ctx context.Context, arg DeleteKVParams) error {
	_, err := q.db.ExecContext(ctx, DeleteKV, arg.AgentID, arg.Key)
	return err
}

const GetKV = `-- name: GetKV :one
SELECT agent_id,
    key,
    value,
    updated_at
FROM agent_kv
WHERE agent_id = ?1
    AND key = ?2
LIMIT 1
`

type GetKVParams struct {
	AgentID string `db:"agent_id" json:"agent_id"`
	Key     string `db:"key" json:"key"`
}

// Agent KV Store queries
//
//	SELECT agent_id,
//	    key,
//	    value,
//	    updated_at
//	FROM agent_kv
//	WHERE agent_id = ?1
//	    AND key = ?2
//	LIMIT 1
func (q *Queries) GetKV(ctx context.Context, arg GetKVParams) (AgentKv, error) {
	row := q.db.QueryRowContext(ctx, GetKV, arg.AgentID, arg.Key)
	var i AgentKv
	err := row.Scan(
		&i.AgentID,
		&i.Key,
		&i.Value,
		&i.UpdatedAt,
	)
	return i, err
}

const ListKVByPrefix = `-- name: ListKVByPrefix :many
SELECT agent_id,
    key,
    value,
    updated_at
FROM agent_kv
WHERE agent_id = ?1
    AND key LIKE ?2 || '%'
ORDER BY key
LIMIT ?3
`

type ListKVByPrefixParams struct {
	AgentID string  `db:"agent_id" json:"agent_id"`
	Prefix  *string `db:"prefix" json:"prefix"`
	Lim     int64   `db:"lim" json:"lim"`
}

// ListKVByPrefix
//
//	SELECT agent_id,
//	    key,
//	    value,
//	    updated_at
//	FROM agent_kv
//	WHERE agent_id = ?1
//	    AND key LIKE ?2 || '%'
//	ORDER BY key
//	LIMIT ?3
func (q *Queries) ListKVByPrefix(ctx context.Context, arg ListKVByPrefixParams) ([]AgentKv, error) {
	rows, err := q.db.QueryContext(ctx, ListKVByPrefix, arg.AgentID, arg.Prefix, arg.Lim)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []AgentKv{}
	for rows.Next() {
		var i AgentKv
		if err := rows.Scan(
			&i.AgentID,
			&i.Key,
			&i.Value,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const UpsertKV = `-- name: UpsertKV :exec
INSERT INTO agent_kv (agent_id, key, value, updated_at)
VALUES (
        ?1,
        ?2,
        ?3,
        datetime('now')
    ) ON CONFLICT (agent_id, key) DO
UPDATE
SET value = excluded.value,
    updated_at = excluded.updated_at
`

type UpsertKVParams struct {
	AgentID string `db:"agent_id" json:"agent_id"`
	Key     string `db:"key" json:"key"`
	Value   string `db:"value" json:"value"`
}

// UpsertKV
//
//	INSERT INTO agent_kv (agent_id, key, value, updated_at)
//	VALUES (
//	        ?1,
//	        ?2,
//	        ?3,
//	        datetime('now')
//	    ) ON CONFLICT (agent_id, key) DO
//	UPDATE
//	SET value = excluded.value,
//	    updated_at = excluded.updated_at
func (q *Queries) UpsertKV(ctx context.Context, arg UpsertKVParams) error {
	_, err := q.db.ExecContext(ctx, UpsertKV, arg.AgentID, arg.Key, arg.Value)
	return err
}
