// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: agent_mentions.sql

package sqlc

import (
	"context"
	"encoding/json"

	"github.com/sipeed/picoclaw/pkg/ids"
)

const AddAgentMention = `-- name: AddAgentMention :one
INSERT INTO agent_mentions (
    id, conversation_id, message_id, kind, target_id, raw, metadata_json
)
VALUES (?, ?, ?, ?, ?, ?, ?)
RETURNING id, conversation_id, message_id, kind, target_id, raw, metadata_json, created_at, updated_at
`

type AddAgentMentionParams struct {
	ID             ids.UUID        `db:"id" json:"id"`
	ConversationID ids.UUID        `db:"conversation_id" json:"conversation_id"`
	MessageID      ids.UUID        `db:"message_id" json:"message_id"`
	Kind           string          `db:"kind" json:"kind"`
	TargetID       ids.UUID        `db:"target_id" json:"target_id"`
	Raw            string          `db:"raw" json:"raw"`
	MetadataJson   json.RawMessage `db:"metadata_json" json:"metadata_json"`
}

// AddAgentMention
//
//	INSERT INTO agent_mentions (
//	    id, conversation_id, message_id, kind, target_id, raw, metadata_json
//	)
//	VALUES (?, ?, ?, ?, ?, ?, ?)
//	RETURNING id, conversation_id, message_id, kind, target_id, raw, metadata_json, created_at, updated_at
func (q *Queries) AddAgentMention(ctx context.Context, arg AddAgentMentionParams) (AgentMention, error) {
	row := q.db.QueryRowContext(ctx, AddAgentMention,
		arg.ID,
		arg.ConversationID,
		arg.MessageID,
		arg.Kind,
		arg.TargetID,
		arg.Raw,
		arg.MetadataJson,
	)
	var i AgentMention
	err := row.Scan(
		&i.ID,
		&i.ConversationID,
		&i.MessageID,
		&i.Kind,
		&i.TargetID,
		&i.Raw,
		&i.MetadataJson,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const ListAgentMentionsByConversationID = `-- name: ListAgentMentionsByConversationID :many
SELECT id, conversation_id, message_id, kind, target_id, raw, metadata_json, created_at, updated_at FROM agent_mentions
WHERE conversation_id = ?
ORDER BY created_at DESC
LIMIT ?2
`

type ListAgentMentionsByConversationIDParams struct {
	ConversationID ids.UUID `db:"conversation_id" json:"conversation_id"`
	Lim            int64    `db:"lim" json:"lim"`
}

// ListAgentMentionsByConversationID
//
//	SELECT id, conversation_id, message_id, kind, target_id, raw, metadata_json, created_at, updated_at FROM agent_mentions
//	WHERE conversation_id = ?
//	ORDER BY created_at DESC
//	LIMIT ?2
func (q *Queries) ListAgentMentionsByConversationID(ctx context.Context, arg ListAgentMentionsByConversationIDParams) ([]AgentMention, error) {
	rows, err := q.db.QueryContext(ctx, ListAgentMentionsByConversationID, arg.ConversationID, arg.Lim)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []AgentMention{}
	for rows.Next() {
		var i AgentMention
		if err := rows.Scan(
			&i.ID,
			&i.ConversationID,
			&i.MessageID,
			&i.Kind,
			&i.TargetID,
			&i.Raw,
			&i.MetadataJson,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
