// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: archival.sql

package sqlc

import (
	"context"
	"strings"

	"github.com/sipeed/picoclaw/pkg/ids"
	"github.com/sipeed/picoclaw/pkg/memory"
)

const CountArchivalChunks = `-- name: CountArchivalChunks :one
SELECT COUNT(*)
FROM archival_chunks
`

// CountArchivalChunks
//
//	SELECT COUNT(*)
//	FROM archival_chunks
func (q *Queries) CountArchivalChunks(ctx context.Context) (int64, error) {
	row := q.db.QueryRowContext(ctx, CountArchivalChunks)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const DeleteArchivalChunksByRecall = `-- name: DeleteArchivalChunksByRecall :exec
DELETE FROM archival_chunks
WHERE recall_id = ?1
`

type DeleteArchivalChunksByRecallParams struct {
	RecallID ids.UUID `json:"recall_id"`
}

// DeleteArchivalChunksByRecall
//
//	DELETE FROM archival_chunks
//	WHERE recall_id = ?1
func (q *Queries) DeleteArchivalChunksByRecall(ctx context.Context, arg DeleteArchivalChunksByRecallParams) error {
	_, err := q.db.ExecContext(ctx, DeleteArchivalChunksByRecall, arg.RecallID)
	return err
}

const GetArchivalChunk = `-- name: GetArchivalChunk :one
SELECT id,
    recall_id,
    chunk_index,
    content,
    embedding,
    source,
    hash,
    created_at
FROM archival_chunks
WHERE id = ?1
`

type GetArchivalChunkParams struct {
	ID ids.UUID `json:"id"`
}

// GetArchivalChunk
//
//	SELECT id,
//	    recall_id,
//	    chunk_index,
//	    content,
//	    embedding,
//	    source,
//	    hash,
//	    created_at
//	FROM archival_chunks
//	WHERE id = ?1
func (q *Queries) GetArchivalChunk(ctx context.Context, arg GetArchivalChunkParams) (ArchivalChunk, error) {
	row := q.db.QueryRowContext(ctx, GetArchivalChunk, arg.ID)
	var i ArchivalChunk
	err := row.Scan(
		&i.ID,
		&i.RecallID,
		&i.ChunkIndex,
		&i.Content,
		&i.Embedding,
		&i.Source,
		&i.Hash,
		&i.CreatedAt,
	)
	return i, err
}

const GetArchivalChunksByIDs = `-- name: GetArchivalChunksByIDs :many
SELECT id,
    recall_id,
    chunk_index,
    content,
    embedding,
    source,
    hash,
    created_at
FROM archival_chunks
WHERE id IN (/*SLICE:ids*/?)
`

type GetArchivalChunksByIDsParams struct {
	Ids []ids.UUID `json:"ids"`
}

// GetArchivalChunksByIDs
//
//	SELECT id,
//	    recall_id,
//	    chunk_index,
//	    content,
//	    embedding,
//	    source,
//	    hash,
//	    created_at
//	FROM archival_chunks
//	WHERE id IN (/*SLICE:ids*/?)
func (q *Queries) GetArchivalChunksByIDs(ctx context.Context, arg GetArchivalChunksByIDsParams) ([]ArchivalChunk, error) {
	query := GetArchivalChunksByIDs
	var queryParams []interface{}
	if len(arg.Ids) > 0 {
		for _, v := range arg.Ids {
			queryParams = append(queryParams, v)
		}
		query = strings.Replace(query, "/*SLICE:ids*/?", strings.Repeat(",?", len(arg.Ids))[1:], 1)
	} else {
		query = strings.Replace(query, "/*SLICE:ids*/?", "NULL", 1)
	}
	rows, err := q.db.QueryContext(ctx, query, queryParams...)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ArchivalChunk{}
	for rows.Next() {
		var i ArchivalChunk
		if err := rows.Scan(
			&i.ID,
			&i.RecallID,
			&i.ChunkIndex,
			&i.Content,
			&i.Embedding,
			&i.Source,
			&i.Hash,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const InsertArchivalChunk = `-- name: InsertArchivalChunk :exec
INSERT INTO archival_chunks (
        id,
        recall_id,
        chunk_index,
        content,
        embedding,
        source,
        hash,
        created_at
    )
VALUES (
        ?1,
        ?2,
        ?3,
        ?4,
        ?5,
        ?6,
        ?7,
        datetime('now')
    )
`

type InsertArchivalChunkParams struct {
	ID         ids.UUID         `json:"id"`
	RecallID   ids.UUID         `json:"recall_id"`
	ChunkIndex int64            `json:"chunk_index"`
	Content    string           `json:"content"`
	Embedding  memory.Embedding `json:"embedding"`
	Source     string           `json:"source"`
	Hash       string           `json:"hash"`
}

// Archival Chunk queries
//
//	INSERT INTO archival_chunks (
//	        id,
//	        recall_id,
//	        chunk_index,
//	        content,
//	        embedding,
//	        source,
//	        hash,
//	        created_at
//	    )
//	VALUES (
//	        ?1,
//	        ?2,
//	        ?3,
//	        ?4,
//	        ?5,
//	        ?6,
//	        ?7,
//	        datetime('now')
//	    )
func (q *Queries) InsertArchivalChunk(ctx context.Context, arg InsertArchivalChunkParams) error {
	_, err := q.db.ExecContext(ctx, InsertArchivalChunk,
		arg.ID,
		arg.RecallID,
		arg.ChunkIndex,
		arg.Content,
		arg.Embedding,
		arg.Source,
		arg.Hash,
	)
	return err
}

const ListAllArchivalChunks = `-- name: ListAllArchivalChunks :many
SELECT id,
    recall_id,
    chunk_index,
    content,
    embedding,
    source,
    hash,
    created_at
FROM archival_chunks
ORDER BY created_at DESC
LIMIT ?2 OFFSET ?1
`

type ListAllArchivalChunksParams struct {
	Off int64 `json:"off"`
	Lim int64 `json:"lim"`
}

// ListAllArchivalChunks
//
//	SELECT id,
//	    recall_id,
//	    chunk_index,
//	    content,
//	    embedding,
//	    source,
//	    hash,
//	    created_at
//	FROM archival_chunks
//	ORDER BY created_at DESC
//	LIMIT ?2 OFFSET ?1
func (q *Queries) ListAllArchivalChunks(ctx context.Context, arg ListAllArchivalChunksParams) ([]ArchivalChunk, error) {
	rows, err := q.db.QueryContext(ctx, ListAllArchivalChunks, arg.Off, arg.Lim)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ArchivalChunk{}
	for rows.Next() {
		var i ArchivalChunk
		if err := rows.Scan(
			&i.ID,
			&i.RecallID,
			&i.ChunkIndex,
			&i.Content,
			&i.Embedding,
			&i.Source,
			&i.Hash,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const ListArchivalChunks = `-- name: ListArchivalChunks :many
SELECT id,
    recall_id,
    chunk_index,
    content,
    embedding,
    source,
    hash,
    created_at
FROM archival_chunks
WHERE recall_id = ?1
ORDER BY chunk_index
`

type ListArchivalChunksParams struct {
	RecallID ids.UUID `json:"recall_id"`
}

// ListArchivalChunks
//
//	SELECT id,
//	    recall_id,
//	    chunk_index,
//	    content,
//	    embedding,
//	    source,
//	    hash,
//	    created_at
//	FROM archival_chunks
//	WHERE recall_id = ?1
//	ORDER BY chunk_index
func (q *Queries) ListArchivalChunks(ctx context.Context, arg ListArchivalChunksParams) ([]ArchivalChunk, error) {
	rows, err := q.db.QueryContext(ctx, ListArchivalChunks, arg.RecallID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ArchivalChunk{}
	for rows.Next() {
		var i ArchivalChunk
		if err := rows.Scan(
			&i.ID,
			&i.RecallID,
			&i.ChunkIndex,
			&i.Content,
			&i.Embedding,
			&i.Source,
			&i.Hash,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
