// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: archival.sql

package sqlc

import (
	"context"
	"strings"

	"github.com/sipeed/picoclaw/pkg/ids"
	"github.com/sipeed/picoclaw/pkg/memory"
)

const CountArchivalChunks = `-- name: CountArchivalChunks :one
SELECT COUNT(*)
FROM archival_chunks ac
    JOIN recall_items ri ON ac.recall_id = ri.id
WHERE ri.agent_id = ?1
`

type CountArchivalChunksParams struct {
	AgentID string `db:"agent_id" json:"agent_id"`
}

// CountArchivalChunks
//
//	SELECT COUNT(*)
//	FROM archival_chunks ac
//	    JOIN recall_items ri ON ac.recall_id = ri.id
//	WHERE ri.agent_id = ?1
func (q *Queries) CountArchivalChunks(ctx context.Context, arg CountArchivalChunksParams) (int64, error) {
	row := q.db.QueryRowContext(ctx, CountArchivalChunks, arg.AgentID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const DeleteArchivalChunksByRecall = `-- name: DeleteArchivalChunksByRecall :exec
DELETE FROM archival_chunks
WHERE recall_id = ?1
`

type DeleteArchivalChunksByRecallParams struct {
	RecallID ids.UUID `db:"recall_id" json:"recall_id"`
}

// DeleteArchivalChunksByRecall
//
//	DELETE FROM archival_chunks
//	WHERE recall_id = ?1
func (q *Queries) DeleteArchivalChunksByRecall(ctx context.Context, arg DeleteArchivalChunksByRecallParams) error {
	_, err := q.db.ExecContext(ctx, DeleteArchivalChunksByRecall, arg.RecallID)
	return err
}

const GetArchivalChunk = `-- name: GetArchivalChunk :one
SELECT ac.id,
    ac.recall_id,
    ac.chunk_index,
    ac.content,
    ac.embedding,
    ac.source,
    ac.hash,
    ac.created_at
FROM archival_chunks ac
    JOIN recall_items ri ON ac.recall_id = ri.id
WHERE ac.id = ?1
    AND ri.agent_id = ?2
LIMIT 1
`

type GetArchivalChunkParams struct {
	ID      ids.UUID `db:"id" json:"id"`
	AgentID string   `db:"agent_id" json:"agent_id"`
}

// GetArchivalChunk
//
//	SELECT ac.id,
//	    ac.recall_id,
//	    ac.chunk_index,
//	    ac.content,
//	    ac.embedding,
//	    ac.source,
//	    ac.hash,
//	    ac.created_at
//	FROM archival_chunks ac
//	    JOIN recall_items ri ON ac.recall_id = ri.id
//	WHERE ac.id = ?1
//	    AND ri.agent_id = ?2
//	LIMIT 1
func (q *Queries) GetArchivalChunk(ctx context.Context, arg GetArchivalChunkParams) (ArchivalChunk, error) {
	row := q.db.QueryRowContext(ctx, GetArchivalChunk, arg.ID, arg.AgentID)
	var i ArchivalChunk
	err := row.Scan(
		&i.ID,
		&i.RecallID,
		&i.ChunkIndex,
		&i.Content,
		&i.Embedding,
		&i.Source,
		&i.Hash,
		&i.CreatedAt,
	)
	return i, err
}

const GetArchivalChunksByIDs = `-- name: GetArchivalChunksByIDs :many
SELECT ac.id,
    ac.recall_id,
    ac.chunk_index,
    ac.content,
    ac.embedding,
    ac.source,
    ac.hash,
    ac.created_at
FROM archival_chunks ac
    JOIN recall_items ri ON ac.recall_id = ri.id
WHERE ac.id IN (/*SLICE:ids*/?)
    AND ri.agent_id = ?2
`

type GetArchivalChunksByIDsParams struct {
	Ids     []ids.UUID `db:"ids" json:"ids"`
	AgentID string     `db:"agent_id" json:"agent_id"`
}

// GetArchivalChunksByIDs
//
//	SELECT ac.id,
//	    ac.recall_id,
//	    ac.chunk_index,
//	    ac.content,
//	    ac.embedding,
//	    ac.source,
//	    ac.hash,
//	    ac.created_at
//	FROM archival_chunks ac
//	    JOIN recall_items ri ON ac.recall_id = ri.id
//	WHERE ac.id IN (/*SLICE:ids*/?)
//	    AND ri.agent_id = ?2
func (q *Queries) GetArchivalChunksByIDs(ctx context.Context, arg GetArchivalChunksByIDsParams) ([]ArchivalChunk, error) {
	query := GetArchivalChunksByIDs
	var queryParams []interface{}
	if len(arg.Ids) > 0 {
		for _, v := range arg.Ids {
			queryParams = append(queryParams, v)
		}
		query = strings.Replace(query, "/*SLICE:ids*/?", strings.Repeat(",?", len(arg.Ids))[1:], 1)
	} else {
		query = strings.Replace(query, "/*SLICE:ids*/?", "NULL", 1)
	}
	queryParams = append(queryParams, arg.AgentID)
	rows, err := q.db.QueryContext(ctx, query, queryParams...)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ArchivalChunk{}
	for rows.Next() {
		var i ArchivalChunk
		if err := rows.Scan(
			&i.ID,
			&i.RecallID,
			&i.ChunkIndex,
			&i.Content,
			&i.Embedding,
			&i.Source,
			&i.Hash,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const InsertArchivalChunk = `-- name: InsertArchivalChunk :exec
INSERT INTO archival_chunks (
        id,
        recall_id,
        chunk_index,
        content,
        embedding,
        source,
        hash,
        created_at
    )
VALUES (
        ?1,
        ?2,
        ?3,
        ?4,
        ?5,
        ?6,
        ?7,
        datetime('now')
    )
`

type InsertArchivalChunkParams struct {
	ID         ids.UUID         `db:"id" json:"id"`
	RecallID   ids.UUID         `db:"recall_id" json:"recall_id"`
	ChunkIndex int64            `db:"chunk_index" json:"chunk_index"`
	Content    string           `db:"content" json:"content"`
	Embedding  memory.Embedding `db:"embedding" json:"embedding"`
	Source     string           `db:"source" json:"source"`
	Hash       string           `db:"hash" json:"hash"`
}

// Archival Chunk queries
//
//	INSERT INTO archival_chunks (
//	        id,
//	        recall_id,
//	        chunk_index,
//	        content,
//	        embedding,
//	        source,
//	        hash,
//	        created_at
//	    )
//	VALUES (
//	        ?1,
//	        ?2,
//	        ?3,
//	        ?4,
//	        ?5,
//	        ?6,
//	        ?7,
//	        datetime('now')
//	    )
func (q *Queries) InsertArchivalChunk(ctx context.Context, arg InsertArchivalChunkParams) error {
	_, err := q.db.ExecContext(ctx, InsertArchivalChunk,
		arg.ID,
		arg.RecallID,
		arg.ChunkIndex,
		arg.Content,
		arg.Embedding,
		arg.Source,
		arg.Hash,
	)
	return err
}

const ListAllArchivalChunks = `-- name: ListAllArchivalChunks :many
SELECT ac.id,
    ac.recall_id,
    ac.chunk_index,
    ac.content,
    ac.embedding,
    ac.source,
    ac.hash,
    ac.created_at
FROM archival_chunks ac
    JOIN recall_items ri ON ac.recall_id = ri.id
WHERE ri.agent_id = ?1
ORDER BY ac.created_at DESC
LIMIT ?3 OFFSET ?2
`

type ListAllArchivalChunksParams struct {
	AgentID string `db:"agent_id" json:"agent_id"`
	Off     int64  `db:"off" json:"off"`
	Lim     int64  `db:"lim" json:"lim"`
}

// ListAllArchivalChunks
//
//	SELECT ac.id,
//	    ac.recall_id,
//	    ac.chunk_index,
//	    ac.content,
//	    ac.embedding,
//	    ac.source,
//	    ac.hash,
//	    ac.created_at
//	FROM archival_chunks ac
//	    JOIN recall_items ri ON ac.recall_id = ri.id
//	WHERE ri.agent_id = ?1
//	ORDER BY ac.created_at DESC
//	LIMIT ?3 OFFSET ?2
func (q *Queries) ListAllArchivalChunks(ctx context.Context, arg ListAllArchivalChunksParams) ([]ArchivalChunk, error) {
	rows, err := q.db.QueryContext(ctx, ListAllArchivalChunks, arg.AgentID, arg.Off, arg.Lim)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ArchivalChunk{}
	for rows.Next() {
		var i ArchivalChunk
		if err := rows.Scan(
			&i.ID,
			&i.RecallID,
			&i.ChunkIndex,
			&i.Content,
			&i.Embedding,
			&i.Source,
			&i.Hash,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const ListArchivalChunks = `-- name: ListArchivalChunks :many
SELECT ac.id,
    ac.recall_id,
    ac.chunk_index,
    ac.content,
    ac.embedding,
    ac.source,
    ac.hash,
    ac.created_at
FROM archival_chunks ac
    JOIN recall_items ri ON ac.recall_id = ri.id
WHERE ac.recall_id = ?1
    AND ri.agent_id = ?2
ORDER BY ac.chunk_index
LIMIT ?3
`

type ListArchivalChunksParams struct {
	RecallID ids.UUID `db:"recall_id" json:"recall_id"`
	AgentID  string   `db:"agent_id" json:"agent_id"`
	Lim      int64    `db:"lim" json:"lim"`
}

// ListArchivalChunks
//
//	SELECT ac.id,
//	    ac.recall_id,
//	    ac.chunk_index,
//	    ac.content,
//	    ac.embedding,
//	    ac.source,
//	    ac.hash,
//	    ac.created_at
//	FROM archival_chunks ac
//	    JOIN recall_items ri ON ac.recall_id = ri.id
//	WHERE ac.recall_id = ?1
//	    AND ri.agent_id = ?2
//	ORDER BY ac.chunk_index
//	LIMIT ?3
func (q *Queries) ListArchivalChunks(ctx context.Context, arg ListArchivalChunksParams) ([]ArchivalChunk, error) {
	rows, err := q.db.QueryContext(ctx, ListArchivalChunks, arg.RecallID, arg.AgentID, arg.Lim)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ArchivalChunk{}
	for rows.Next() {
		var i ArchivalChunk
		if err := rows.Scan(
			&i.ID,
			&i.RecallID,
			&i.ChunkIndex,
			&i.Content,
			&i.Embedding,
			&i.Source,
			&i.Hash,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
