// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: consolidation.sql

package sqlc

import (
	"context"
	"time"

	"github.com/ZanzyTHEbar/dragonscale/pkg/ids"
	"github.com/ZanzyTHEbar/dragonscale/pkg/memory"
)

const FindSimilarRecallItems = `-- name: FindSimilarRecallItems :many
SELECT ri.id,
    ri.agent_id,
    ri.content,
    ac.embedding as embedding,
    vector_distance_cosine(ac.embedding, ?1) as distance
FROM recall_items ri
    JOIN archival_chunks ac ON ac.recall_id = ri.id
    AND ac.chunk_index = 0
WHERE ri.agent_id = ?2
    AND ri.id != ?3
    AND ac.embedding IS NOT NULL
ORDER BY distance ASC
LIMIT ?4
`

type FindSimilarRecallItemsParams struct {
	QueryEmbedding interface{} `db:"query_embedding" json:"query_embedding"`
	AgentID        string      `db:"agent_id" json:"agent_id"`
	ExcludeID      ids.UUID    `db:"exclude_id" json:"exclude_id"`
	Lim            int64       `db:"lim" json:"lim"`
}

type FindSimilarRecallItemsRow struct {
	ID        ids.UUID         `db:"id" json:"id"`
	AgentID   string           `db:"agent_id" json:"agent_id"`
	Content   string           `db:"content" json:"content"`
	Embedding memory.Embedding `db:"embedding" json:"embedding"`
	Distance  interface{}      `db:"distance" json:"distance"`
}

// Finds recall items with high cosine similarity to the given embedding.
// Uses libSQL's built-in vector similarity if available, otherwise returns
// candidates for manual comparison.
//
//	SELECT ri.id,
//	    ri.agent_id,
//	    ri.content,
//	    ac.embedding as embedding,
//	    vector_distance_cosine(ac.embedding, ?1) as distance
//	FROM recall_items ri
//	    JOIN archival_chunks ac ON ac.recall_id = ri.id
//	    AND ac.chunk_index = 0
//	WHERE ri.agent_id = ?2
//	    AND ri.id != ?3
//	    AND ac.embedding IS NOT NULL
//	ORDER BY distance ASC
//	LIMIT ?4
func (q *Queries) FindSimilarRecallItems(ctx context.Context, arg FindSimilarRecallItemsParams) ([]FindSimilarRecallItemsRow, error) {
	rows, err := q.db.QueryContext(ctx, FindSimilarRecallItems,
		arg.QueryEmbedding,
		arg.AgentID,
		arg.ExcludeID,
		arg.Lim,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []FindSimilarRecallItemsRow{}
	for rows.Next() {
		var i FindSimilarRecallItemsRow
		if err := rows.Scan(
			&i.ID,
			&i.AgentID,
			&i.Content,
			&i.Embedding,
			&i.Distance,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const ListRecallItemsForConsolidation = `-- name: ListRecallItemsForConsolidation :many
SELECT ri.id,
    ri.agent_id,
    ri.session_key,
    ri.role,
    ri.sector,
    ri.importance,
    ri.salience,
    ri.decay_rate,
    ri.content,
    ri.tags,
    ri.created_at,
    ri.updated_at,
    ac.embedding as embedding
FROM recall_items ri
    LEFT JOIN archival_chunks ac ON ac.recall_id = ri.id
    AND ac.chunk_index = 0
WHERE ri.created_at > ?1
    AND ri.suppressed_at IS NULL
    AND (
        ?2 = ''
        OR ri.agent_id = ?2
    )
ORDER BY ri.created_at DESC
LIMIT ?3
`

type ListRecallItemsForConsolidationParams struct {
	Cutoff  time.Time   `db:"cutoff" json:"cutoff"`
	AgentID interface{} `db:"agent_id" json:"agent_id"`
	Lim     int64       `db:"lim" json:"lim"`
}

type ListRecallItemsForConsolidationRow struct {
	ID         ids.UUID         `db:"id" json:"id"`
	AgentID    string           `db:"agent_id" json:"agent_id"`
	SessionKey string           `db:"session_key" json:"session_key"`
	Role       string           `db:"role" json:"role"`
	Sector     memory.Sector    `db:"sector" json:"sector"`
	Importance float64          `db:"importance" json:"importance"`
	Salience   float64          `db:"salience" json:"salience"`
	DecayRate  float64          `db:"decay_rate" json:"decay_rate"`
	Content    string           `db:"content" json:"content"`
	Tags       string           `db:"tags" json:"tags"`
	CreatedAt  time.Time        `db:"created_at" json:"created_at"`
	UpdatedAt  time.Time        `db:"updated_at" json:"updated_at"`
	Embedding  memory.Embedding `db:"embedding" json:"embedding"`
}

// Consolidation queries for memory graph maintenance (ADR-004)
// Returns recall items created after the cutoff time, joined with their first
// archival chunk's embedding for similarity comparison.
//
//	SELECT ri.id,
//	    ri.agent_id,
//	    ri.session_key,
//	    ri.role,
//	    ri.sector,
//	    ri.importance,
//	    ri.salience,
//	    ri.decay_rate,
//	    ri.content,
//	    ri.tags,
//	    ri.created_at,
//	    ri.updated_at,
//	    ac.embedding as embedding
//	FROM recall_items ri
//	    LEFT JOIN archival_chunks ac ON ac.recall_id = ri.id
//	    AND ac.chunk_index = 0
//	WHERE ri.created_at > ?1
//	    AND ri.suppressed_at IS NULL
//	    AND (
//	        ?2 = ''
//	        OR ri.agent_id = ?2
//	    )
//	ORDER BY ri.created_at DESC
//	LIMIT ?3
func (q *Queries) ListRecallItemsForConsolidation(ctx context.Context, arg ListRecallItemsForConsolidationParams) ([]ListRecallItemsForConsolidationRow, error) {
	rows, err := q.db.QueryContext(ctx, ListRecallItemsForConsolidation, arg.Cutoff, arg.AgentID, arg.Lim)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListRecallItemsForConsolidationRow{}
	for rows.Next() {
		var i ListRecallItemsForConsolidationRow
		if err := rows.Scan(
			&i.ID,
			&i.AgentID,
			&i.SessionKey,
			&i.Role,
			&i.Sector,
			&i.Importance,
			&i.Salience,
			&i.DecayRate,
			&i.Content,
			&i.Tags,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.Embedding,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
