// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: dag.sql

package sqlc

import (
	"context"
	"encoding/json"

	"github.com/ZanzyTHEbar/dragonscale/pkg/ids"
)

const GetDAGNodeBySnapshotAndNodeID = `-- name: GetDAGNodeBySnapshotAndNodeID :one
SELECT id,
    snapshot_id,
    node_id,
    level,
    summary,
    tokens,
    start_idx,
    end_idx,
    span,
    content_hash,
    metrics_json,
    metadata_json,
    created_at,
    updated_at
FROM dag_nodes
WHERE snapshot_id = ?1
    AND node_id = ?2
LIMIT 1
`

type GetDAGNodeBySnapshotAndNodeIDParams struct {
	SnapshotID ids.UUID `db:"snapshot_id" json:"snapshot_id"`
	NodeID     string   `db:"node_id" json:"node_id"`
}

// GetDAGNodeBySnapshotAndNodeID
//
//	SELECT id,
//	    snapshot_id,
//	    node_id,
//	    level,
//	    summary,
//	    tokens,
//	    start_idx,
//	    end_idx,
//	    span,
//	    content_hash,
//	    metrics_json,
//	    metadata_json,
//	    created_at,
//	    updated_at
//	FROM dag_nodes
//	WHERE snapshot_id = ?1
//	    AND node_id = ?2
//	LIMIT 1
func (q *Queries) GetDAGNodeBySnapshotAndNodeID(ctx context.Context, arg GetDAGNodeBySnapshotAndNodeIDParams) (DagNode, error) {
	row := q.db.QueryRowContext(ctx, GetDAGNodeBySnapshotAndNodeID, arg.SnapshotID, arg.NodeID)
	var i DagNode
	err := row.Scan(
		&i.ID,
		&i.SnapshotID,
		&i.NodeID,
		&i.Level,
		&i.Summary,
		&i.Tokens,
		&i.StartIdx,
		&i.EndIdx,
		&i.Span,
		&i.ContentHash,
		&i.MetricsJson,
		&i.MetadataJson,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const GetDAGSnapshotByID = `-- name: GetDAGSnapshotByID :one
SELECT id,
    agent_id,
    session_key,
    from_msg_idx,
    to_msg_idx,
    msg_count,
    roots_json,
    content_hash,
    created_at,
    updated_at
FROM dag_snapshots
WHERE id = ?1
LIMIT 1
`

type GetDAGSnapshotByIDParams struct {
	ID ids.UUID `db:"id" json:"id"`
}

// GetDAGSnapshotByID
//
//	SELECT id,
//	    agent_id,
//	    session_key,
//	    from_msg_idx,
//	    to_msg_idx,
//	    msg_count,
//	    roots_json,
//	    content_hash,
//	    created_at,
//	    updated_at
//	FROM dag_snapshots
//	WHERE id = ?1
//	LIMIT 1
func (q *Queries) GetDAGSnapshotByID(ctx context.Context, arg GetDAGSnapshotByIDParams) (DagSnapshot, error) {
	row := q.db.QueryRowContext(ctx, GetDAGSnapshotByID, arg.ID)
	var i DagSnapshot
	err := row.Scan(
		&i.ID,
		&i.AgentID,
		&i.SessionKey,
		&i.FromMsgIdx,
		&i.ToMsgIdx,
		&i.MsgCount,
		&i.RootsJson,
		&i.ContentHash,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const GetLatestDAGSnapshotBySession = `-- name: GetLatestDAGSnapshotBySession :one
SELECT id,
    agent_id,
    session_key,
    from_msg_idx,
    to_msg_idx,
    msg_count,
    roots_json,
    content_hash,
    created_at,
    updated_at
FROM dag_snapshots
WHERE agent_id = ?1
    AND session_key = ?2
ORDER BY created_at DESC
LIMIT 1
`

type GetLatestDAGSnapshotBySessionParams struct {
	AgentID    string `db:"agent_id" json:"agent_id"`
	SessionKey string `db:"session_key" json:"session_key"`
}

// GetLatestDAGSnapshotBySession
//
//	SELECT id,
//	    agent_id,
//	    session_key,
//	    from_msg_idx,
//	    to_msg_idx,
//	    msg_count,
//	    roots_json,
//	    content_hash,
//	    created_at,
//	    updated_at
//	FROM dag_snapshots
//	WHERE agent_id = ?1
//	    AND session_key = ?2
//	ORDER BY created_at DESC
//	LIMIT 1
func (q *Queries) GetLatestDAGSnapshotBySession(ctx context.Context, arg GetLatestDAGSnapshotBySessionParams) (DagSnapshot, error) {
	row := q.db.QueryRowContext(ctx, GetLatestDAGSnapshotBySession, arg.AgentID, arg.SessionKey)
	var i DagSnapshot
	err := row.Scan(
		&i.ID,
		&i.AgentID,
		&i.SessionKey,
		&i.FromMsgIdx,
		&i.ToMsgIdx,
		&i.MsgCount,
		&i.RootsJson,
		&i.ContentHash,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const InsertDAGEdge = `-- name: InsertDAGEdge :exec
INSERT INTO dag_edges (
        id,
        snapshot_id,
        parent_node_id,
        child_node_id,
        edge_index,
        metadata_json
    )
VALUES (
        ?1,
        ?2,
        ?3,
        ?4,
        ?5,
        ?6
    )
`

type InsertDAGEdgeParams struct {
	ID           ids.UUID        `db:"id" json:"id"`
	SnapshotID   ids.UUID        `db:"snapshot_id" json:"snapshot_id"`
	ParentNodeID ids.UUID        `db:"parent_node_id" json:"parent_node_id"`
	ChildNodeID  ids.UUID        `db:"child_node_id" json:"child_node_id"`
	EdgeIndex    int64           `db:"edge_index" json:"edge_index"`
	MetadataJson json.RawMessage `db:"metadata_json" json:"metadata_json"`
}

// InsertDAGEdge
//
//	INSERT INTO dag_edges (
//	        id,
//	        snapshot_id,
//	        parent_node_id,
//	        child_node_id,
//	        edge_index,
//	        metadata_json
//	    )
//	VALUES (
//	        ?1,
//	        ?2,
//	        ?3,
//	        ?4,
//	        ?5,
//	        ?6
//	    )
func (q *Queries) InsertDAGEdge(ctx context.Context, arg InsertDAGEdgeParams) error {
	_, err := q.db.ExecContext(ctx, InsertDAGEdge,
		arg.ID,
		arg.SnapshotID,
		arg.ParentNodeID,
		arg.ChildNodeID,
		arg.EdgeIndex,
		arg.MetadataJson,
	)
	return err
}

const InsertDAGNode = `-- name: InsertDAGNode :one
INSERT INTO dag_nodes (
        id,
        snapshot_id,
        node_id,
        level,
        summary,
        tokens,
        start_idx,
        end_idx,
        span,
        content_hash,
        metrics_json,
        metadata_json
    )
VALUES (
        ?1,
        ?2,
        ?3,
        ?4,
        ?5,
        ?6,
        ?7,
        ?8,
        ?9,
        ?10,
        ?11,
        ?12
    )
RETURNING id,
    snapshot_id,
    node_id,
    level,
    summary,
    tokens,
    start_idx,
    end_idx,
    span,
    content_hash,
    metrics_json,
    metadata_json,
    created_at,
    updated_at
`

type InsertDAGNodeParams struct {
	ID           ids.UUID        `db:"id" json:"id"`
	SnapshotID   ids.UUID        `db:"snapshot_id" json:"snapshot_id"`
	NodeID       string          `db:"node_id" json:"node_id"`
	Level        int64           `db:"level" json:"level"`
	Summary      string          `db:"summary" json:"summary"`
	Tokens       int64           `db:"tokens" json:"tokens"`
	StartIdx     int64           `db:"start_idx" json:"start_idx"`
	EndIdx       int64           `db:"end_idx" json:"end_idx"`
	Span         int64           `db:"span" json:"span"`
	ContentHash  string          `db:"content_hash" json:"content_hash"`
	MetricsJson  json.RawMessage `db:"metrics_json" json:"metrics_json"`
	MetadataJson json.RawMessage `db:"metadata_json" json:"metadata_json"`
}

// InsertDAGNode
//
//	INSERT INTO dag_nodes (
//	        id,
//	        snapshot_id,
//	        node_id,
//	        level,
//	        summary,
//	        tokens,
//	        start_idx,
//	        end_idx,
//	        span,
//	        content_hash,
//	        metrics_json,
//	        metadata_json
//	    )
//	VALUES (
//	        ?1,
//	        ?2,
//	        ?3,
//	        ?4,
//	        ?5,
//	        ?6,
//	        ?7,
//	        ?8,
//	        ?9,
//	        ?10,
//	        ?11,
//	        ?12
//	    )
//	RETURNING id,
//	    snapshot_id,
//	    node_id,
//	    level,
//	    summary,
//	    tokens,
//	    start_idx,
//	    end_idx,
//	    span,
//	    content_hash,
//	    metrics_json,
//	    metadata_json,
//	    created_at,
//	    updated_at
func (q *Queries) InsertDAGNode(ctx context.Context, arg InsertDAGNodeParams) (DagNode, error) {
	row := q.db.QueryRowContext(ctx, InsertDAGNode,
		arg.ID,
		arg.SnapshotID,
		arg.NodeID,
		arg.Level,
		arg.Summary,
		arg.Tokens,
		arg.StartIdx,
		arg.EndIdx,
		arg.Span,
		arg.ContentHash,
		arg.MetricsJson,
		arg.MetadataJson,
	)
	var i DagNode
	err := row.Scan(
		&i.ID,
		&i.SnapshotID,
		&i.NodeID,
		&i.Level,
		&i.Summary,
		&i.Tokens,
		&i.StartIdx,
		&i.EndIdx,
		&i.Span,
		&i.ContentHash,
		&i.MetricsJson,
		&i.MetadataJson,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const InsertDAGSnapshot = `-- name: InsertDAGSnapshot :one
INSERT INTO dag_snapshots (
        id,
        agent_id,
        session_key,
        from_msg_idx,
        to_msg_idx,
        msg_count,
        roots_json,
        content_hash
    )
VALUES (
        ?1,
        ?2,
        ?3,
        ?4,
        ?5,
        ?6,
        ?7,
        ?8
    )
RETURNING id,
    agent_id,
    session_key,
    from_msg_idx,
    to_msg_idx,
    msg_count,
    roots_json,
    content_hash,
    created_at,
    updated_at
`

type InsertDAGSnapshotParams struct {
	ID          ids.UUID `db:"id" json:"id"`
	AgentID     string   `db:"agent_id" json:"agent_id"`
	SessionKey  string   `db:"session_key" json:"session_key"`
	FromMsgIdx  int64    `db:"from_msg_idx" json:"from_msg_idx"`
	ToMsgIdx    int64    `db:"to_msg_idx" json:"to_msg_idx"`
	MsgCount    int64    `db:"msg_count" json:"msg_count"`
	RootsJson   string   `db:"roots_json" json:"roots_json"`
	ContentHash string   `db:"content_hash" json:"content_hash"`
}

// DAG persistence queries
//
//	INSERT INTO dag_snapshots (
//	        id,
//	        agent_id,
//	        session_key,
//	        from_msg_idx,
//	        to_msg_idx,
//	        msg_count,
//	        roots_json,
//	        content_hash
//	    )
//	VALUES (
//	        ?1,
//	        ?2,
//	        ?3,
//	        ?4,
//	        ?5,
//	        ?6,
//	        ?7,
//	        ?8
//	    )
//	RETURNING id,
//	    agent_id,
//	    session_key,
//	    from_msg_idx,
//	    to_msg_idx,
//	    msg_count,
//	    roots_json,
//	    content_hash,
//	    created_at,
//	    updated_at
func (q *Queries) InsertDAGSnapshot(ctx context.Context, arg InsertDAGSnapshotParams) (DagSnapshot, error) {
	row := q.db.QueryRowContext(ctx, InsertDAGSnapshot,
		arg.ID,
		arg.AgentID,
		arg.SessionKey,
		arg.FromMsgIdx,
		arg.ToMsgIdx,
		arg.MsgCount,
		arg.RootsJson,
		arg.ContentHash,
	)
	var i DagSnapshot
	err := row.Scan(
		&i.ID,
		&i.AgentID,
		&i.SessionKey,
		&i.FromMsgIdx,
		&i.ToMsgIdx,
		&i.MsgCount,
		&i.RootsJson,
		&i.ContentHash,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const ListDAGEdgesBySnapshotID = `-- name: ListDAGEdgesBySnapshotID :many
SELECT id,
    snapshot_id,
    parent_node_id,
    child_node_id,
    edge_index,
    metadata_json,
    created_at,
    updated_at
FROM dag_edges
WHERE snapshot_id = ?1
ORDER BY edge_index ASC,
    created_at ASC
`

type ListDAGEdgesBySnapshotIDParams struct {
	SnapshotID ids.UUID `db:"snapshot_id" json:"snapshot_id"`
}

// ListDAGEdgesBySnapshotID
//
//	SELECT id,
//	    snapshot_id,
//	    parent_node_id,
//	    child_node_id,
//	    edge_index,
//	    metadata_json,
//	    created_at,
//	    updated_at
//	FROM dag_edges
//	WHERE snapshot_id = ?1
//	ORDER BY edge_index ASC,
//	    created_at ASC
func (q *Queries) ListDAGEdgesBySnapshotID(ctx context.Context, arg ListDAGEdgesBySnapshotIDParams) ([]DagEdge, error) {
	rows, err := q.db.QueryContext(ctx, ListDAGEdgesBySnapshotID, arg.SnapshotID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []DagEdge{}
	for rows.Next() {
		var i DagEdge
		if err := rows.Scan(
			&i.ID,
			&i.SnapshotID,
			&i.ParentNodeID,
			&i.ChildNodeID,
			&i.EdgeIndex,
			&i.MetadataJson,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const ListDAGNodesBySnapshotID = `-- name: ListDAGNodesBySnapshotID :many
SELECT id,
    snapshot_id,
    node_id,
    level,
    summary,
    tokens,
    start_idx,
    end_idx,
    span,
    content_hash,
    metrics_json,
    metadata_json,
    created_at,
    updated_at
FROM dag_nodes
WHERE snapshot_id = ?1
ORDER BY start_idx ASC
`

type ListDAGNodesBySnapshotIDParams struct {
	SnapshotID ids.UUID `db:"snapshot_id" json:"snapshot_id"`
}

// ListDAGNodesBySnapshotID
//
//	SELECT id,
//	    snapshot_id,
//	    node_id,
//	    level,
//	    summary,
//	    tokens,
//	    start_idx,
//	    end_idx,
//	    span,
//	    content_hash,
//	    metrics_json,
//	    metadata_json,
//	    created_at,
//	    updated_at
//	FROM dag_nodes
//	WHERE snapshot_id = ?1
//	ORDER BY start_idx ASC
func (q *Queries) ListDAGNodesBySnapshotID(ctx context.Context, arg ListDAGNodesBySnapshotIDParams) ([]DagNode, error) {
	rows, err := q.db.QueryContext(ctx, ListDAGNodesBySnapshotID, arg.SnapshotID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []DagNode{}
	for rows.Next() {
		var i DagNode
		if err := rows.Scan(
			&i.ID,
			&i.SnapshotID,
			&i.NodeID,
			&i.Level,
			&i.Summary,
			&i.Tokens,
			&i.StartIdx,
			&i.EndIdx,
			&i.Span,
			&i.ContentHash,
			&i.MetricsJson,
			&i.MetadataJson,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
