// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: immutable_messages.sql

package sqlc

import (
	"context"

	"github.com/ZanzyTHEbar/dragonscale/pkg/ids"
)

const CountImmutableMessages = `-- name: CountImmutableMessages :one
SELECT COUNT(*)
FROM immutable_messages
WHERE session_key = ?1
`

type CountImmutableMessagesParams struct {
	SessionKey string `db:"session_key" json:"session_key"`
}

// CountImmutableMessages
//
//	SELECT COUNT(*)
//	FROM immutable_messages
//	WHERE session_key = ?1
func (q *Queries) CountImmutableMessages(ctx context.Context, arg CountImmutableMessagesParams) (int64, error) {
	row := q.db.QueryRowContext(ctx, CountImmutableMessages, arg.SessionKey)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const GetImmutableMessage = `-- name: GetImmutableMessage :one
SELECT id,
    session_key,
    role,
    content,
    tool_call_id,
    tool_calls,
    token_estimate,
    created_at
FROM immutable_messages
WHERE id = ?1
LIMIT 1
`

type GetImmutableMessageParams struct {
	ID ids.UUID `db:"id" json:"id"`
}

// GetImmutableMessage
//
//	SELECT id,
//	    session_key,
//	    role,
//	    content,
//	    tool_call_id,
//	    tool_calls,
//	    token_estimate,
//	    created_at
//	FROM immutable_messages
//	WHERE id = ?1
//	LIMIT 1
func (q *Queries) GetImmutableMessage(ctx context.Context, arg GetImmutableMessageParams) (ImmutableMessage, error) {
	row := q.db.QueryRowContext(ctx, GetImmutableMessage, arg.ID)
	var i ImmutableMessage
	err := row.Scan(
		&i.ID,
		&i.SessionKey,
		&i.Role,
		&i.Content,
		&i.ToolCallID,
		&i.ToolCalls,
		&i.TokenEstimate,
		&i.CreatedAt,
	)
	return i, err
}

const InsertImmutableMessage = `-- name: InsertImmutableMessage :one
INSERT INTO immutable_messages (
        id,
        session_key,
        role,
        content,
        tool_call_id,
        tool_calls,
        token_estimate
    )
VALUES (
        ?1,
        ?2,
        ?3,
        ?4,
        ?5,
        ?6,
        ?7
    )
RETURNING id,
    session_key,
    role,
    content,
    tool_call_id,
    tool_calls,
    token_estimate,
    created_at
`

type InsertImmutableMessageParams struct {
	ID            ids.UUID `db:"id" json:"id"`
	SessionKey    string   `db:"session_key" json:"session_key"`
	Role          string   `db:"role" json:"role"`
	Content       string   `db:"content" json:"content"`
	ToolCallID    string   `db:"tool_call_id" json:"tool_call_id"`
	ToolCalls     string   `db:"tool_calls" json:"tool_calls"`
	TokenEstimate int64    `db:"token_estimate" json:"token_estimate"`
}

// Immutable Messages queries (LCM ADR-001: append-only verbatim message store)
//
//	INSERT INTO immutable_messages (
//	        id,
//	        session_key,
//	        role,
//	        content,
//	        tool_call_id,
//	        tool_calls,
//	        token_estimate
//	    )
//	VALUES (
//	        ?1,
//	        ?2,
//	        ?3,
//	        ?4,
//	        ?5,
//	        ?6,
//	        ?7
//	    )
//	RETURNING id,
//	    session_key,
//	    role,
//	    content,
//	    tool_call_id,
//	    tool_calls,
//	    token_estimate,
//	    created_at
func (q *Queries) InsertImmutableMessage(ctx context.Context, arg InsertImmutableMessageParams) (ImmutableMessage, error) {
	row := q.db.QueryRowContext(ctx, InsertImmutableMessage,
		arg.ID,
		arg.SessionKey,
		arg.Role,
		arg.Content,
		arg.ToolCallID,
		arg.ToolCalls,
		arg.TokenEstimate,
	)
	var i ImmutableMessage
	err := row.Scan(
		&i.ID,
		&i.SessionKey,
		&i.Role,
		&i.Content,
		&i.ToolCallID,
		&i.ToolCalls,
		&i.TokenEstimate,
		&i.CreatedAt,
	)
	return i, err
}

const ListImmutableMessages = `-- name: ListImmutableMessages :many
SELECT id,
    session_key,
    role,
    content,
    tool_call_id,
    tool_calls,
    token_estimate,
    created_at
FROM immutable_messages
WHERE session_key = ?1
ORDER BY created_at ASC
LIMIT ?3 OFFSET ?2
`

type ListImmutableMessagesParams struct {
	SessionKey string `db:"session_key" json:"session_key"`
	Off        int64  `db:"off" json:"off"`
	Lim        int64  `db:"lim" json:"lim"`
}

// ListImmutableMessages
//
//	SELECT id,
//	    session_key,
//	    role,
//	    content,
//	    tool_call_id,
//	    tool_calls,
//	    token_estimate,
//	    created_at
//	FROM immutable_messages
//	WHERE session_key = ?1
//	ORDER BY created_at ASC
//	LIMIT ?3 OFFSET ?2
func (q *Queries) ListImmutableMessages(ctx context.Context, arg ListImmutableMessagesParams) ([]ImmutableMessage, error) {
	rows, err := q.db.QueryContext(ctx, ListImmutableMessages, arg.SessionKey, arg.Off, arg.Lim)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ImmutableMessage{}
	for rows.Next() {
		var i ImmutableMessage
		if err := rows.Scan(
			&i.ID,
			&i.SessionKey,
			&i.Role,
			&i.Content,
			&i.ToolCallID,
			&i.ToolCalls,
			&i.TokenEstimate,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
