// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: jobs.sql

package sqlc

import (
	"context"
	"time"

	"github.com/sipeed/picoclaw/pkg/ids"
)

const ClaimJobByID = `-- name: ClaimJobByID :one
UPDATE jobs
SET status = 'running',
    attempts = attempts + 1,
    locked_at = strftime('%Y-%m-%dT%H:%M:%fZ', 'now'),
    locked_by = ?1,
    updated_at = strftime('%Y-%m-%dT%H:%M:%fZ', 'now'),
    last_error = NULL
WHERE id = ?2
    AND status = 'queued'
RETURNING id, kind, status, run_at, attempts, max_attempts, locked_at, locked_by, payload_json, dedupe_key, last_error, created_at, updated_at, completed_at
`

type ClaimJobByIDParams struct {
	LockedBy *string  `db:"locked_by" json:"locked_by"`
	ID       ids.UUID `db:"id" json:"id"`
}

// ClaimJobByID
//
//	UPDATE jobs
//	SET status = 'running',
//	    attempts = attempts + 1,
//	    locked_at = strftime('%Y-%m-%dT%H:%M:%fZ', 'now'),
//	    locked_by = ?1,
//	    updated_at = strftime('%Y-%m-%dT%H:%M:%fZ', 'now'),
//	    last_error = NULL
//	WHERE id = ?2
//	    AND status = 'queued'
//	RETURNING id, kind, status, run_at, attempts, max_attempts, locked_at, locked_by, payload_json, dedupe_key, last_error, created_at, updated_at, completed_at
func (q *Queries) ClaimJobByID(ctx context.Context, arg ClaimJobByIDParams) (Job, error) {
	row := q.db.QueryRowContext(ctx, ClaimJobByID, arg.LockedBy, arg.ID)
	var i Job
	err := row.Scan(
		&i.ID,
		&i.Kind,
		&i.Status,
		&i.RunAt,
		&i.Attempts,
		&i.MaxAttempts,
		&i.LockedAt,
		&i.LockedBy,
		&i.PayloadJson,
		&i.DedupeKey,
		&i.LastError,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.CompletedAt,
	)
	return i, err
}

const CountJobsByStatus = `-- name: CountJobsByStatus :many
SELECT status,
    count(*) AS count
FROM jobs
GROUP BY status
`

type CountJobsByStatusRow struct {
	Status string `db:"status" json:"status"`
	Count  int64  `db:"count" json:"count"`
}

// CountJobsByStatus
//
//	SELECT status,
//	    count(*) AS count
//	FROM jobs
//	GROUP BY status
func (q *Queries) CountJobsByStatus(ctx context.Context) ([]CountJobsByStatusRow, error) {
	rows, err := q.db.QueryContext(ctx, CountJobsByStatus)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []CountJobsByStatusRow{}
	for rows.Next() {
		var i CountJobsByStatusRow
		if err := rows.Scan(&i.Status, &i.Count); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const EnqueueJob = `-- name: EnqueueJob :one
INSERT INTO jobs (
        id,
        kind,
        status,
        run_at,
        max_attempts,
        payload_json,
        dedupe_key
    )
VALUES (
        ?1,
        ?2,
        'queued',
        coalesce(
            ?3,
            strftime('%Y-%m-%dT%H:%M:%fZ', 'now')
        ),
        coalesce(?4, 3),
        coalesce(?5, '{}'),
        ?6
    ) ON CONFLICT(kind, dedupe_key)
WHERE dedupe_key IS NOT NULL DO
UPDATE
SET status = 'queued',
    run_at = excluded.run_at,
    max_attempts = excluded.max_attempts,
    payload_json = excluded.payload_json,
    attempts = 0,
    last_error = NULL,
    updated_at = strftime('%Y-%m-%dT%H:%M:%fZ', 'now')
RETURNING id, kind, status, run_at, attempts, max_attempts, locked_at, locked_by, payload_json, dedupe_key, last_error, created_at, updated_at, completed_at
`

type EnqueueJobParams struct {
	ID          ids.UUID    `db:"id" json:"id"`
	Kind        string      `db:"kind" json:"kind"`
	RunAt       interface{} `db:"run_at" json:"run_at"`
	MaxAttempts interface{} `db:"max_attempts" json:"max_attempts"`
	PayloadJson interface{} `db:"payload_json" json:"payload_json"`
	DedupeKey   *string     `db:"dedupe_key" json:"dedupe_key"`
}

// EnqueueJob
//
//	INSERT INTO jobs (
//	        id,
//	        kind,
//	        status,
//	        run_at,
//	        max_attempts,
//	        payload_json,
//	        dedupe_key
//	    )
//	VALUES (
//	        ?1,
//	        ?2,
//	        'queued',
//	        coalesce(
//	            ?3,
//	            strftime('%Y-%m-%dT%H:%M:%fZ', 'now')
//	        ),
//	        coalesce(?4, 3),
//	        coalesce(?5, '{}'),
//	        ?6
//	    ) ON CONFLICT(kind, dedupe_key)
//	WHERE dedupe_key IS NOT NULL DO
//	UPDATE
//	SET status = 'queued',
//	    run_at = excluded.run_at,
//	    max_attempts = excluded.max_attempts,
//	    payload_json = excluded.payload_json,
//	    attempts = 0,
//	    last_error = NULL,
//	    updated_at = strftime('%Y-%m-%dT%H:%M:%fZ', 'now')
//	RETURNING id, kind, status, run_at, attempts, max_attempts, locked_at, locked_by, payload_json, dedupe_key, last_error, created_at, updated_at, completed_at
func (q *Queries) EnqueueJob(ctx context.Context, arg EnqueueJobParams) (Job, error) {
	row := q.db.QueryRowContext(ctx, EnqueueJob,
		arg.ID,
		arg.Kind,
		arg.RunAt,
		arg.MaxAttempts,
		arg.PayloadJson,
		arg.DedupeKey,
	)
	var i Job
	err := row.Scan(
		&i.ID,
		&i.Kind,
		&i.Status,
		&i.RunAt,
		&i.Attempts,
		&i.MaxAttempts,
		&i.LockedAt,
		&i.LockedBy,
		&i.PayloadJson,
		&i.DedupeKey,
		&i.LastError,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.CompletedAt,
	)
	return i, err
}

const FindNextRunnableJob = `-- name: FindNextRunnableJob :one
SELECT id
FROM jobs
WHERE status = 'queued'
    AND run_at <= strftime('%Y-%m-%dT%H:%M:%fZ', 'now')
ORDER BY run_at ASC,
    created_at ASC
LIMIT 1
`

// FindNextRunnableJob
//
//	SELECT id
//	FROM jobs
//	WHERE status = 'queued'
//	    AND run_at <= strftime('%Y-%m-%dT%H:%M:%fZ', 'now')
//	ORDER BY run_at ASC,
//	    created_at ASC
//	LIMIT 1
func (q *Queries) FindNextRunnableJob(ctx context.Context) (ids.UUID, error) {
	row := q.db.QueryRowContext(ctx, FindNextRunnableJob)
	var id ids.UUID
	err := row.Scan(&id)
	return id, err
}

const GetJob = `-- name: GetJob :one
SELECT id, kind, status, run_at, attempts, max_attempts, locked_at, locked_by, payload_json, dedupe_key, last_error, created_at, updated_at, completed_at
FROM jobs
WHERE id = ?1
LIMIT 1
`

type GetJobParams struct {
	ID ids.UUID `db:"id" json:"id"`
}

// GetJob
//
//	SELECT id, kind, status, run_at, attempts, max_attempts, locked_at, locked_by, payload_json, dedupe_key, last_error, created_at, updated_at, completed_at
//	FROM jobs
//	WHERE id = ?1
//	LIMIT 1
func (q *Queries) GetJob(ctx context.Context, arg GetJobParams) (Job, error) {
	row := q.db.QueryRowContext(ctx, GetJob, arg.ID)
	var i Job
	err := row.Scan(
		&i.ID,
		&i.Kind,
		&i.Status,
		&i.RunAt,
		&i.Attempts,
		&i.MaxAttempts,
		&i.LockedAt,
		&i.LockedBy,
		&i.PayloadJson,
		&i.DedupeKey,
		&i.LastError,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.CompletedAt,
	)
	return i, err
}

const ListJobs = `-- name: ListJobs :many
SELECT id, kind, status, run_at, attempts, max_attempts, locked_at, locked_by, payload_json, dedupe_key, last_error, created_at, updated_at, completed_at
FROM jobs
ORDER BY created_at DESC
LIMIT ?2 OFFSET ?1
`

type ListJobsParams struct {
	Off int64 `db:"off" json:"off"`
	Lim int64 `db:"lim" json:"lim"`
}

// ListJobs
//
//	SELECT id, kind, status, run_at, attempts, max_attempts, locked_at, locked_by, payload_json, dedupe_key, last_error, created_at, updated_at, completed_at
//	FROM jobs
//	ORDER BY created_at DESC
//	LIMIT ?2 OFFSET ?1
func (q *Queries) ListJobs(ctx context.Context, arg ListJobsParams) ([]Job, error) {
	rows, err := q.db.QueryContext(ctx, ListJobs, arg.Off, arg.Lim)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Job{}
	for rows.Next() {
		var i Job
		if err := rows.Scan(
			&i.ID,
			&i.Kind,
			&i.Status,
			&i.RunAt,
			&i.Attempts,
			&i.MaxAttempts,
			&i.LockedAt,
			&i.LockedBy,
			&i.PayloadJson,
			&i.DedupeKey,
			&i.LastError,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.CompletedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const MarkJobFailed = `-- name: MarkJobFailed :one
UPDATE jobs
SET status = 'failed',
    completed_at = strftime('%Y-%m-%dT%H:%M:%fZ', 'now'),
    updated_at = strftime('%Y-%m-%dT%H:%M:%fZ', 'now'),
    last_error = ?1
WHERE id = ?2
RETURNING id, kind, status, run_at, attempts, max_attempts, locked_at, locked_by, payload_json, dedupe_key, last_error, created_at, updated_at, completed_at
`

type MarkJobFailedParams struct {
	LastError *string  `db:"last_error" json:"last_error"`
	ID        ids.UUID `db:"id" json:"id"`
}

// MarkJobFailed
//
//	UPDATE jobs
//	SET status = 'failed',
//	    completed_at = strftime('%Y-%m-%dT%H:%M:%fZ', 'now'),
//	    updated_at = strftime('%Y-%m-%dT%H:%M:%fZ', 'now'),
//	    last_error = ?1
//	WHERE id = ?2
//	RETURNING id, kind, status, run_at, attempts, max_attempts, locked_at, locked_by, payload_json, dedupe_key, last_error, created_at, updated_at, completed_at
func (q *Queries) MarkJobFailed(ctx context.Context, arg MarkJobFailedParams) (Job, error) {
	row := q.db.QueryRowContext(ctx, MarkJobFailed, arg.LastError, arg.ID)
	var i Job
	err := row.Scan(
		&i.ID,
		&i.Kind,
		&i.Status,
		&i.RunAt,
		&i.Attempts,
		&i.MaxAttempts,
		&i.LockedAt,
		&i.LockedBy,
		&i.PayloadJson,
		&i.DedupeKey,
		&i.LastError,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.CompletedAt,
	)
	return i, err
}

const MarkJobSucceeded = `-- name: MarkJobSucceeded :one
UPDATE jobs
SET status = 'succeeded',
    completed_at = strftime('%Y-%m-%dT%H:%M:%fZ', 'now'),
    updated_at = strftime('%Y-%m-%dT%H:%M:%fZ', 'now'),
    last_error = NULL
WHERE id = ?1
RETURNING id, kind, status, run_at, attempts, max_attempts, locked_at, locked_by, payload_json, dedupe_key, last_error, created_at, updated_at, completed_at
`

type MarkJobSucceededParams struct {
	ID ids.UUID `db:"id" json:"id"`
}

// MarkJobSucceeded
//
//	UPDATE jobs
//	SET status = 'succeeded',
//	    completed_at = strftime('%Y-%m-%dT%H:%M:%fZ', 'now'),
//	    updated_at = strftime('%Y-%m-%dT%H:%M:%fZ', 'now'),
//	    last_error = NULL
//	WHERE id = ?1
//	RETURNING id, kind, status, run_at, attempts, max_attempts, locked_at, locked_by, payload_json, dedupe_key, last_error, created_at, updated_at, completed_at
func (q *Queries) MarkJobSucceeded(ctx context.Context, arg MarkJobSucceededParams) (Job, error) {
	row := q.db.QueryRowContext(ctx, MarkJobSucceeded, arg.ID)
	var i Job
	err := row.Scan(
		&i.ID,
		&i.Kind,
		&i.Status,
		&i.RunAt,
		&i.Attempts,
		&i.MaxAttempts,
		&i.LockedAt,
		&i.LockedBy,
		&i.PayloadJson,
		&i.DedupeKey,
		&i.LastError,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.CompletedAt,
	)
	return i, err
}

const RequeueJob = `-- name: RequeueJob :one
UPDATE jobs
SET status = 'queued',
    run_at = coalesce(
        ?1,
        strftime('%Y-%m-%dT%H:%M:%fZ', 'now')
    ),
    updated_at = strftime('%Y-%m-%dT%H:%M:%fZ', 'now'),
    last_error = ?2,
    locked_at = NULL,
    locked_by = NULL,
    completed_at = NULL
WHERE id = ?3
RETURNING id, kind, status, run_at, attempts, max_attempts, locked_at, locked_by, payload_json, dedupe_key, last_error, created_at, updated_at, completed_at
`

type RequeueJobParams struct {
	RunAt     time.Time `db:"run_at" json:"run_at"`
	LastError *string   `db:"last_error" json:"last_error"`
	ID        ids.UUID  `db:"id" json:"id"`
}

// RequeueJob
//
//	UPDATE jobs
//	SET status = 'queued',
//	    run_at = coalesce(
//	        ?1,
//	        strftime('%Y-%m-%dT%H:%M:%fZ', 'now')
//	    ),
//	    updated_at = strftime('%Y-%m-%dT%H:%M:%fZ', 'now'),
//	    last_error = ?2,
//	    locked_at = NULL,
//	    locked_by = NULL,
//	    completed_at = NULL
//	WHERE id = ?3
//	RETURNING id, kind, status, run_at, attempts, max_attempts, locked_at, locked_by, payload_json, dedupe_key, last_error, created_at, updated_at, completed_at
func (q *Queries) RequeueJob(ctx context.Context, arg RequeueJobParams) (Job, error) {
	row := q.db.QueryRowContext(ctx, RequeueJob, arg.RunAt, arg.LastError, arg.ID)
	var i Job
	err := row.Scan(
		&i.ID,
		&i.Kind,
		&i.Status,
		&i.RunAt,
		&i.Attempts,
		&i.MaxAttempts,
		&i.LockedAt,
		&i.LockedBy,
		&i.PayloadJson,
		&i.DedupeKey,
		&i.LastError,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.CompletedAt,
	)
	return i, err
}
