// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: map_ops.sql

package sqlc

import (
	"context"
	"time"

	"github.com/ZanzyTHEbar/dragonscale/pkg/ids"
)

const CountMapItemsByRun = `-- name: CountMapItemsByRun :one
SELECT count(*) AS count
FROM map_items
WHERE run_id = ?1
`

type CountMapItemsByRunParams struct {
	RunID ids.UUID `db:"run_id" json:"run_id"`
}

// CountMapItemsByRun
//
//	SELECT count(*) AS count
//	FROM map_items
//	WHERE run_id = ?1
func (q *Queries) CountMapItemsByRun(ctx context.Context, arg CountMapItemsByRunParams) (int64, error) {
	row := q.db.QueryRowContext(ctx, CountMapItemsByRun, arg.RunID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const CountMapItemsByRunAndStatus = `-- name: CountMapItemsByRunAndStatus :many
SELECT status,
    count(*) AS count
FROM map_items
WHERE run_id = ?1
GROUP BY status
`

type CountMapItemsByRunAndStatusParams struct {
	RunID ids.UUID `db:"run_id" json:"run_id"`
}

type CountMapItemsByRunAndStatusRow struct {
	Status string `db:"status" json:"status"`
	Count  int64  `db:"count" json:"count"`
}

// CountMapItemsByRunAndStatus
//
//	SELECT status,
//	    count(*) AS count
//	FROM map_items
//	WHERE run_id = ?1
//	GROUP BY status
func (q *Queries) CountMapItemsByRunAndStatus(ctx context.Context, arg CountMapItemsByRunAndStatusParams) ([]CountMapItemsByRunAndStatusRow, error) {
	rows, err := q.db.QueryContext(ctx, CountMapItemsByRunAndStatus, arg.RunID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []CountMapItemsByRunAndStatusRow{}
	for rows.Next() {
		var i CountMapItemsByRunAndStatusRow
		if err := rows.Scan(&i.Status, &i.Count); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const GetMapItemByID = `-- name: GetMapItemByID :one
SELECT id, run_id, item_index, status, attempts, last_error, input_fb, output_fb, input_hash, output_hash, created_at, updated_at, completed_at
FROM map_items
WHERE id = ?1
LIMIT 1
`

type GetMapItemByIDParams struct {
	ID ids.UUID `db:"id" json:"id"`
}

// GetMapItemByID
//
//	SELECT id, run_id, item_index, status, attempts, last_error, input_fb, output_fb, input_hash, output_hash, created_at, updated_at, completed_at
//	FROM map_items
//	WHERE id = ?1
//	LIMIT 1
func (q *Queries) GetMapItemByID(ctx context.Context, arg GetMapItemByIDParams) (MapItem, error) {
	row := q.db.QueryRowContext(ctx, GetMapItemByID, arg.ID)
	var i MapItem
	err := row.Scan(
		&i.ID,
		&i.RunID,
		&i.ItemIndex,
		&i.Status,
		&i.Attempts,
		&i.LastError,
		&i.InputFb,
		&i.OutputFb,
		&i.InputHash,
		&i.OutputHash,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.CompletedAt,
	)
	return i, err
}

const GetMapItemByRunAndIndex = `-- name: GetMapItemByRunAndIndex :one
SELECT id, run_id, item_index, status, attempts, last_error, input_fb, output_fb, input_hash, output_hash, created_at, updated_at, completed_at
FROM map_items
WHERE run_id = ?1
    AND item_index = ?2
LIMIT 1
`

type GetMapItemByRunAndIndexParams struct {
	RunID     ids.UUID `db:"run_id" json:"run_id"`
	ItemIndex int64    `db:"item_index" json:"item_index"`
}

// GetMapItemByRunAndIndex
//
//	SELECT id, run_id, item_index, status, attempts, last_error, input_fb, output_fb, input_hash, output_hash, created_at, updated_at, completed_at
//	FROM map_items
//	WHERE run_id = ?1
//	    AND item_index = ?2
//	LIMIT 1
func (q *Queries) GetMapItemByRunAndIndex(ctx context.Context, arg GetMapItemByRunAndIndexParams) (MapItem, error) {
	row := q.db.QueryRowContext(ctx, GetMapItemByRunAndIndex, arg.RunID, arg.ItemIndex)
	var i MapItem
	err := row.Scan(
		&i.ID,
		&i.RunID,
		&i.ItemIndex,
		&i.Status,
		&i.Attempts,
		&i.LastError,
		&i.InputFb,
		&i.OutputFb,
		&i.InputHash,
		&i.OutputHash,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.CompletedAt,
	)
	return i, err
}

const GetMapRunByID = `-- name: GetMapRunByID :one
SELECT id, agent_id, session_key, operator_kind, idempotency_key, status, total_items, queued_items, running_items, succeeded_items, failed_items, spec_fb, last_error, created_at, updated_at, completed_at
FROM map_runs
WHERE id = ?1
LIMIT 1
`

type GetMapRunByIDParams struct {
	ID ids.UUID `db:"id" json:"id"`
}

// GetMapRunByID
//
//	SELECT id, agent_id, session_key, operator_kind, idempotency_key, status, total_items, queued_items, running_items, succeeded_items, failed_items, spec_fb, last_error, created_at, updated_at, completed_at
//	FROM map_runs
//	WHERE id = ?1
//	LIMIT 1
func (q *Queries) GetMapRunByID(ctx context.Context, arg GetMapRunByIDParams) (MapRun, error) {
	row := q.db.QueryRowContext(ctx, GetMapRunByID, arg.ID)
	var i MapRun
	err := row.Scan(
		&i.ID,
		&i.AgentID,
		&i.SessionKey,
		&i.OperatorKind,
		&i.IdempotencyKey,
		&i.Status,
		&i.TotalItems,
		&i.QueuedItems,
		&i.RunningItems,
		&i.SucceededItems,
		&i.FailedItems,
		&i.SpecFb,
		&i.LastError,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.CompletedAt,
	)
	return i, err
}

const GetMapRunByIdempotencyKey = `-- name: GetMapRunByIdempotencyKey :one
SELECT id, agent_id, session_key, operator_kind, idempotency_key, status, total_items, queued_items, running_items, succeeded_items, failed_items, spec_fb, last_error, created_at, updated_at, completed_at
FROM map_runs
WHERE agent_id = ?1
    AND session_key = ?2
    AND operator_kind = ?3
    AND idempotency_key = ?4
LIMIT 1
`

type GetMapRunByIdempotencyKeyParams struct {
	AgentID        string  `db:"agent_id" json:"agent_id"`
	SessionKey     string  `db:"session_key" json:"session_key"`
	OperatorKind   string  `db:"operator_kind" json:"operator_kind"`
	IdempotencyKey *string `db:"idempotency_key" json:"idempotency_key"`
}

// GetMapRunByIdempotencyKey
//
//	SELECT id, agent_id, session_key, operator_kind, idempotency_key, status, total_items, queued_items, running_items, succeeded_items, failed_items, spec_fb, last_error, created_at, updated_at, completed_at
//	FROM map_runs
//	WHERE agent_id = ?1
//	    AND session_key = ?2
//	    AND operator_kind = ?3
//	    AND idempotency_key = ?4
//	LIMIT 1
func (q *Queries) GetMapRunByIdempotencyKey(ctx context.Context, arg GetMapRunByIdempotencyKeyParams) (MapRun, error) {
	row := q.db.QueryRowContext(ctx, GetMapRunByIdempotencyKey,
		arg.AgentID,
		arg.SessionKey,
		arg.OperatorKind,
		arg.IdempotencyKey,
	)
	var i MapRun
	err := row.Scan(
		&i.ID,
		&i.AgentID,
		&i.SessionKey,
		&i.OperatorKind,
		&i.IdempotencyKey,
		&i.Status,
		&i.TotalItems,
		&i.QueuedItems,
		&i.RunningItems,
		&i.SucceededItems,
		&i.FailedItems,
		&i.SpecFb,
		&i.LastError,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.CompletedAt,
	)
	return i, err
}

const InsertMapItem = `-- name: InsertMapItem :one
INSERT INTO map_items (
        id,
        run_id,
        item_index,
        status,
        attempts,
        last_error,
        input_fb,
        output_fb,
        input_hash,
        output_hash
    )
VALUES (
        ?1,
        ?2,
        ?3,
        ?4,
        ?5,
        ?6,
        ?7,
        ?8,
        ?9,
        ?10
    )
RETURNING id, run_id, item_index, status, attempts, last_error, input_fb, output_fb, input_hash, output_hash, created_at, updated_at, completed_at
`

type InsertMapItemParams struct {
	ID         ids.UUID `db:"id" json:"id"`
	RunID      ids.UUID `db:"run_id" json:"run_id"`
	ItemIndex  int64    `db:"item_index" json:"item_index"`
	Status     string   `db:"status" json:"status"`
	Attempts   int64    `db:"attempts" json:"attempts"`
	LastError  *string  `db:"last_error" json:"last_error"`
	InputFb    []byte   `db:"input_fb" json:"input_fb"`
	OutputFb   []byte   `db:"output_fb" json:"output_fb"`
	InputHash  *string  `db:"input_hash" json:"input_hash"`
	OutputHash *string  `db:"output_hash" json:"output_hash"`
}

// InsertMapItem
//
//	INSERT INTO map_items (
//	        id,
//	        run_id,
//	        item_index,
//	        status,
//	        attempts,
//	        last_error,
//	        input_fb,
//	        output_fb,
//	        input_hash,
//	        output_hash
//	    )
//	VALUES (
//	        ?1,
//	        ?2,
//	        ?3,
//	        ?4,
//	        ?5,
//	        ?6,
//	        ?7,
//	        ?8,
//	        ?9,
//	        ?10
//	    )
//	RETURNING id, run_id, item_index, status, attempts, last_error, input_fb, output_fb, input_hash, output_hash, created_at, updated_at, completed_at
func (q *Queries) InsertMapItem(ctx context.Context, arg InsertMapItemParams) (MapItem, error) {
	row := q.db.QueryRowContext(ctx, InsertMapItem,
		arg.ID,
		arg.RunID,
		arg.ItemIndex,
		arg.Status,
		arg.Attempts,
		arg.LastError,
		arg.InputFb,
		arg.OutputFb,
		arg.InputHash,
		arg.OutputHash,
	)
	var i MapItem
	err := row.Scan(
		&i.ID,
		&i.RunID,
		&i.ItemIndex,
		&i.Status,
		&i.Attempts,
		&i.LastError,
		&i.InputFb,
		&i.OutputFb,
		&i.InputHash,
		&i.OutputHash,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.CompletedAt,
	)
	return i, err
}

const InsertMapRun = `-- name: InsertMapRun :one
INSERT INTO map_runs (
        id,
        agent_id,
        session_key,
        operator_kind,
        idempotency_key,
        status,
        total_items,
        queued_items,
        running_items,
        succeeded_items,
        failed_items,
        spec_fb,
        last_error
    )
VALUES (
        ?1,
        ?2,
        ?3,
        ?4,
        ?5,
        ?6,
        ?7,
        ?8,
        ?9,
        ?10,
        ?11,
        ?12,
        ?13
    )
RETURNING id, agent_id, session_key, operator_kind, idempotency_key, status, total_items, queued_items, running_items, succeeded_items, failed_items, spec_fb, last_error, created_at, updated_at, completed_at
`

type InsertMapRunParams struct {
	ID             ids.UUID `db:"id" json:"id"`
	AgentID        string   `db:"agent_id" json:"agent_id"`
	SessionKey     string   `db:"session_key" json:"session_key"`
	OperatorKind   string   `db:"operator_kind" json:"operator_kind"`
	IdempotencyKey *string  `db:"idempotency_key" json:"idempotency_key"`
	Status         string   `db:"status" json:"status"`
	TotalItems     int64    `db:"total_items" json:"total_items"`
	QueuedItems    int64    `db:"queued_items" json:"queued_items"`
	RunningItems   int64    `db:"running_items" json:"running_items"`
	SucceededItems int64    `db:"succeeded_items" json:"succeeded_items"`
	FailedItems    int64    `db:"failed_items" json:"failed_items"`
	SpecFb         []byte   `db:"spec_fb" json:"spec_fb"`
	LastError      *string  `db:"last_error" json:"last_error"`
}

// InsertMapRun
//
//	INSERT INTO map_runs (
//	        id,
//	        agent_id,
//	        session_key,
//	        operator_kind,
//	        idempotency_key,
//	        status,
//	        total_items,
//	        queued_items,
//	        running_items,
//	        succeeded_items,
//	        failed_items,
//	        spec_fb,
//	        last_error
//	    )
//	VALUES (
//	        ?1,
//	        ?2,
//	        ?3,
//	        ?4,
//	        ?5,
//	        ?6,
//	        ?7,
//	        ?8,
//	        ?9,
//	        ?10,
//	        ?11,
//	        ?12,
//	        ?13
//	    )
//	RETURNING id, agent_id, session_key, operator_kind, idempotency_key, status, total_items, queued_items, running_items, succeeded_items, failed_items, spec_fb, last_error, created_at, updated_at, completed_at
func (q *Queries) InsertMapRun(ctx context.Context, arg InsertMapRunParams) (MapRun, error) {
	row := q.db.QueryRowContext(ctx, InsertMapRun,
		arg.ID,
		arg.AgentID,
		arg.SessionKey,
		arg.OperatorKind,
		arg.IdempotencyKey,
		arg.Status,
		arg.TotalItems,
		arg.QueuedItems,
		arg.RunningItems,
		arg.SucceededItems,
		arg.FailedItems,
		arg.SpecFb,
		arg.LastError,
	)
	var i MapRun
	err := row.Scan(
		&i.ID,
		&i.AgentID,
		&i.SessionKey,
		&i.OperatorKind,
		&i.IdempotencyKey,
		&i.Status,
		&i.TotalItems,
		&i.QueuedItems,
		&i.RunningItems,
		&i.SucceededItems,
		&i.FailedItems,
		&i.SpecFb,
		&i.LastError,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.CompletedAt,
	)
	return i, err
}

const ListMapItemsByRunPaged = `-- name: ListMapItemsByRunPaged :many
SELECT id, run_id, item_index, status, attempts, last_error, input_fb, output_fb, input_hash, output_hash, created_at, updated_at, completed_at
FROM map_items
WHERE run_id = ?1
ORDER BY item_index ASC
LIMIT ?3 OFFSET ?2
`

type ListMapItemsByRunPagedParams struct {
	RunID ids.UUID `db:"run_id" json:"run_id"`
	Off   int64    `db:"off" json:"off"`
	Lim   int64    `db:"lim" json:"lim"`
}

// ListMapItemsByRunPaged
//
//	SELECT id, run_id, item_index, status, attempts, last_error, input_fb, output_fb, input_hash, output_hash, created_at, updated_at, completed_at
//	FROM map_items
//	WHERE run_id = ?1
//	ORDER BY item_index ASC
//	LIMIT ?3 OFFSET ?2
func (q *Queries) ListMapItemsByRunPaged(ctx context.Context, arg ListMapItemsByRunPagedParams) ([]MapItem, error) {
	rows, err := q.db.QueryContext(ctx, ListMapItemsByRunPaged, arg.RunID, arg.Off, arg.Lim)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []MapItem{}
	for rows.Next() {
		var i MapItem
		if err := rows.Scan(
			&i.ID,
			&i.RunID,
			&i.ItemIndex,
			&i.Status,
			&i.Attempts,
			&i.LastError,
			&i.InputFb,
			&i.OutputFb,
			&i.InputHash,
			&i.OutputHash,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.CompletedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const ListMapRunsBySession = `-- name: ListMapRunsBySession :many
SELECT id, agent_id, session_key, operator_kind, idempotency_key, status, total_items, queued_items, running_items, succeeded_items, failed_items, spec_fb, last_error, created_at, updated_at, completed_at
FROM map_runs
WHERE agent_id = ?1
    AND session_key = ?2
ORDER BY created_at DESC
LIMIT ?4 OFFSET ?3
`

type ListMapRunsBySessionParams struct {
	AgentID    string `db:"agent_id" json:"agent_id"`
	SessionKey string `db:"session_key" json:"session_key"`
	Off        int64  `db:"off" json:"off"`
	Lim        int64  `db:"lim" json:"lim"`
}

// ListMapRunsBySession
//
//	SELECT id, agent_id, session_key, operator_kind, idempotency_key, status, total_items, queued_items, running_items, succeeded_items, failed_items, spec_fb, last_error, created_at, updated_at, completed_at
//	FROM map_runs
//	WHERE agent_id = ?1
//	    AND session_key = ?2
//	ORDER BY created_at DESC
//	LIMIT ?4 OFFSET ?3
func (q *Queries) ListMapRunsBySession(ctx context.Context, arg ListMapRunsBySessionParams) ([]MapRun, error) {
	rows, err := q.db.QueryContext(ctx, ListMapRunsBySession,
		arg.AgentID,
		arg.SessionKey,
		arg.Off,
		arg.Lim,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []MapRun{}
	for rows.Next() {
		var i MapRun
		if err := rows.Scan(
			&i.ID,
			&i.AgentID,
			&i.SessionKey,
			&i.OperatorKind,
			&i.IdempotencyKey,
			&i.Status,
			&i.TotalItems,
			&i.QueuedItems,
			&i.RunningItems,
			&i.SucceededItems,
			&i.FailedItems,
			&i.SpecFb,
			&i.LastError,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.CompletedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const MarkMapItemFailed = `-- name: MarkMapItemFailed :one
UPDATE map_items
SET status = 'failed',
    last_error = ?1,
    updated_at = strftime('%Y-%m-%dT%H:%M:%fZ', 'now'),
    completed_at = strftime('%Y-%m-%dT%H:%M:%fZ', 'now')
WHERE id = ?2
RETURNING id, run_id, item_index, status, attempts, last_error, input_fb, output_fb, input_hash, output_hash, created_at, updated_at, completed_at
`

type MarkMapItemFailedParams struct {
	LastError *string  `db:"last_error" json:"last_error"`
	ID        ids.UUID `db:"id" json:"id"`
}

// MarkMapItemFailed
//
//	UPDATE map_items
//	SET status = 'failed',
//	    last_error = ?1,
//	    updated_at = strftime('%Y-%m-%dT%H:%M:%fZ', 'now'),
//	    completed_at = strftime('%Y-%m-%dT%H:%M:%fZ', 'now')
//	WHERE id = ?2
//	RETURNING id, run_id, item_index, status, attempts, last_error, input_fb, output_fb, input_hash, output_hash, created_at, updated_at, completed_at
func (q *Queries) MarkMapItemFailed(ctx context.Context, arg MarkMapItemFailedParams) (MapItem, error) {
	row := q.db.QueryRowContext(ctx, MarkMapItemFailed, arg.LastError, arg.ID)
	var i MapItem
	err := row.Scan(
		&i.ID,
		&i.RunID,
		&i.ItemIndex,
		&i.Status,
		&i.Attempts,
		&i.LastError,
		&i.InputFb,
		&i.OutputFb,
		&i.InputHash,
		&i.OutputHash,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.CompletedAt,
	)
	return i, err
}

const MarkMapItemRunning = `-- name: MarkMapItemRunning :one
UPDATE map_items
SET status = 'running',
    attempts = attempts + 1,
    last_error = NULL,
    updated_at = strftime('%Y-%m-%dT%H:%M:%fZ', 'now')
WHERE id = ?1
RETURNING id, run_id, item_index, status, attempts, last_error, input_fb, output_fb, input_hash, output_hash, created_at, updated_at, completed_at
`

type MarkMapItemRunningParams struct {
	ID ids.UUID `db:"id" json:"id"`
}

// MarkMapItemRunning
//
//	UPDATE map_items
//	SET status = 'running',
//	    attempts = attempts + 1,
//	    last_error = NULL,
//	    updated_at = strftime('%Y-%m-%dT%H:%M:%fZ', 'now')
//	WHERE id = ?1
//	RETURNING id, run_id, item_index, status, attempts, last_error, input_fb, output_fb, input_hash, output_hash, created_at, updated_at, completed_at
func (q *Queries) MarkMapItemRunning(ctx context.Context, arg MarkMapItemRunningParams) (MapItem, error) {
	row := q.db.QueryRowContext(ctx, MarkMapItemRunning, arg.ID)
	var i MapItem
	err := row.Scan(
		&i.ID,
		&i.RunID,
		&i.ItemIndex,
		&i.Status,
		&i.Attempts,
		&i.LastError,
		&i.InputFb,
		&i.OutputFb,
		&i.InputHash,
		&i.OutputHash,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.CompletedAt,
	)
	return i, err
}

const MarkMapItemSucceeded = `-- name: MarkMapItemSucceeded :one
UPDATE map_items
SET status = 'succeeded',
    output_fb = ?1,
    output_hash = ?2,
    last_error = NULL,
    updated_at = strftime('%Y-%m-%dT%H:%M:%fZ', 'now'),
    completed_at = strftime('%Y-%m-%dT%H:%M:%fZ', 'now')
WHERE id = ?3
RETURNING id, run_id, item_index, status, attempts, last_error, input_fb, output_fb, input_hash, output_hash, created_at, updated_at, completed_at
`

type MarkMapItemSucceededParams struct {
	OutputFb   []byte   `db:"output_fb" json:"output_fb"`
	OutputHash *string  `db:"output_hash" json:"output_hash"`
	ID         ids.UUID `db:"id" json:"id"`
}

// MarkMapItemSucceeded
//
//	UPDATE map_items
//	SET status = 'succeeded',
//	    output_fb = ?1,
//	    output_hash = ?2,
//	    last_error = NULL,
//	    updated_at = strftime('%Y-%m-%dT%H:%M:%fZ', 'now'),
//	    completed_at = strftime('%Y-%m-%dT%H:%M:%fZ', 'now')
//	WHERE id = ?3
//	RETURNING id, run_id, item_index, status, attempts, last_error, input_fb, output_fb, input_hash, output_hash, created_at, updated_at, completed_at
func (q *Queries) MarkMapItemSucceeded(ctx context.Context, arg MarkMapItemSucceededParams) (MapItem, error) {
	row := q.db.QueryRowContext(ctx, MarkMapItemSucceeded, arg.OutputFb, arg.OutputHash, arg.ID)
	var i MapItem
	err := row.Scan(
		&i.ID,
		&i.RunID,
		&i.ItemIndex,
		&i.Status,
		&i.Attempts,
		&i.LastError,
		&i.InputFb,
		&i.OutputFb,
		&i.InputHash,
		&i.OutputHash,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.CompletedAt,
	)
	return i, err
}

const UpdateMapRunProgress = `-- name: UpdateMapRunProgress :one
UPDATE map_runs
SET status = ?1,
    queued_items = ?2,
    running_items = ?3,
    succeeded_items = ?4,
    failed_items = ?5,
    last_error = ?6,
    updated_at = strftime('%Y-%m-%dT%H:%M:%fZ', 'now'),
    completed_at = ?7
WHERE id = ?8
RETURNING id, agent_id, session_key, operator_kind, idempotency_key, status, total_items, queued_items, running_items, succeeded_items, failed_items, spec_fb, last_error, created_at, updated_at, completed_at
`

type UpdateMapRunProgressParams struct {
	Status         string     `db:"status" json:"status"`
	QueuedItems    int64      `db:"queued_items" json:"queued_items"`
	RunningItems   int64      `db:"running_items" json:"running_items"`
	SucceededItems int64      `db:"succeeded_items" json:"succeeded_items"`
	FailedItems    int64      `db:"failed_items" json:"failed_items"`
	LastError      *string    `db:"last_error" json:"last_error"`
	CompletedAt    *time.Time `db:"completed_at" json:"completed_at"`
	ID             ids.UUID   `db:"id" json:"id"`
}

// UpdateMapRunProgress
//
//	UPDATE map_runs
//	SET status = ?1,
//	    queued_items = ?2,
//	    running_items = ?3,
//	    succeeded_items = ?4,
//	    failed_items = ?5,
//	    last_error = ?6,
//	    updated_at = strftime('%Y-%m-%dT%H:%M:%fZ', 'now'),
//	    completed_at = ?7
//	WHERE id = ?8
//	RETURNING id, agent_id, session_key, operator_kind, idempotency_key, status, total_items, queued_items, running_items, succeeded_items, failed_items, spec_fb, last_error, created_at, updated_at, completed_at
func (q *Queries) UpdateMapRunProgress(ctx context.Context, arg UpdateMapRunProgressParams) (MapRun, error) {
	row := q.db.QueryRowContext(ctx, UpdateMapRunProgress,
		arg.Status,
		arg.QueuedItems,
		arg.RunningItems,
		arg.SucceededItems,
		arg.FailedItems,
		arg.LastError,
		arg.CompletedAt,
		arg.ID,
	)
	var i MapRun
	err := row.Scan(
		&i.ID,
		&i.AgentID,
		&i.SessionKey,
		&i.OperatorKind,
		&i.IdempotencyKey,
		&i.Status,
		&i.TotalItems,
		&i.QueuedItems,
		&i.RunningItems,
		&i.SucceededItems,
		&i.FailedItems,
		&i.SpecFb,
		&i.LastError,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.CompletedAt,
	)
	return i, err
}
