// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: memory_edges.sql

package sqlc

import (
	"context"

	"github.com/ZanzyTHEbar/dragonscale/pkg/ids"
)

const CountMemoryEdgesForItem = `-- name: CountMemoryEdgesForItem :one
SELECT COUNT(*)
FROM memory_edges
WHERE from_id = ?1
    OR to_id = ?1
`

type CountMemoryEdgesForItemParams struct {
	MemoryID ids.UUID `db:"memory_id" json:"memory_id"`
}

// CountMemoryEdgesForItem
//
//	SELECT COUNT(*)
//	FROM memory_edges
//	WHERE from_id = ?1
//	    OR to_id = ?1
func (q *Queries) CountMemoryEdgesForItem(ctx context.Context, arg CountMemoryEdgesForItemParams) (int64, error) {
	row := q.db.QueryRowContext(ctx, CountMemoryEdgesForItem, arg.MemoryID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const DeleteMemoryEdgesForItem = `-- name: DeleteMemoryEdgesForItem :exec
DELETE FROM memory_edges
WHERE from_id = ?1
    OR to_id = ?1
`

type DeleteMemoryEdgesForItemParams struct {
	MemoryID ids.UUID `db:"memory_id" json:"memory_id"`
}

// DeleteMemoryEdgesForItem
//
//	DELETE FROM memory_edges
//	WHERE from_id = ?1
//	    OR to_id = ?1
func (q *Queries) DeleteMemoryEdgesForItem(ctx context.Context, arg DeleteMemoryEdgesForItemParams) error {
	_, err := q.db.ExecContext(ctx, DeleteMemoryEdgesForItem, arg.MemoryID)
	return err
}

const InsertMemoryEdge = `-- name: InsertMemoryEdge :one
INSERT INTO memory_edges (from_id, to_id, edge_type, weight)
VALUES (
        ?1,
        ?2,
        ?3,
        ?4
    )
RETURNING id,
    from_id,
    to_id,
    edge_type,
    weight,
    created_at
`

type InsertMemoryEdgeParams struct {
	FromID   ids.UUID `db:"from_id" json:"from_id"`
	ToID     ids.UUID `db:"to_id" json:"to_id"`
	EdgeType string   `db:"edge_type" json:"edge_type"`
	Weight   float64  `db:"weight" json:"weight"`
}

// Memory Graph Edges queries (ADR-004: typed relational memory)
//
//	INSERT INTO memory_edges (from_id, to_id, edge_type, weight)
//	VALUES (
//	        ?1,
//	        ?2,
//	        ?3,
//	        ?4
//	    )
//	RETURNING id,
//	    from_id,
//	    to_id,
//	    edge_type,
//	    weight,
//	    created_at
func (q *Queries) InsertMemoryEdge(ctx context.Context, arg InsertMemoryEdgeParams) (MemoryEdge, error) {
	row := q.db.QueryRowContext(ctx, InsertMemoryEdge,
		arg.FromID,
		arg.ToID,
		arg.EdgeType,
		arg.Weight,
	)
	var i MemoryEdge
	err := row.Scan(
		&i.ID,
		&i.FromID,
		&i.ToID,
		&i.EdgeType,
		&i.Weight,
		&i.CreatedAt,
	)
	return i, err
}

const ListMemoryEdgesByType = `-- name: ListMemoryEdgesByType :many
SELECT id,
    from_id,
    to_id,
    edge_type,
    weight,
    created_at
FROM memory_edges
WHERE edge_type = ?1
ORDER BY created_at DESC
LIMIT ?2
`

type ListMemoryEdgesByTypeParams struct {
	EdgeType string `db:"edge_type" json:"edge_type"`
	Lim      int64  `db:"lim" json:"lim"`
}

// ListMemoryEdgesByType
//
//	SELECT id,
//	    from_id,
//	    to_id,
//	    edge_type,
//	    weight,
//	    created_at
//	FROM memory_edges
//	WHERE edge_type = ?1
//	ORDER BY created_at DESC
//	LIMIT ?2
func (q *Queries) ListMemoryEdgesByType(ctx context.Context, arg ListMemoryEdgesByTypeParams) ([]MemoryEdge, error) {
	rows, err := q.db.QueryContext(ctx, ListMemoryEdgesByType, arg.EdgeType, arg.Lim)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []MemoryEdge{}
	for rows.Next() {
		var i MemoryEdge
		if err := rows.Scan(
			&i.ID,
			&i.FromID,
			&i.ToID,
			&i.EdgeType,
			&i.Weight,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const ListMemoryEdgesForItem = `-- name: ListMemoryEdgesForItem :many
SELECT id,
    from_id,
    to_id,
    edge_type,
    weight,
    created_at
FROM memory_edges
WHERE from_id = ?1
    OR to_id = ?1
ORDER BY created_at DESC
LIMIT ?2
`

type ListMemoryEdgesForItemParams struct {
	MemoryID ids.UUID `db:"memory_id" json:"memory_id"`
	Lim      int64    `db:"lim" json:"lim"`
}

// ListMemoryEdgesForItem
//
//	SELECT id,
//	    from_id,
//	    to_id,
//	    edge_type,
//	    weight,
//	    created_at
//	FROM memory_edges
//	WHERE from_id = ?1
//	    OR to_id = ?1
//	ORDER BY created_at DESC
//	LIMIT ?2
func (q *Queries) ListMemoryEdgesForItem(ctx context.Context, arg ListMemoryEdgesForItemParams) ([]MemoryEdge, error) {
	rows, err := q.db.QueryContext(ctx, ListMemoryEdgesForItem, arg.MemoryID, arg.Lim)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []MemoryEdge{}
	for rows.Next() {
		var i MemoryEdge
		if err := rows.Scan(
			&i.ID,
			&i.FromID,
			&i.ToID,
			&i.EdgeType,
			&i.Weight,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
