// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package sqlc

import (
	"time"

	"github.com/sipeed/picoclaw/pkg/ids"
	"github.com/sipeed/picoclaw/pkg/memory"
)

type ArchivalChunk struct {
	ID         ids.UUID         `json:"id"`
	RecallID   ids.UUID         `json:"recall_id"`
	ChunkIndex int64            `json:"chunk_index"`
	Content    string           `json:"content"`
	Embedding  memory.Embedding `json:"embedding"`
	Source     string           `json:"source"`
	Hash       string           `json:"hash"`
	CreatedAt  time.Time        `json:"created_at"`
}

type MemorySummary struct {
	ID         ids.UUID  `json:"id"`
	AgentID    string    `json:"agent_id"`
	SessionKey string    `json:"session_key"`
	Content    string    `json:"content"`
	FromMsgIdx int64     `json:"from_msg_idx"`
	ToMsgIdx   int64     `json:"to_msg_idx"`
	CreatedAt  time.Time `json:"created_at"`
}

type RecallItem struct {
	ID         ids.UUID      `json:"id"`
	AgentID    string        `json:"agent_id"`
	SessionKey string        `json:"session_key"`
	Role       string        `json:"role"`
	Sector     memory.Sector `json:"sector"`
	Importance float64       `json:"importance"`
	Salience   float64       `json:"salience"`
	DecayRate  float64       `json:"decay_rate"`
	Content    string        `json:"content"`
	Tags       string        `json:"tags"`
	CreatedAt  time.Time     `json:"created_at"`
	UpdatedAt  time.Time     `json:"updated_at"`
}

type WorkingContext struct {
	AgentID    string    `json:"agent_id"`
	SessionKey string    `json:"session_key"`
	Content    string    `json:"content"`
	UpdatedAt  time.Time `json:"updated_at"`
}
