// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package sqlc

import (
	"time"

	"github.com/sipeed/picoclaw/pkg/ids"
	"github.com/sipeed/picoclaw/pkg/memory"
)

type AgentAuditLog struct {
	ID         ids.UUID  `json:"id"`
	AgentID    string    `json:"agent_id"`
	SessionKey string    `json:"session_key"`
	Action     string    `json:"action"`
	Target     string    `json:"target"`
	Input      *string   `json:"input"`
	Output     *string   `json:"output"`
	DurationMs *int64    `json:"duration_ms"`
	CreatedAt  time.Time `json:"created_at"`
}

type AgentDocument struct {
	ID        ids.UUID  `json:"id"`
	AgentID   string    `json:"agent_id"`
	Name      string    `json:"name"`
	Category  string    `json:"category"`
	Content   string    `json:"content"`
	Version   int64     `json:"version"`
	IsActive  bool      `json:"is_active"`
	CreatedAt time.Time `json:"created_at"`
	UpdatedAt time.Time `json:"updated_at"`
}

type AgentKv struct {
	AgentID   string    `json:"agent_id"`
	Key       string    `json:"key"`
	Value     string    `json:"value"`
	UpdatedAt time.Time `json:"updated_at"`
}

type ArchivalChunk struct {
	ID         ids.UUID         `json:"id"`
	RecallID   ids.UUID         `json:"recall_id"`
	ChunkIndex int64            `json:"chunk_index"`
	Content    string           `json:"content"`
	Embedding  memory.Embedding `json:"embedding"`
	Source     string           `json:"source"`
	Hash       string           `json:"hash"`
	CreatedAt  time.Time        `json:"created_at"`
}

type MemorySummary struct {
	ID         ids.UUID  `json:"id"`
	AgentID    string    `json:"agent_id"`
	SessionKey string    `json:"session_key"`
	Content    string    `json:"content"`
	FromMsgIdx int64     `json:"from_msg_idx"`
	ToMsgIdx   int64     `json:"to_msg_idx"`
	CreatedAt  time.Time `json:"created_at"`
}

type RecallItem struct {
	ID         ids.UUID      `json:"id"`
	AgentID    string        `json:"agent_id"`
	SessionKey string        `json:"session_key"`
	Role       string        `json:"role"`
	Sector     memory.Sector `json:"sector"`
	Importance float64       `json:"importance"`
	Salience   float64       `json:"salience"`
	DecayRate  float64       `json:"decay_rate"`
	Content    string        `json:"content"`
	Tags       string        `json:"tags"`
	CreatedAt  time.Time     `json:"created_at"`
	UpdatedAt  time.Time     `json:"updated_at"`
}

type WorkingContext struct {
	AgentID    string    `json:"agent_id"`
	SessionKey string    `json:"session_key"`
	Content    string    `json:"content"`
	UpdatedAt  time.Time `json:"updated_at"`
}
