// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: recall.sql

package sqlc

import (
	"context"
	"strings"

	"github.com/sipeed/picoclaw/pkg/ids"
	"github.com/sipeed/picoclaw/pkg/memory"
)

const CountRecallItems = `-- name: CountRecallItems :one
SELECT COUNT(*)
FROM recall_items
WHERE agent_id = ?1
    AND (
        session_key = ?2
        OR ?2 = ''
    )
`

type CountRecallItemsParams struct {
	AgentID    string `db:"agent_id" json:"agent_id"`
	SessionKey string `db:"session_key" json:"session_key"`
}

// CountRecallItems
//
//	SELECT COUNT(*)
//	FROM recall_items
//	WHERE agent_id = ?1
//	    AND (
//	        session_key = ?2
//	        OR ?2 = ''
//	    )
func (q *Queries) CountRecallItems(ctx context.Context, arg CountRecallItemsParams) (int64, error) {
	row := q.db.QueryRowContext(ctx, CountRecallItems, arg.AgentID, arg.SessionKey)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const CountSessionMessages = `-- name: CountSessionMessages :one
SELECT COUNT(*)
FROM recall_items
WHERE agent_id = ?1
    AND session_key = ?2
    AND tags = 'session-message'
`

type CountSessionMessagesParams struct {
	AgentID    string `db:"agent_id" json:"agent_id"`
	SessionKey string `db:"session_key" json:"session_key"`
}

// CountSessionMessages
//
//	SELECT COUNT(*)
//	FROM recall_items
//	WHERE agent_id = ?1
//	    AND session_key = ?2
//	    AND tags = 'session-message'
func (q *Queries) CountSessionMessages(ctx context.Context, arg CountSessionMessagesParams) (int64, error) {
	row := q.db.QueryRowContext(ctx, CountSessionMessages, arg.AgentID, arg.SessionKey)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const DeleteRecallItem = `-- name: DeleteRecallItem :exec
DELETE FROM recall_items
WHERE id = ?1
    AND agent_id = ?2
`

type DeleteRecallItemParams struct {
	ID      ids.UUID `db:"id" json:"id"`
	AgentID string   `db:"agent_id" json:"agent_id"`
}

// DeleteRecallItem
//
//	DELETE FROM recall_items
//	WHERE id = ?1
//	    AND agent_id = ?2
func (q *Queries) DeleteRecallItem(ctx context.Context, arg DeleteRecallItemParams) error {
	_, err := q.db.ExecContext(ctx, DeleteRecallItem, arg.ID, arg.AgentID)
	return err
}

const GetRecallItem = `-- name: GetRecallItem :one
SELECT id,
    agent_id,
    session_key,
    role,
    sector,
    importance,
    salience,
    decay_rate,
    content,
    tags,
    created_at,
    updated_at
FROM recall_items
WHERE id = ?1
    AND agent_id = ?2
LIMIT 1
`

type GetRecallItemParams struct {
	ID      ids.UUID `db:"id" json:"id"`
	AgentID string   `db:"agent_id" json:"agent_id"`
}

// GetRecallItem
//
//	SELECT id,
//	    agent_id,
//	    session_key,
//	    role,
//	    sector,
//	    importance,
//	    salience,
//	    decay_rate,
//	    content,
//	    tags,
//	    created_at,
//	    updated_at
//	FROM recall_items
//	WHERE id = ?1
//	    AND agent_id = ?2
//	LIMIT 1
func (q *Queries) GetRecallItem(ctx context.Context, arg GetRecallItemParams) (RecallItem, error) {
	row := q.db.QueryRowContext(ctx, GetRecallItem, arg.ID, arg.AgentID)
	var i RecallItem
	err := row.Scan(
		&i.ID,
		&i.AgentID,
		&i.SessionKey,
		&i.Role,
		&i.Sector,
		&i.Importance,
		&i.Salience,
		&i.DecayRate,
		&i.Content,
		&i.Tags,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const GetRecallItemsByIDs = `-- name: GetRecallItemsByIDs :many
SELECT id,
    agent_id,
    session_key,
    role,
    sector,
    importance,
    salience,
    decay_rate,
    content,
    tags,
    created_at,
    updated_at
FROM recall_items
WHERE id IN (/*SLICE:ids*/?)
    AND agent_id = ?2
`

type GetRecallItemsByIDsParams struct {
	Ids     []ids.UUID `db:"ids" json:"ids"`
	AgentID string     `db:"agent_id" json:"agent_id"`
}

// GetRecallItemsByIDs
//
//	SELECT id,
//	    agent_id,
//	    session_key,
//	    role,
//	    sector,
//	    importance,
//	    salience,
//	    decay_rate,
//	    content,
//	    tags,
//	    created_at,
//	    updated_at
//	FROM recall_items
//	WHERE id IN (/*SLICE:ids*/?)
//	    AND agent_id = ?2
func (q *Queries) GetRecallItemsByIDs(ctx context.Context, arg GetRecallItemsByIDsParams) ([]RecallItem, error) {
	query := GetRecallItemsByIDs
	var queryParams []interface{}
	if len(arg.Ids) > 0 {
		for _, v := range arg.Ids {
			queryParams = append(queryParams, v)
		}
		query = strings.Replace(query, "/*SLICE:ids*/?", strings.Repeat(",?", len(arg.Ids))[1:], 1)
	} else {
		query = strings.Replace(query, "/*SLICE:ids*/?", "NULL", 1)
	}
	queryParams = append(queryParams, arg.AgentID)
	rows, err := q.db.QueryContext(ctx, query, queryParams...)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []RecallItem{}
	for rows.Next() {
		var i RecallItem
		if err := rows.Scan(
			&i.ID,
			&i.AgentID,
			&i.SessionKey,
			&i.Role,
			&i.Sector,
			&i.Importance,
			&i.Salience,
			&i.DecayRate,
			&i.Content,
			&i.Tags,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const InsertRecallItem = `-- name: InsertRecallItem :exec
INSERT INTO recall_items (
        id,
        agent_id,
        session_key,
        role,
        sector,
        importance,
        salience,
        decay_rate,
        content,
        tags,
        created_at,
        updated_at
    )
VALUES (
        ?1,
        ?2,
        ?3,
        ?4,
        ?5,
        ?6,
        ?7,
        ?8,
        ?9,
        ?10,
        datetime('now'),
        datetime('now')
    )
`

type InsertRecallItemParams struct {
	ID         ids.UUID      `db:"id" json:"id"`
	AgentID    string        `db:"agent_id" json:"agent_id"`
	SessionKey string        `db:"session_key" json:"session_key"`
	Role       string        `db:"role" json:"role"`
	Sector     memory.Sector `db:"sector" json:"sector"`
	Importance float64       `db:"importance" json:"importance"`
	Salience   float64       `db:"salience" json:"salience"`
	DecayRate  float64       `db:"decay_rate" json:"decay_rate"`
	Content    string        `db:"content" json:"content"`
	Tags       string        `db:"tags" json:"tags"`
}

// Recall Item queries
//
//	INSERT INTO recall_items (
//	        id,
//	        agent_id,
//	        session_key,
//	        role,
//	        sector,
//	        importance,
//	        salience,
//	        decay_rate,
//	        content,
//	        tags,
//	        created_at,
//	        updated_at
//	    )
//	VALUES (
//	        ?1,
//	        ?2,
//	        ?3,
//	        ?4,
//	        ?5,
//	        ?6,
//	        ?7,
//	        ?8,
//	        ?9,
//	        ?10,
//	        datetime('now'),
//	        datetime('now')
//	    )
func (q *Queries) InsertRecallItem(ctx context.Context, arg InsertRecallItemParams) error {
	_, err := q.db.ExecContext(ctx, InsertRecallItem,
		arg.ID,
		arg.AgentID,
		arg.SessionKey,
		arg.Role,
		arg.Sector,
		arg.Importance,
		arg.Salience,
		arg.DecayRate,
		arg.Content,
		arg.Tags,
	)
	return err
}

const InsertSessionMessage = `-- name: InsertSessionMessage :exec
INSERT INTO recall_items (
        id,
        agent_id,
        session_key,
        role,
        sector,
        importance,
        salience,
        decay_rate,
        content,
        tags,
        created_at,
        updated_at
    )
VALUES (
        ?1,
        ?2,
        ?3,
        ?4,
        'episodic',
        0.5,
        0.5,
        0.01,
        ?5,
        'session-message',
        datetime('now'),
        datetime('now')
    )
`

type InsertSessionMessageParams struct {
	ID         ids.UUID `db:"id" json:"id"`
	AgentID    string   `db:"agent_id" json:"agent_id"`
	SessionKey string   `db:"session_key" json:"session_key"`
	Role       string   `db:"role" json:"role"`
	Content    string   `db:"content" json:"content"`
}

// InsertSessionMessage
//
//	INSERT INTO recall_items (
//	        id,
//	        agent_id,
//	        session_key,
//	        role,
//	        sector,
//	        importance,
//	        salience,
//	        decay_rate,
//	        content,
//	        tags,
//	        created_at,
//	        updated_at
//	    )
//	VALUES (
//	        ?1,
//	        ?2,
//	        ?3,
//	        ?4,
//	        'episodic',
//	        0.5,
//	        0.5,
//	        0.01,
//	        ?5,
//	        'session-message',
//	        datetime('now'),
//	        datetime('now')
//	    )
func (q *Queries) InsertSessionMessage(ctx context.Context, arg InsertSessionMessageParams) error {
	_, err := q.db.ExecContext(ctx, InsertSessionMessage,
		arg.ID,
		arg.AgentID,
		arg.SessionKey,
		arg.Role,
		arg.Content,
	)
	return err
}

const ListRecallItems = `-- name: ListRecallItems :many
SELECT id,
    agent_id,
    session_key,
    role,
    sector,
    importance,
    salience,
    decay_rate,
    content,
    tags,
    created_at,
    updated_at
FROM recall_items
WHERE agent_id = ?1
    AND (
        session_key = ?2
        OR ?2 = ''
    )
ORDER BY created_at DESC
LIMIT ?4 OFFSET ?3
`

type ListRecallItemsParams struct {
	AgentID    string `db:"agent_id" json:"agent_id"`
	SessionKey string `db:"session_key" json:"session_key"`
	Off        int64  `db:"off" json:"off"`
	Lim        int64  `db:"lim" json:"lim"`
}

// ListRecallItems
//
//	SELECT id,
//	    agent_id,
//	    session_key,
//	    role,
//	    sector,
//	    importance,
//	    salience,
//	    decay_rate,
//	    content,
//	    tags,
//	    created_at,
//	    updated_at
//	FROM recall_items
//	WHERE agent_id = ?1
//	    AND (
//	        session_key = ?2
//	        OR ?2 = ''
//	    )
//	ORDER BY created_at DESC
//	LIMIT ?4 OFFSET ?3
func (q *Queries) ListRecallItems(ctx context.Context, arg ListRecallItemsParams) ([]RecallItem, error) {
	rows, err := q.db.QueryContext(ctx, ListRecallItems,
		arg.AgentID,
		arg.SessionKey,
		arg.Off,
		arg.Lim,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []RecallItem{}
	for rows.Next() {
		var i RecallItem
		if err := rows.Scan(
			&i.ID,
			&i.AgentID,
			&i.SessionKey,
			&i.Role,
			&i.Sector,
			&i.Importance,
			&i.Salience,
			&i.DecayRate,
			&i.Content,
			&i.Tags,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const ListSessionMessages = `-- name: ListSessionMessages :many
SELECT id,
    agent_id,
    session_key,
    role,
    sector,
    importance,
    salience,
    decay_rate,
    content,
    tags,
    created_at,
    updated_at
FROM recall_items
WHERE agent_id = ?1
    AND session_key = ?2
    AND tags = 'session-message'
    AND (
        role = ?3
        OR ?3 = ''
    )
ORDER BY created_at ASC
LIMIT ?4
`

type ListSessionMessagesParams struct {
	AgentID    string `db:"agent_id" json:"agent_id"`
	SessionKey string `db:"session_key" json:"session_key"`
	Role       string `db:"role" json:"role"`
	Lim        int64  `db:"lim" json:"lim"`
}

// ListSessionMessages
//
//	SELECT id,
//	    agent_id,
//	    session_key,
//	    role,
//	    sector,
//	    importance,
//	    salience,
//	    decay_rate,
//	    content,
//	    tags,
//	    created_at,
//	    updated_at
//	FROM recall_items
//	WHERE agent_id = ?1
//	    AND session_key = ?2
//	    AND tags = 'session-message'
//	    AND (
//	        role = ?3
//	        OR ?3 = ''
//	    )
//	ORDER BY created_at ASC
//	LIMIT ?4
func (q *Queries) ListSessionMessages(ctx context.Context, arg ListSessionMessagesParams) ([]RecallItem, error) {
	rows, err := q.db.QueryContext(ctx, ListSessionMessages,
		arg.AgentID,
		arg.SessionKey,
		arg.Role,
		arg.Lim,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []RecallItem{}
	for rows.Next() {
		var i RecallItem
		if err := rows.Scan(
			&i.ID,
			&i.AgentID,
			&i.SessionKey,
			&i.Role,
			&i.Sector,
			&i.Importance,
			&i.Salience,
			&i.DecayRate,
			&i.Content,
			&i.Tags,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const SearchRecallByKeyword = `-- name: SearchRecallByKeyword :many
SELECT ri.id,
    ri.agent_id,
    ri.session_key,
    ri.role,
    ri.sector,
    ri.importance,
    ri.salience,
    ri.decay_rate,
    ri.content,
    ri.tags,
    ri.created_at,
    ri.updated_at
FROM recall_items ri
WHERE ri.content LIKE '%' || ?1 || '%'
    AND ri.agent_id = ?2
ORDER BY ri.importance DESC
LIMIT ?3
`

type SearchRecallByKeywordParams struct {
	Keyword *string `db:"keyword" json:"keyword"`
	AgentID string  `db:"agent_id" json:"agent_id"`
	Lim     int64   `db:"lim" json:"lim"`
}

// SearchRecallByKeyword
//
//	SELECT ri.id,
//	    ri.agent_id,
//	    ri.session_key,
//	    ri.role,
//	    ri.sector,
//	    ri.importance,
//	    ri.salience,
//	    ri.decay_rate,
//	    ri.content,
//	    ri.tags,
//	    ri.created_at,
//	    ri.updated_at
//	FROM recall_items ri
//	WHERE ri.content LIKE '%' || ?1 || '%'
//	    AND ri.agent_id = ?2
//	ORDER BY ri.importance DESC
//	LIMIT ?3
func (q *Queries) SearchRecallByKeyword(ctx context.Context, arg SearchRecallByKeywordParams) ([]RecallItem, error) {
	rows, err := q.db.QueryContext(ctx, SearchRecallByKeyword, arg.Keyword, arg.AgentID, arg.Lim)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []RecallItem{}
	for rows.Next() {
		var i RecallItem
		if err := rows.Scan(
			&i.ID,
			&i.AgentID,
			&i.SessionKey,
			&i.Role,
			&i.Sector,
			&i.Importance,
			&i.Salience,
			&i.DecayRate,
			&i.Content,
			&i.Tags,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const UpdateRecallItem = `-- name: UpdateRecallItem :exec
UPDATE recall_items
SET role = ?1,
    sector = ?2,
    importance = ?3,
    salience = ?4,
    decay_rate = ?5,
    content = ?6,
    tags = ?7,
    updated_at = datetime('now')
WHERE id = ?8
    AND agent_id = ?9
`

type UpdateRecallItemParams struct {
	Role       string        `db:"role" json:"role"`
	Sector     memory.Sector `db:"sector" json:"sector"`
	Importance float64       `db:"importance" json:"importance"`
	Salience   float64       `db:"salience" json:"salience"`
	DecayRate  float64       `db:"decay_rate" json:"decay_rate"`
	Content    string        `db:"content" json:"content"`
	Tags       string        `db:"tags" json:"tags"`
	ID         ids.UUID      `db:"id" json:"id"`
	AgentID    string        `db:"agent_id" json:"agent_id"`
}

// UpdateRecallItem
//
//	UPDATE recall_items
//	SET role = ?1,
//	    sector = ?2,
//	    importance = ?3,
//	    salience = ?4,
//	    decay_rate = ?5,
//	    content = ?6,
//	    tags = ?7,
//	    updated_at = datetime('now')
//	WHERE id = ?8
//	    AND agent_id = ?9
func (q *Queries) UpdateRecallItem(ctx context.Context, arg UpdateRecallItemParams) error {
	_, err := q.db.ExecContext(ctx, UpdateRecallItem,
		arg.Role,
		arg.Sector,
		arg.Importance,
		arg.Salience,
		arg.DecayRate,
		arg.Content,
		arg.Tags,
		arg.ID,
		arg.AgentID,
	)
	return err
}
