// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: rl.sql

package sqlc

import (
	"context"
	"time"

	"github.com/ZanzyTHEbar/dragonscale/pkg/ids"
	"github.com/ZanzyTHEbar/dragonscale/pkg/memory"
)

const GetCompletedTasks = `-- name: GetCompletedTasks :many
SELECT id,
    agent_id,
    conversation_id,
    run_id,
    description,
    tokens_used,
    tool_calls,
    errors,
    user_corrections,
    completed,
    created_at
FROM task_completions
WHERE agent_id = ?1
	AND unixepoch(created_at) > unixepoch(?2)
	AND completed = 1
ORDER BY created_at ASC
`

type GetCompletedTasksParams struct {
	AgentID string      `db:"agent_id" json:"agent_id"`
	Since   interface{} `db:"since" json:"since"`
}

// Get tasks completed since the given time for RL processing
//
//	SELECT id,
//	    agent_id,
//	    conversation_id,
//	    run_id,
//	    description,
//	    tokens_used,
//	    tool_calls,
//	    errors,
//	    user_corrections,
//	    completed,
//	    created_at
//	FROM task_completions
//	WHERE agent_id = ?1
//		AND unixepoch(created_at) > unixepoch(?2)
//		AND completed = 1
//	ORDER BY created_at ASC
func (q *Queries) GetCompletedTasks(ctx context.Context, arg GetCompletedTasksParams) ([]TaskCompletion, error) {
	rows, err := q.db.QueryContext(ctx, GetCompletedTasks, arg.AgentID, arg.Since)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []TaskCompletion{}
	for rows.Next() {
		var i TaskCompletion
		if err := rows.Scan(
			&i.ID,
			&i.AgentID,
			&i.ConversationID,
			&i.RunID,
			&i.Description,
			&i.TokensUsed,
			&i.ToolCalls,
			&i.Errors,
			&i.UserCorrections,
			&i.Completed,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const GetHighTokenSessions = `-- name: GetHighTokenSessions :many
SELECT conversation_id as session_id,
    agent_id,
    SUM(COALESCE(tokens_used, 0)) as total_tokens,
    COUNT(*) as task_count
FROM task_completions
WHERE created_at > strftime('%Y-%m-%dT%H:%M:%fZ', 'now', '-24 hours')
GROUP BY conversation_id,
    agent_id
HAVING SUM(COALESCE(tokens_used, 0)) > ?1
ORDER BY total_tokens DESC
LIMIT ?2
`

type GetHighTokenSessionsParams struct {
	MinTokens *int64 `db:"min_tokens" json:"min_tokens"`
	Lim       int64  `db:"lim" json:"lim"`
}

type GetHighTokenSessionsRow struct {
	SessionID   ids.UUID `db:"session_id" json:"session_id"`
	AgentID     string   `db:"agent_id" json:"agent_id"`
	TotalTokens *float64 `db:"total_tokens" json:"total_tokens"`
	TaskCount   int64    `db:"task_count" json:"task_count"`
}

// Get sessions with high token usage grouped by conversation/agent
//
//	SELECT conversation_id as session_id,
//	    agent_id,
//	    SUM(COALESCE(tokens_used, 0)) as total_tokens,
//	    COUNT(*) as task_count
//	FROM task_completions
//	WHERE created_at > strftime('%Y-%m-%dT%H:%M:%fZ', 'now', '-24 hours')
//	GROUP BY conversation_id,
//	    agent_id
//	HAVING SUM(COALESCE(tokens_used, 0)) > ?1
//	ORDER BY total_tokens DESC
//	LIMIT ?2
func (q *Queries) GetHighTokenSessions(ctx context.Context, arg GetHighTokenSessionsParams) ([]GetHighTokenSessionsRow, error) {
	rows, err := q.db.QueryContext(ctx, GetHighTokenSessions, arg.MinTokens, arg.Lim)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []GetHighTokenSessionsRow{}
	for rows.Next() {
		var i GetHighTokenSessionsRow
		if err := rows.Scan(
			&i.SessionID,
			&i.AgentID,
			&i.TotalTokens,
			&i.TaskCount,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const GetMemoriesByRetrievalCount = `-- name: GetMemoriesByRetrievalCount :many
SELECT id,
    agent_id,
    session_key,
    role,
    sector,
    importance,
    salience,
    decay_rate,
    content,
    tags,
    rl_weight,
    rl_credit,
    self_report_score,
    task_retrieval_count,
    created_at,
    updated_at
FROM recall_items
WHERE agent_id = ?1
    AND suppressed_at IS NULL
ORDER BY task_retrieval_count DESC
LIMIT ?2
`

type GetMemoriesByRetrievalCountParams struct {
	AgentID string `db:"agent_id" json:"agent_id"`
	Lim     int64  `db:"lim" json:"lim"`
}

type GetMemoriesByRetrievalCountRow struct {
	ID                 ids.UUID      `db:"id" json:"id"`
	AgentID            string        `db:"agent_id" json:"agent_id"`
	SessionKey         string        `db:"session_key" json:"session_key"`
	Role               string        `db:"role" json:"role"`
	Sector             memory.Sector `db:"sector" json:"sector"`
	Importance         float64       `db:"importance" json:"importance"`
	Salience           float64       `db:"salience" json:"salience"`
	DecayRate          float64       `db:"decay_rate" json:"decay_rate"`
	Content            string        `db:"content" json:"content"`
	Tags               string        `db:"tags" json:"tags"`
	RlWeight           *float64      `db:"rl_weight" json:"rl_weight"`
	RlCredit           *float64      `db:"rl_credit" json:"rl_credit"`
	SelfReportScore    *int64        `db:"self_report_score" json:"self_report_score"`
	TaskRetrievalCount *int64        `db:"task_retrieval_count" json:"task_retrieval_count"`
	CreatedAt          time.Time     `db:"created_at" json:"created_at"`
	UpdatedAt          time.Time     `db:"updated_at" json:"updated_at"`
}

// Get memories ordered by their task retrieval count (for RL analysis)
//
//	SELECT id,
//	    agent_id,
//	    session_key,
//	    role,
//	    sector,
//	    importance,
//	    salience,
//	    decay_rate,
//	    content,
//	    tags,
//	    rl_weight,
//	    rl_credit,
//	    self_report_score,
//	    task_retrieval_count,
//	    created_at,
//	    updated_at
//	FROM recall_items
//	WHERE agent_id = ?1
//	    AND suppressed_at IS NULL
//	ORDER BY task_retrieval_count DESC
//	LIMIT ?2
func (q *Queries) GetMemoriesByRetrievalCount(ctx context.Context, arg GetMemoriesByRetrievalCountParams) ([]GetMemoriesByRetrievalCountRow, error) {
	rows, err := q.db.QueryContext(ctx, GetMemoriesByRetrievalCount, arg.AgentID, arg.Lim)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []GetMemoriesByRetrievalCountRow{}
	for rows.Next() {
		var i GetMemoriesByRetrievalCountRow
		if err := rows.Scan(
			&i.ID,
			&i.AgentID,
			&i.SessionKey,
			&i.Role,
			&i.Sector,
			&i.Importance,
			&i.Salience,
			&i.DecayRate,
			&i.Content,
			&i.Tags,
			&i.RlWeight,
			&i.RlCredit,
			&i.SelfReportScore,
			&i.TaskRetrievalCount,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const GetRetrievedMemories = `-- name: GetRetrievedMemories :many
SELECT tr.memory_id,
    tr.similarity,
    ri.self_report_score
FROM task_retrievals tr
    JOIN recall_items ri ON tr.memory_id = ri.id
WHERE tr.task_id = ?1
`

type GetRetrievedMemoriesParams struct {
	TaskID ids.UUID `db:"task_id" json:"task_id"`
}

type GetRetrievedMemoriesRow struct {
	MemoryID        ids.UUID `db:"memory_id" json:"memory_id"`
	Similarity      float64  `db:"similarity" json:"similarity"`
	SelfReportScore *int64   `db:"self_report_score" json:"self_report_score"`
}

// Get memories retrieved during a specific task with their self-report scores
//
//	SELECT tr.memory_id,
//	    tr.similarity,
//	    ri.self_report_score
//	FROM task_retrievals tr
//	    JOIN recall_items ri ON tr.memory_id = ri.id
//	WHERE tr.task_id = ?1
func (q *Queries) GetRetrievedMemories(ctx context.Context, arg GetRetrievedMemoriesParams) ([]GetRetrievedMemoriesRow, error) {
	rows, err := q.db.QueryContext(ctx, GetRetrievedMemories, arg.TaskID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []GetRetrievedMemoriesRow{}
	for rows.Next() {
		var i GetRetrievedMemoriesRow
		if err := rows.Scan(&i.MemoryID, &i.Similarity, &i.SelfReportScore); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const GetTaskBaseline = `-- name: GetTaskBaseline :one
SELECT agent_id,
    count,
    mean_tokens,
    mean_errors,
    mean_user_corrections,
    m2_tokens,
    m2_errors,
    m2_user_corrections,
    updated_at
FROM task_baselines
WHERE agent_id = ?1
LIMIT 1
`

type GetTaskBaselineParams struct {
	AgentID string `db:"agent_id" json:"agent_id"`
}

// RL (Reinforcement Learning) queries for Memelord integration
// Task baseline queries for per-agent performance statistics
// Get the baseline statistics for an agent
//
//	SELECT agent_id,
//	    count,
//	    mean_tokens,
//	    mean_errors,
//	    mean_user_corrections,
//	    m2_tokens,
//	    m2_errors,
//	    m2_user_corrections,
//	    updated_at
//	FROM task_baselines
//	WHERE agent_id = ?1
//	LIMIT 1
func (q *Queries) GetTaskBaseline(ctx context.Context, arg GetTaskBaselineParams) (TaskBaseline, error) {
	row := q.db.QueryRowContext(ctx, GetTaskBaseline, arg.AgentID)
	var i TaskBaseline
	err := row.Scan(
		&i.AgentID,
		&i.Count,
		&i.MeanTokens,
		&i.MeanErrors,
		&i.MeanUserCorrections,
		&i.M2Tokens,
		&i.M2Errors,
		&i.M2UserCorrections,
		&i.UpdatedAt,
	)
	return i, err
}

const IncrementTaskRetrievalCount = `-- name: IncrementTaskRetrievalCount :exec
UPDATE recall_items
SET task_retrieval_count = task_retrieval_count + 1,
    updated_at = datetime('now')
WHERE id = ?1
    AND agent_id = ?2
`

type IncrementTaskRetrievalCountParams struct {
	ID      ids.UUID `db:"id" json:"id"`
	AgentID string   `db:"agent_id" json:"agent_id"`
}

// Increment the task retrieval counter for a memory item
//
//	UPDATE recall_items
//	SET task_retrieval_count = task_retrieval_count + 1,
//	    updated_at = datetime('now')
//	WHERE id = ?1
//	    AND agent_id = ?2
func (q *Queries) IncrementTaskRetrievalCount(ctx context.Context, arg IncrementTaskRetrievalCountParams) error {
	_, err := q.db.ExecContext(ctx, IncrementTaskRetrievalCount, arg.ID, arg.AgentID)
	return err
}

const ListActiveAgents = `-- name: ListActiveAgents :many
SELECT DISTINCT agent_id
FROM task_completions
WHERE unixepoch(created_at) > unixepoch(?1)
ORDER BY agent_id
`

type ListActiveAgentsParams struct {
	Since interface{} `db:"since" json:"since"`
}

// Get all unique agent IDs that have completed tasks (for multi-agent processing)
//
//	SELECT DISTINCT agent_id
//	FROM task_completions
//	WHERE unixepoch(created_at) > unixepoch(?1)
//	ORDER BY agent_id
func (q *Queries) ListActiveAgents(ctx context.Context, arg ListActiveAgentsParams) ([]string, error) {
	rows, err := q.db.QueryContext(ctx, ListActiveAgents, arg.Since)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []string{}
	for rows.Next() {
		var agent_id string
		if err := rows.Scan(&agent_id); err != nil {
			return nil, err
		}
		items = append(items, agent_id)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const ListHighValueMemories = `-- name: ListHighValueMemories :many
SELECT id,
    agent_id,
    session_key,
    role,
    sector,
    importance,
    salience,
    decay_rate,
    content,
    tags,
    rl_weight,
    rl_credit,
    self_report_score,
    task_retrieval_count,
    created_at,
    updated_at
FROM recall_items
WHERE agent_id = ?1
    AND suppressed_at IS NULL
    AND (
        rl_credit > ?2
        OR rl_weight > ?3
    )
ORDER BY rl_credit DESC NULLS LAST
LIMIT ?4
`

type ListHighValueMemoriesParams struct {
	AgentID   string   `db:"agent_id" json:"agent_id"`
	MinCredit *float64 `db:"min_credit" json:"min_credit"`
	MinWeight *float64 `db:"min_weight" json:"min_weight"`
	Lim       int64    `db:"lim" json:"lim"`
}

type ListHighValueMemoriesRow struct {
	ID                 ids.UUID      `db:"id" json:"id"`
	AgentID            string        `db:"agent_id" json:"agent_id"`
	SessionKey         string        `db:"session_key" json:"session_key"`
	Role               string        `db:"role" json:"role"`
	Sector             memory.Sector `db:"sector" json:"sector"`
	Importance         float64       `db:"importance" json:"importance"`
	Salience           float64       `db:"salience" json:"salience"`
	DecayRate          float64       `db:"decay_rate" json:"decay_rate"`
	Content            string        `db:"content" json:"content"`
	Tags               string        `db:"tags" json:"tags"`
	RlWeight           *float64      `db:"rl_weight" json:"rl_weight"`
	RlCredit           *float64      `db:"rl_credit" json:"rl_credit"`
	SelfReportScore    *int64        `db:"self_report_score" json:"self_report_score"`
	TaskRetrievalCount *int64        `db:"task_retrieval_count" json:"task_retrieval_count"`
	CreatedAt          time.Time     `db:"created_at" json:"created_at"`
	UpdatedAt          time.Time     `db:"updated_at" json:"updated_at"`
}

// List memories with high RL weights (credits) for priority retention
//
//	SELECT id,
//	    agent_id,
//	    session_key,
//	    role,
//	    sector,
//	    importance,
//	    salience,
//	    decay_rate,
//	    content,
//	    tags,
//	    rl_weight,
//	    rl_credit,
//	    self_report_score,
//	    task_retrieval_count,
//	    created_at,
//	    updated_at
//	FROM recall_items
//	WHERE agent_id = ?1
//	    AND suppressed_at IS NULL
//	    AND (
//	        rl_credit > ?2
//	        OR rl_weight > ?3
//	    )
//	ORDER BY rl_credit DESC NULLS LAST
//	LIMIT ?4
func (q *Queries) ListHighValueMemories(ctx context.Context, arg ListHighValueMemoriesParams) ([]ListHighValueMemoriesRow, error) {
	rows, err := q.db.QueryContext(ctx, ListHighValueMemories,
		arg.AgentID,
		arg.MinCredit,
		arg.MinWeight,
		arg.Lim,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListHighValueMemoriesRow{}
	for rows.Next() {
		var i ListHighValueMemoriesRow
		if err := rows.Scan(
			&i.ID,
			&i.AgentID,
			&i.SessionKey,
			&i.Role,
			&i.Sector,
			&i.Importance,
			&i.Salience,
			&i.DecayRate,
			&i.Content,
			&i.Tags,
			&i.RlWeight,
			&i.RlCredit,
			&i.SelfReportScore,
			&i.TaskRetrievalCount,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const StoreTaskCompletion = `-- name: StoreTaskCompletion :one
INSERT INTO task_completions (
        id,
        agent_id,
        conversation_id,
        run_id,
        description,
        tokens_used,
        tool_calls,
        errors,
        user_corrections,
        completed
    )
VALUES (
        ?1,
        ?2,
        ?3,
        ?4,
        ?5,
        ?6,
        ?7,
        ?8,
        ?9,
        ?10
    )
RETURNING id,
    agent_id,
    conversation_id,
    run_id,
    description,
    tokens_used,
    tool_calls,
    errors,
    user_corrections,
    completed,
    created_at
`

type StoreTaskCompletionParams struct {
	ID              ids.UUID `db:"id" json:"id"`
	AgentID         string   `db:"agent_id" json:"agent_id"`
	ConversationID  ids.UUID `db:"conversation_id" json:"conversation_id"`
	RunID           ids.UUID `db:"run_id" json:"run_id"`
	Description     string   `db:"description" json:"description"`
	TokensUsed      *int64   `db:"tokens_used" json:"tokens_used"`
	ToolCalls       *int64   `db:"tool_calls" json:"tool_calls"`
	Errors          *int64   `db:"errors" json:"errors"`
	UserCorrections *int64   `db:"user_corrections" json:"user_corrections"`
	Completed       bool     `db:"completed" json:"completed"`
}

// Store a task completion record for RL analysis
//
//	INSERT INTO task_completions (
//	        id,
//	        agent_id,
//	        conversation_id,
//	        run_id,
//	        description,
//	        tokens_used,
//	        tool_calls,
//	        errors,
//	        user_corrections,
//	        completed
//	    )
//	VALUES (
//	        ?1,
//	        ?2,
//	        ?3,
//	        ?4,
//	        ?5,
//	        ?6,
//	        ?7,
//	        ?8,
//	        ?9,
//	        ?10
//	    )
//	RETURNING id,
//	    agent_id,
//	    conversation_id,
//	    run_id,
//	    description,
//	    tokens_used,
//	    tool_calls,
//	    errors,
//	    user_corrections,
//	    completed,
//	    created_at
func (q *Queries) StoreTaskCompletion(ctx context.Context, arg StoreTaskCompletionParams) (TaskCompletion, error) {
	row := q.db.QueryRowContext(ctx, StoreTaskCompletion,
		arg.ID,
		arg.AgentID,
		arg.ConversationID,
		arg.RunID,
		arg.Description,
		arg.TokensUsed,
		arg.ToolCalls,
		arg.Errors,
		arg.UserCorrections,
		arg.Completed,
	)
	var i TaskCompletion
	err := row.Scan(
		&i.ID,
		&i.AgentID,
		&i.ConversationID,
		&i.RunID,
		&i.Description,
		&i.TokensUsed,
		&i.ToolCalls,
		&i.Errors,
		&i.UserCorrections,
		&i.Completed,
		&i.CreatedAt,
	)
	return i, err
}

const StoreTaskRetrieval = `-- name: StoreTaskRetrieval :exec
INSERT INTO task_retrievals (id, task_id, memory_id, similarity)
VALUES (
        ?1,
        ?2,
        ?3,
        ?4
    ) ON CONFLICT (task_id, memory_id) DO
UPDATE
SET similarity = excluded.similarity
`

type StoreTaskRetrievalParams struct {
	ID         ids.UUID `db:"id" json:"id"`
	TaskID     ids.UUID `db:"task_id" json:"task_id"`
	MemoryID   ids.UUID `db:"memory_id" json:"memory_id"`
	Similarity float64  `db:"similarity" json:"similarity"`
}

// Store a memory retrieval record for a task
//
//	INSERT INTO task_retrievals (id, task_id, memory_id, similarity)
//	VALUES (
//	        ?1,
//	        ?2,
//	        ?3,
//	        ?4
//	    ) ON CONFLICT (task_id, memory_id) DO
//	UPDATE
//	SET similarity = excluded.similarity
func (q *Queries) StoreTaskRetrieval(ctx context.Context, arg StoreTaskRetrievalParams) error {
	_, err := q.db.ExecContext(ctx, StoreTaskRetrieval,
		arg.ID,
		arg.TaskID,
		arg.MemoryID,
		arg.Similarity,
	)
	return err
}

const UpdateMemorySelfReportScore = `-- name: UpdateMemorySelfReportScore :exec
UPDATE recall_items
SET self_report_score = ?1,
    updated_at = datetime('now')
WHERE id = ?2
    AND agent_id = ?3
`

type UpdateMemorySelfReportScoreParams struct {
	SelfReportScore *int64   `db:"self_report_score" json:"self_report_score"`
	ID              ids.UUID `db:"id" json:"id"`
	AgentID         string   `db:"agent_id" json:"agent_id"`
}

// Update the self-reported score for a memory item
//
//	UPDATE recall_items
//	SET self_report_score = ?1,
//	    updated_at = datetime('now')
//	WHERE id = ?2
//	    AND agent_id = ?3
func (q *Queries) UpdateMemorySelfReportScore(ctx context.Context, arg UpdateMemorySelfReportScoreParams) error {
	_, err := q.db.ExecContext(ctx, UpdateMemorySelfReportScore, arg.SelfReportScore, arg.ID, arg.AgentID)
	return err
}

const UpdateMemoryWeight = `-- name: UpdateMemoryWeight :exec
UPDATE recall_items
SET rl_weight = ?1,
    rl_credit = ?2,
    updated_at = datetime('now')
WHERE id = ?3
    AND agent_id = ?4
`

type UpdateMemoryWeightParams struct {
	RlWeight *float64 `db:"rl_weight" json:"rl_weight"`
	RlCredit *float64 `db:"rl_credit" json:"rl_credit"`
	ID       ids.UUID `db:"id" json:"id"`
	AgentID  string   `db:"agent_id" json:"agent_id"`
}

// Update the RL weight and credit for a specific memory item
//
//	UPDATE recall_items
//	SET rl_weight = ?1,
//	    rl_credit = ?2,
//	    updated_at = datetime('now')
//	WHERE id = ?3
//	    AND agent_id = ?4
func (q *Queries) UpdateMemoryWeight(ctx context.Context, arg UpdateMemoryWeightParams) error {
	_, err := q.db.ExecContext(ctx, UpdateMemoryWeight,
		arg.RlWeight,
		arg.RlCredit,
		arg.ID,
		arg.AgentID,
	)
	return err
}

const UpdateTaskBaseline = `-- name: UpdateTaskBaseline :exec
INSERT INTO task_baselines (
        agent_id,
        count,
        mean_tokens,
        mean_errors,
        mean_user_corrections,
        m2_tokens,
        m2_errors,
        m2_user_corrections,
        updated_at
    )
VALUES (
        ?1,
        ?2,
        ?3,
        ?4,
        ?5,
        ?6,
        ?7,
        ?8,
        datetime('now')
    ) ON CONFLICT (agent_id) DO
UPDATE
SET count = excluded.count,
    mean_tokens = excluded.mean_tokens,
    mean_errors = excluded.mean_errors,
    mean_user_corrections = excluded.mean_user_corrections,
    m2_tokens = excluded.m2_tokens,
    m2_errors = excluded.m2_errors,
    m2_user_corrections = excluded.m2_user_corrections,
    updated_at = excluded.updated_at
`

type UpdateTaskBaselineParams struct {
	AgentID             string   `db:"agent_id" json:"agent_id"`
	Count               *int64   `db:"count" json:"count"`
	MeanTokens          *int64   `db:"mean_tokens" json:"mean_tokens"`
	MeanErrors          *float64 `db:"mean_errors" json:"mean_errors"`
	MeanUserCorrections *float64 `db:"mean_user_corrections" json:"mean_user_corrections"`
	M2Tokens            *float64 `db:"m2_tokens" json:"m2_tokens"`
	M2Errors            *float64 `db:"m2_errors" json:"m2_errors"`
	M2UserCorrections   *float64 `db:"m2_user_corrections" json:"m2_user_corrections"`
}

// Insert or replace task baseline statistics for an agent
//
//	INSERT INTO task_baselines (
//	        agent_id,
//	        count,
//	        mean_tokens,
//	        mean_errors,
//	        mean_user_corrections,
//	        m2_tokens,
//	        m2_errors,
//	        m2_user_corrections,
//	        updated_at
//	    )
//	VALUES (
//	        ?1,
//	        ?2,
//	        ?3,
//	        ?4,
//	        ?5,
//	        ?6,
//	        ?7,
//	        ?8,
//	        datetime('now')
//	    ) ON CONFLICT (agent_id) DO
//	UPDATE
//	SET count = excluded.count,
//	    mean_tokens = excluded.mean_tokens,
//	    mean_errors = excluded.mean_errors,
//	    mean_user_corrections = excluded.mean_user_corrections,
//	    m2_tokens = excluded.m2_tokens,
//	    m2_errors = excluded.m2_errors,
//	    m2_user_corrections = excluded.m2_user_corrections,
//	    updated_at = excluded.updated_at
func (q *Queries) UpdateTaskBaseline(ctx context.Context, arg UpdateTaskBaselineParams) error {
	_, err := q.db.ExecContext(ctx, UpdateTaskBaseline,
		arg.AgentID,
		arg.Count,
		arg.MeanTokens,
		arg.MeanErrors,
		arg.MeanUserCorrections,
		arg.M2Tokens,
		arg.M2Errors,
		arg.M2UserCorrections,
	)
	return err
}
