// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: soft_delete.sql

package sqlc

import (
	"context"
	"time"

	"github.com/ZanzyTHEbar/dragonscale/pkg/ids"
	"github.com/ZanzyTHEbar/dragonscale/pkg/memory"
)

const HardDeleteArchivalChunks = `-- name: HardDeleteArchivalChunks :exec
DELETE FROM archival_chunks
WHERE recall_id = ?1
`

type HardDeleteArchivalChunksParams struct {
	RecallID ids.UUID `db:"recall_id" json:"recall_id"`
}

// Permanently deletes archival chunks for a recall item.
//
//	DELETE FROM archival_chunks
//	WHERE recall_id = ?1
func (q *Queries) HardDeleteArchivalChunks(ctx context.Context, arg HardDeleteArchivalChunksParams) error {
	_, err := q.db.ExecContext(ctx, HardDeleteArchivalChunks, arg.RecallID)
	return err
}

const HardDeleteChunk = `-- name: HardDeleteChunk :exec
DELETE FROM archival_chunks
WHERE id = ?1
`

type HardDeleteChunkParams struct {
	ID ids.UUID `db:"id" json:"id"`
}

// Permanently deletes a single archival chunk by ID.
//
//	DELETE FROM archival_chunks
//	WHERE id = ?1
func (q *Queries) HardDeleteChunk(ctx context.Context, arg HardDeleteChunkParams) error {
	_, err := q.db.ExecContext(ctx, HardDeleteChunk, arg.ID)
	return err
}

const HardDeleteRecallItem = `-- name: HardDeleteRecallItem :exec
DELETE FROM recall_items
WHERE id = ?1
    AND agent_id = ?2
`

type HardDeleteRecallItemParams struct {
	ID      ids.UUID `db:"id" json:"id"`
	AgentID string   `db:"agent_id" json:"agent_id"`
}

// Permanently deletes a recall item (after quarantine period).
//
//	DELETE FROM recall_items
//	WHERE id = ?1
//	    AND agent_id = ?2
func (q *Queries) HardDeleteRecallItem(ctx context.Context, arg HardDeleteRecallItemParams) error {
	_, err := q.db.ExecContext(ctx, HardDeleteRecallItem, arg.ID, arg.AgentID)
	return err
}

const ListQuarantinedArchivalChunks = `-- name: ListQuarantinedArchivalChunks :many
SELECT id,
    recall_id,
    chunk_index,
    content,
    embedding,
    source,
    hash,
    created_at,
    suppressed_at
FROM archival_chunks
WHERE suppressed_at IS NOT NULL
    AND suppressed_at < ?1
ORDER BY suppressed_at ASC
LIMIT ?2
`

type ListQuarantinedArchivalChunksParams struct {
	BeforeDate *time.Time `db:"before_date" json:"before_date"`
	Lim        int64      `db:"lim" json:"lim"`
}

// Returns archival chunks that have been soft-deleted and are
// eligible for permanent deletion.
//
//	SELECT id,
//	    recall_id,
//	    chunk_index,
//	    content,
//	    embedding,
//	    source,
//	    hash,
//	    created_at,
//	    suppressed_at
//	FROM archival_chunks
//	WHERE suppressed_at IS NOT NULL
//	    AND suppressed_at < ?1
//	ORDER BY suppressed_at ASC
//	LIMIT ?2
func (q *Queries) ListQuarantinedArchivalChunks(ctx context.Context, arg ListQuarantinedArchivalChunksParams) ([]ArchivalChunk, error) {
	rows, err := q.db.QueryContext(ctx, ListQuarantinedArchivalChunks, arg.BeforeDate, arg.Lim)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ArchivalChunk{}
	for rows.Next() {
		var i ArchivalChunk
		if err := rows.Scan(
			&i.ID,
			&i.RecallID,
			&i.ChunkIndex,
			&i.Content,
			&i.Embedding,
			&i.Source,
			&i.Hash,
			&i.CreatedAt,
			&i.SuppressedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const ListQuarantinedRecallItems = `-- name: ListQuarantinedRecallItems :many
SELECT id,
    agent_id,
    session_key,
    role,
    sector,
    importance,
    salience,
    decay_rate,
    content,
    tags,
    created_at,
    updated_at,
    suppressed_at
FROM recall_items
WHERE suppressed_at IS NOT NULL
    AND suppressed_at < ?1
ORDER BY suppressed_at ASC
LIMIT ?2
`

type ListQuarantinedRecallItemsParams struct {
	BeforeDate *time.Time `db:"before_date" json:"before_date"`
	Lim        int64      `db:"lim" json:"lim"`
}

type ListQuarantinedRecallItemsRow struct {
	ID           ids.UUID      `db:"id" json:"id"`
	AgentID      string        `db:"agent_id" json:"agent_id"`
	SessionKey   string        `db:"session_key" json:"session_key"`
	Role         string        `db:"role" json:"role"`
	Sector       memory.Sector `db:"sector" json:"sector"`
	Importance   float64       `db:"importance" json:"importance"`
	Salience     float64       `db:"salience" json:"salience"`
	DecayRate    float64       `db:"decay_rate" json:"decay_rate"`
	Content      string        `db:"content" json:"content"`
	Tags         string        `db:"tags" json:"tags"`
	CreatedAt    time.Time     `db:"created_at" json:"created_at"`
	UpdatedAt    time.Time     `db:"updated_at" json:"updated_at"`
	SuppressedAt *time.Time    `db:"suppressed_at" json:"suppressed_at"`
}

// Returns recall items that have been soft-deleted (suppressed) and are
// eligible for permanent deletion (older than quarantine period).
//
//	SELECT id,
//	    agent_id,
//	    session_key,
//	    role,
//	    sector,
//	    importance,
//	    salience,
//	    decay_rate,
//	    content,
//	    tags,
//	    created_at,
//	    updated_at,
//	    suppressed_at
//	FROM recall_items
//	WHERE suppressed_at IS NOT NULL
//	    AND suppressed_at < ?1
//	ORDER BY suppressed_at ASC
//	LIMIT ?2
func (q *Queries) ListQuarantinedRecallItems(ctx context.Context, arg ListQuarantinedRecallItemsParams) ([]ListQuarantinedRecallItemsRow, error) {
	rows, err := q.db.QueryContext(ctx, ListQuarantinedRecallItems, arg.BeforeDate, arg.Lim)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListQuarantinedRecallItemsRow{}
	for rows.Next() {
		var i ListQuarantinedRecallItemsRow
		if err := rows.Scan(
			&i.ID,
			&i.AgentID,
			&i.SessionKey,
			&i.Role,
			&i.Sector,
			&i.Importance,
			&i.Salience,
			&i.DecayRate,
			&i.Content,
			&i.Tags,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.SuppressedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const RestoreRecallItem = `-- name: RestoreRecallItem :exec
UPDATE recall_items
SET suppressed_at = NULL
WHERE id = ?1
    AND agent_id = ?2
`

type RestoreRecallItemParams struct {
	ID      ids.UUID `db:"id" json:"id"`
	AgentID string   `db:"agent_id" json:"agent_id"`
}

// Restores a soft-deleted recall item by clearing suppressed_at.
//
//	UPDATE recall_items
//	SET suppressed_at = NULL
//	WHERE id = ?1
//	    AND agent_id = ?2
func (q *Queries) RestoreRecallItem(ctx context.Context, arg RestoreRecallItemParams) error {
	_, err := q.db.ExecContext(ctx, RestoreRecallItem, arg.ID, arg.AgentID)
	return err
}

const SoftDeleteArchivalChunks = `-- name: SoftDeleteArchivalChunks :exec
UPDATE archival_chunks
SET suppressed_at = datetime('now')
WHERE recall_id = ?1
`

type SoftDeleteArchivalChunksParams struct {
	RecallID ids.UUID `db:"recall_id" json:"recall_id"`
}

// Sets suppressed_at for all chunks belonging to a recall item.
//
//	UPDATE archival_chunks
//	SET suppressed_at = datetime('now')
//	WHERE recall_id = ?1
func (q *Queries) SoftDeleteArchivalChunks(ctx context.Context, arg SoftDeleteArchivalChunksParams) error {
	_, err := q.db.ExecContext(ctx, SoftDeleteArchivalChunks, arg.RecallID)
	return err
}

const SoftDeleteRecallItem = `-- name: SoftDeleteRecallItem :exec
UPDATE recall_items
SET suppressed_at = datetime('now')
WHERE id = ?1
    AND agent_id = ?2
`

type SoftDeleteRecallItemParams struct {
	ID      ids.UUID `db:"id" json:"id"`
	AgentID string   `db:"agent_id" json:"agent_id"`
}

// Soft delete queries (T2.4: quarantine before permanent deletion)
// Sets suppressed_at for a recall item instead of permanently deleting it.
//
//	UPDATE recall_items
//	SET suppressed_at = datetime('now')
//	WHERE id = ?1
//	    AND agent_id = ?2
func (q *Queries) SoftDeleteRecallItem(ctx context.Context, arg SoftDeleteRecallItemParams) error {
	_, err := q.db.ExecContext(ctx, SoftDeleteRecallItem, arg.ID, arg.AgentID)
	return err
}
