// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: summaries.sql

package sqlc

import (
	"context"

	"github.com/sipeed/picoclaw/pkg/ids"
)

const InsertSummary = `-- name: InsertSummary :exec
INSERT INTO memory_summaries (
        id,
        agent_id,
        session_key,
        content,
        from_msg_idx,
        to_msg_idx,
        created_at
    )
VALUES (
        ?1,
        ?2,
        ?3,
        ?4,
        ?5,
        ?6,
        datetime('now')
    )
`

type InsertSummaryParams struct {
	ID         ids.UUID `json:"id"`
	AgentID    string   `json:"agent_id"`
	SessionKey string   `json:"session_key"`
	Content    string   `json:"content"`
	FromMsgIdx int64    `json:"from_msg_idx"`
	ToMsgIdx   int64    `json:"to_msg_idx"`
}

// Memory Summary queries
//
//	INSERT INTO memory_summaries (
//	        id,
//	        agent_id,
//	        session_key,
//	        content,
//	        from_msg_idx,
//	        to_msg_idx,
//	        created_at
//	    )
//	VALUES (
//	        ?1,
//	        ?2,
//	        ?3,
//	        ?4,
//	        ?5,
//	        ?6,
//	        datetime('now')
//	    )
func (q *Queries) InsertSummary(ctx context.Context, arg InsertSummaryParams) error {
	_, err := q.db.ExecContext(ctx, InsertSummary,
		arg.ID,
		arg.AgentID,
		arg.SessionKey,
		arg.Content,
		arg.FromMsgIdx,
		arg.ToMsgIdx,
	)
	return err
}

const ListSummaries = `-- name: ListSummaries :many
SELECT id,
    agent_id,
    session_key,
    content,
    from_msg_idx,
    to_msg_idx,
    created_at
FROM memory_summaries
WHERE agent_id = ?1
    AND (
        session_key = ?2
        OR ?2 = ''
    )
ORDER BY created_at DESC
LIMIT ?3
`

type ListSummariesParams struct {
	AgentID    string `json:"agent_id"`
	SessionKey string `json:"session_key"`
	Lim        int64  `json:"lim"`
}

// ListSummaries
//
//	SELECT id,
//	    agent_id,
//	    session_key,
//	    content,
//	    from_msg_idx,
//	    to_msg_idx,
//	    created_at
//	FROM memory_summaries
//	WHERE agent_id = ?1
//	    AND (
//	        session_key = ?2
//	        OR ?2 = ''
//	    )
//	ORDER BY created_at DESC
//	LIMIT ?3
func (q *Queries) ListSummaries(ctx context.Context, arg ListSummariesParams) ([]MemorySummary, error) {
	rows, err := q.db.QueryContext(ctx, ListSummaries, arg.AgentID, arg.SessionKey, arg.Lim)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []MemorySummary{}
	for rows.Next() {
		var i MemorySummary
		if err := rows.Scan(
			&i.ID,
			&i.AgentID,
			&i.SessionKey,
			&i.Content,
			&i.FromMsgIdx,
			&i.ToMsgIdx,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
