// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: summaries.sql

package sqlc

import (
	"context"

	"github.com/ZanzyTHEbar/dragonscale/pkg/ids"
)

const InsertSummary = `-- name: InsertSummary :one
INSERT INTO memory_summaries (
        id,
        agent_id,
        session_key,
        content,
        from_msg_idx,
        to_msg_idx,
        created_at
    )
VALUES (
        ?1,
        ?2,
        ?3,
        ?4,
        ?5,
        ?6,
        datetime('now')
    )
RETURNING id, agent_id, session_key, content, from_msg_idx, to_msg_idx, created_at
`

type InsertSummaryParams struct {
	ID         ids.UUID `db:"id" json:"id"`
	AgentID    string   `db:"agent_id" json:"agent_id"`
	SessionKey string   `db:"session_key" json:"session_key"`
	Content    string   `db:"content" json:"content"`
	FromMsgIdx int64    `db:"from_msg_idx" json:"from_msg_idx"`
	ToMsgIdx   int64    `db:"to_msg_idx" json:"to_msg_idx"`
}

// Memory Summary queries
//
//	INSERT INTO memory_summaries (
//	        id,
//	        agent_id,
//	        session_key,
//	        content,
//	        from_msg_idx,
//	        to_msg_idx,
//	        created_at
//	    )
//	VALUES (
//	        ?1,
//	        ?2,
//	        ?3,
//	        ?4,
//	        ?5,
//	        ?6,
//	        datetime('now')
//	    )
//	RETURNING id, agent_id, session_key, content, from_msg_idx, to_msg_idx, created_at
func (q *Queries) InsertSummary(ctx context.Context, arg InsertSummaryParams) (MemorySummary, error) {
	row := q.db.QueryRowContext(ctx, InsertSummary,
		arg.ID,
		arg.AgentID,
		arg.SessionKey,
		arg.Content,
		arg.FromMsgIdx,
		arg.ToMsgIdx,
	)
	var i MemorySummary
	err := row.Scan(
		&i.ID,
		&i.AgentID,
		&i.SessionKey,
		&i.Content,
		&i.FromMsgIdx,
		&i.ToMsgIdx,
		&i.CreatedAt,
	)
	return i, err
}

const ListSummaries = `-- name: ListSummaries :many
SELECT id,
    agent_id,
    session_key,
    content,
    from_msg_idx,
    to_msg_idx,
    created_at
FROM memory_summaries
WHERE agent_id = ?1
    AND (
        session_key = ?2
        OR ?2 = ''
    )
ORDER BY created_at DESC
LIMIT ?3
`

type ListSummariesParams struct {
	AgentID    string `db:"agent_id" json:"agent_id"`
	SessionKey string `db:"session_key" json:"session_key"`
	Lim        int64  `db:"lim" json:"lim"`
}

// ListSummaries
//
//	SELECT id,
//	    agent_id,
//	    session_key,
//	    content,
//	    from_msg_idx,
//	    to_msg_idx,
//	    created_at
//	FROM memory_summaries
//	WHERE agent_id = ?1
//	    AND (
//	        session_key = ?2
//	        OR ?2 = ''
//	    )
//	ORDER BY created_at DESC
//	LIMIT ?3
func (q *Queries) ListSummaries(ctx context.Context, arg ListSummariesParams) ([]MemorySummary, error) {
	rows, err := q.db.QueryContext(ctx, ListSummaries, arg.AgentID, arg.SessionKey, arg.Lim)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []MemorySummary{}
	for rows.Next() {
		var i MemorySummary
		if err := rows.Scan(
			&i.ID,
			&i.AgentID,
			&i.SessionKey,
			&i.Content,
			&i.FromMsgIdx,
			&i.ToMsgIdx,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
