// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: working_context.sql

package sqlc

import (
	"context"
)

const GetWorkingContext = `-- name: GetWorkingContext :one
SELECT agent_id,
    session_key,
    content,
    updated_at
FROM working_context
WHERE agent_id = ?1
    AND session_key = ?2
LIMIT 1
`

type GetWorkingContextParams struct {
	AgentID    string `db:"agent_id" json:"agent_id"`
	SessionKey string `db:"session_key" json:"session_key"`
}

// Working Context queries
//
//	SELECT agent_id,
//	    session_key,
//	    content,
//	    updated_at
//	FROM working_context
//	WHERE agent_id = ?1
//	    AND session_key = ?2
//	LIMIT 1
func (q *Queries) GetWorkingContext(ctx context.Context, arg GetWorkingContextParams) (WorkingContext, error) {
	row := q.db.QueryRowContext(ctx, GetWorkingContext, arg.AgentID, arg.SessionKey)
	var i WorkingContext
	err := row.Scan(
		&i.AgentID,
		&i.SessionKey,
		&i.Content,
		&i.UpdatedAt,
	)
	return i, err
}

const UpsertWorkingContext = `-- name: UpsertWorkingContext :one
INSERT INTO working_context (agent_id, session_key, content, updated_at)
VALUES (
        ?1,
        ?2,
        ?3,
        datetime('now')
    ) ON CONFLICT (agent_id, session_key) DO
UPDATE
SET content = excluded.content,
    updated_at = excluded.updated_at
RETURNING agent_id, session_key, content, updated_at
`

type UpsertWorkingContextParams struct {
	AgentID    string `db:"agent_id" json:"agent_id"`
	SessionKey string `db:"session_key" json:"session_key"`
	Content    string `db:"content" json:"content"`
}

// UpsertWorkingContext
//
//	INSERT INTO working_context (agent_id, session_key, content, updated_at)
//	VALUES (
//	        ?1,
//	        ?2,
//	        ?3,
//	        datetime('now')
//	    ) ON CONFLICT (agent_id, session_key) DO
//	UPDATE
//	SET content = excluded.content,
//	    updated_at = excluded.updated_at
//	RETURNING agent_id, session_key, content, updated_at
func (q *Queries) UpsertWorkingContext(ctx context.Context, arg UpsertWorkingContextParams) (WorkingContext, error) {
	row := q.db.QueryRowContext(ctx, UpsertWorkingContext, arg.AgentID, arg.SessionKey, arg.Content)
	var i WorkingContext
	err := row.Scan(
		&i.AgentID,
		&i.SessionKey,
		&i.Content,
		&i.UpdatedAt,
	)
	return i, err
}
