// Code generated by the FlatBuffers compiler. DO NOT EDIT.

package itrfb

import "strconv"

type CmdType int8

const (
	CmdTypeNONE       CmdType = 0
	CmdTypePeek       CmdType = 1
	CmdTypeGrep       CmdType = 2
	CmdTypePartition  CmdType = 3
	CmdTypeRecurse    CmdType = 4
	CmdTypeToolExec   CmdType = 5
	CmdTypeExecWasm   CmdType = 6
	CmdTypeFinal      CmdType = 7
	CmdTypeToolSearch CmdType = 8
	CmdTypeCodeExec   CmdType = 9
	CmdTypeDAGPlan    CmdType = 10
)

var EnumNamesCmdType = map[CmdType]string{
	CmdTypeNONE:       "NONE",
	CmdTypePeek:       "Peek",
	CmdTypeGrep:       "Grep",
	CmdTypePartition:  "Partition",
	CmdTypeRecurse:    "Recurse",
	CmdTypeToolExec:   "ToolExec",
	CmdTypeExecWasm:   "ExecWasm",
	CmdTypeFinal:      "Final",
	CmdTypeToolSearch: "ToolSearch",
	CmdTypeCodeExec:   "CodeExec",
	CmdTypeDAGPlan:    "DAGPlan",
}

var EnumValuesCmdType = map[string]CmdType{
	"NONE":       CmdTypeNONE,
	"Peek":       CmdTypePeek,
	"Grep":       CmdTypeGrep,
	"Partition":  CmdTypePartition,
	"Recurse":    CmdTypeRecurse,
	"ToolExec":   CmdTypeToolExec,
	"ExecWasm":   CmdTypeExecWasm,
	"Final":      CmdTypeFinal,
	"ToolSearch": CmdTypeToolSearch,
	"CodeExec":   CmdTypeCodeExec,
	"DAGPlan":    CmdTypeDAGPlan,
}

func (v CmdType) String() string {
	if s, ok := EnumNamesCmdType[v]; ok {
		return s
	}
	return "CmdType(" + strconv.FormatInt(int64(v), 10) + ")"
}
