// Code generated by the FlatBuffers compiler. DO NOT EDIT.

package itrfb

import "strconv"

type CommandPayload byte

const (
	CommandPayloadNONE       CommandPayload = 0
	CommandPayloadPeek       CommandPayload = 1
	CommandPayloadGrep       CommandPayload = 2
	CommandPayloadPartition  CommandPayload = 3
	CommandPayloadRecurse    CommandPayload = 4
	CommandPayloadToolExec   CommandPayload = 5
	CommandPayloadExecWasm   CommandPayload = 6
	CommandPayloadFinal      CommandPayload = 7
	CommandPayloadToolSearch CommandPayload = 8
	CommandPayloadCodeExec   CommandPayload = 9
)

var EnumNamesCommandPayload = map[CommandPayload]string{
	CommandPayloadNONE:       "NONE",
	CommandPayloadPeek:       "Peek",
	CommandPayloadGrep:       "Grep",
	CommandPayloadPartition:  "Partition",
	CommandPayloadRecurse:    "Recurse",
	CommandPayloadToolExec:   "ToolExec",
	CommandPayloadExecWasm:   "ExecWasm",
	CommandPayloadFinal:      "Final",
	CommandPayloadToolSearch: "ToolSearch",
	CommandPayloadCodeExec:   "CodeExec",
}

var EnumValuesCommandPayload = map[string]CommandPayload{
	"NONE":       CommandPayloadNONE,
	"Peek":       CommandPayloadPeek,
	"Grep":       CommandPayloadGrep,
	"Partition":  CommandPayloadPartition,
	"Recurse":    CommandPayloadRecurse,
	"ToolExec":   CommandPayloadToolExec,
	"ExecWasm":   CommandPayloadExecWasm,
	"Final":      CommandPayloadFinal,
	"ToolSearch": CommandPayloadToolSearch,
	"CodeExec":   CommandPayloadCodeExec,
}

func (v CommandPayload) String() string {
	if s, ok := EnumNamesCommandPayload[v]; ok {
		return s
	}
	return "CommandPayload(" + strconv.FormatInt(int64(v), 10) + ")"
}
