// Code generated by the FlatBuffers compiler. DO NOT EDIT.

package itrfb

import (
	flatbuffers "github.com/google/flatbuffers/go"
)

type DAGNode struct {
	_tab flatbuffers.Table
}

func GetRootAsDAGNode(buf []byte, offset flatbuffers.UOffsetT) *DAGNode {
	n := flatbuffers.GetUOffsetT(buf[offset:])
	x := &DAGNode{}
	x.Init(buf, n+offset)
	return x
}

func FinishDAGNodeBuffer(builder *flatbuffers.Builder, offset flatbuffers.UOffsetT) {
	builder.Finish(offset)
}

func GetSizePrefixedRootAsDAGNode(buf []byte, offset flatbuffers.UOffsetT) *DAGNode {
	n := flatbuffers.GetUOffsetT(buf[offset+flatbuffers.SizeUint32:])
	x := &DAGNode{}
	x.Init(buf, n+offset+flatbuffers.SizeUint32)
	return x
}

func FinishSizePrefixedDAGNodeBuffer(builder *flatbuffers.Builder, offset flatbuffers.UOffsetT) {
	builder.FinishSizePrefixed(offset)
}

func (rcv *DAGNode) Init(buf []byte, i flatbuffers.UOffsetT) {
	rcv._tab.Bytes = buf
	rcv._tab.Pos = i
}

func (rcv *DAGNode) Table() flatbuffers.Table {
	return rcv._tab
}

func (rcv *DAGNode) Id() []byte {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(4))
	if o != 0 {
		return rcv._tab.ByteVector(o + rcv._tab.Pos)
	}
	return nil
}

func (rcv *DAGNode) NodeType() CmdType {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(6))
	if o != 0 {
		return CmdType(rcv._tab.GetInt8(o + rcv._tab.Pos))
	}
	return 0
}

func (rcv *DAGNode) MutateNodeType(n CmdType) bool {
	return rcv._tab.MutateInt8Slot(6, int8(n))
}

func (rcv *DAGNode) PayloadType() CommandPayload {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(8))
	if o != 0 {
		return CommandPayload(rcv._tab.GetByte(o + rcv._tab.Pos))
	}
	return 0
}

func (rcv *DAGNode) MutatePayloadType(n CommandPayload) bool {
	return rcv._tab.MutateByteSlot(8, byte(n))
}

func (rcv *DAGNode) Payload(obj *flatbuffers.Table) bool {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(10))
	if o != 0 {
		rcv._tab.Union(obj, o)
		return true
	}
	return false
}

func (rcv *DAGNode) DependsOn(j int) []byte {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(12))
	if o != 0 {
		a := rcv._tab.Vector(o)
		return rcv._tab.ByteVector(a + flatbuffers.UOffsetT(j*4))
	}
	return nil
}

func (rcv *DAGNode) DependsOnLength() int {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(12))
	if o != 0 {
		return rcv._tab.VectorLen(o)
	}
	return 0
}

func DAGNodeStart(builder *flatbuffers.Builder) {
	builder.StartObject(5)
}
func DAGNodeAddId(builder *flatbuffers.Builder, id flatbuffers.UOffsetT) {
	builder.PrependUOffsetTSlot(0, flatbuffers.UOffsetT(id), 0)
}
func DAGNodeAddNodeType(builder *flatbuffers.Builder, nodeType CmdType) {
	builder.PrependInt8Slot(1, int8(nodeType), 0)
}
func DAGNodeAddPayloadType(builder *flatbuffers.Builder, payloadType CommandPayload) {
	builder.PrependByteSlot(2, byte(payloadType), 0)
}
func DAGNodeAddPayload(builder *flatbuffers.Builder, payload flatbuffers.UOffsetT) {
	builder.PrependUOffsetTSlot(3, flatbuffers.UOffsetT(payload), 0)
}
func DAGNodeAddDependsOn(builder *flatbuffers.Builder, dependsOn flatbuffers.UOffsetT) {
	builder.PrependUOffsetTSlot(4, flatbuffers.UOffsetT(dependsOn), 0)
}
func DAGNodeStartDependsOnVector(builder *flatbuffers.Builder, numElems int) flatbuffers.UOffsetT {
	return builder.StartVector(4, numElems, 4)
}
func DAGNodeEnd(builder *flatbuffers.Builder) flatbuffers.UOffsetT {
	return builder.EndObject()
}
