// Code generated by the FlatBuffers compiler. DO NOT EDIT.

package itrfb

import (
	flatbuffers "github.com/google/flatbuffers/go"
)

type DAGPlan struct {
	_tab flatbuffers.Table
}

func GetRootAsDAGPlan(buf []byte, offset flatbuffers.UOffsetT) *DAGPlan {
	n := flatbuffers.GetUOffsetT(buf[offset:])
	x := &DAGPlan{}
	x.Init(buf, n+offset)
	return x
}

func GetSizePrefixedRootAsDAGPlan(buf []byte, offset flatbuffers.UOffsetT) *DAGPlan {
	n := flatbuffers.GetUOffsetT(buf[offset+flatbuffers.SizeUint32:])
	x := &DAGPlan{}
	x.Init(buf, n+offset+flatbuffers.SizeUint32)
	return x
}

func (rcv *DAGPlan) Init(buf []byte, i flatbuffers.UOffsetT) {
	rcv._tab.Bytes = buf
	rcv._tab.Pos = i
}

func (rcv *DAGPlan) Table() flatbuffers.Table {
	return rcv._tab
}

func (rcv *DAGPlan) Nodes(obj *DAGNode, j int) bool {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(4))
	if o != 0 {
		x := rcv._tab.Vector(o)
		x += flatbuffers.UOffsetT(j) * 4
		x = rcv._tab.Indirect(x)
		obj.Init(rcv._tab.Bytes, x)
		return true
	}
	return false
}

func (rcv *DAGPlan) NodesLength() int {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(4))
	if o != 0 {
		return rcv._tab.VectorLen(o)
	}
	return 0
}

func (rcv *DAGPlan) MaxParallel() byte {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(6))
	if o != 0 {
		return rcv._tab.GetByte(o + rcv._tab.Pos)
	}
	return 0
}

func (rcv *DAGPlan) MutateMaxParallel(n byte) bool {
	return rcv._tab.MutateByteSlot(6, n)
}

func (rcv *DAGPlan) TokenBudget() uint32 {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(8))
	if o != 0 {
		return rcv._tab.GetUint32(o + rcv._tab.Pos)
	}
	return 0
}

func (rcv *DAGPlan) MutateTokenBudget(n uint32) bool {
	return rcv._tab.MutateUint32Slot(8, n)
}

func (rcv *DAGPlan) JoinerQuery() []byte {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(10))
	if o != 0 {
		return rcv._tab.ByteVector(o + rcv._tab.Pos)
	}
	return nil
}

func DAGPlanStart(builder *flatbuffers.Builder) {
	builder.StartObject(4)
}
func DAGPlanAddNodes(builder *flatbuffers.Builder, nodes flatbuffers.UOffsetT) {
	builder.PrependUOffsetTSlot(0, flatbuffers.UOffsetT(nodes), 0)
}
func DAGPlanStartNodesVector(builder *flatbuffers.Builder, numElems int) flatbuffers.UOffsetT {
	return builder.StartVector(4, numElems, 4)
}
func DAGPlanAddMaxParallel(builder *flatbuffers.Builder, maxParallel byte) {
	builder.PrependByteSlot(1, maxParallel, 0)
}
func DAGPlanAddTokenBudget(builder *flatbuffers.Builder, tokenBudget uint32) {
	builder.PrependUint32Slot(2, tokenBudget, 0)
}
func DAGPlanAddJoinerQuery(builder *flatbuffers.Builder, joinerQuery flatbuffers.UOffsetT) {
	builder.PrependUOffsetTSlot(3, flatbuffers.UOffsetT(joinerQuery), 0)
}
func DAGPlanEnd(builder *flatbuffers.Builder) flatbuffers.UOffsetT {
	return builder.EndObject()
}
