// Code generated by the FlatBuffers compiler. DO NOT EDIT.

package itrfb

import (
	flatbuffers "github.com/google/flatbuffers/go"
)

type Final struct {
	_tab flatbuffers.Table
}

func GetRootAsFinal(buf []byte, offset flatbuffers.UOffsetT) *Final {
	n := flatbuffers.GetUOffsetT(buf[offset:])
	x := &Final{}
	x.Init(buf, n+offset)
	return x
}

func GetSizePrefixedRootAsFinal(buf []byte, offset flatbuffers.UOffsetT) *Final {
	n := flatbuffers.GetUOffsetT(buf[offset+flatbuffers.SizeUint32:])
	x := &Final{}
	x.Init(buf, n+offset+flatbuffers.SizeUint32)
	return x
}

func (rcv *Final) Init(buf []byte, i flatbuffers.UOffsetT) {
	rcv._tab.Bytes = buf
	rcv._tab.Pos = i
}

func (rcv *Final) Table() flatbuffers.Table {
	return rcv._tab
}

func (rcv *Final) Answer() []byte {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(4))
	if o != 0 {
		return rcv._tab.ByteVector(o + rcv._tab.Pos)
	}
	return nil
}

func (rcv *Final) VarName() []byte {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(6))
	if o != 0 {
		return rcv._tab.ByteVector(o + rcv._tab.Pos)
	}
	return nil
}

func FinalStart(builder *flatbuffers.Builder) {
	builder.StartObject(2)
}
func FinalAddAnswer(builder *flatbuffers.Builder, answer flatbuffers.UOffsetT) {
	builder.PrependUOffsetTSlot(0, flatbuffers.UOffsetT(answer), 0)
}
func FinalAddVarName(builder *flatbuffers.Builder, varName flatbuffers.UOffsetT) {
	builder.PrependUOffsetTSlot(1, flatbuffers.UOffsetT(varName), 0)
}
func FinalEnd(builder *flatbuffers.Builder) flatbuffers.UOffsetT {
	return builder.EndObject()
}
