// Code generated by the FlatBuffers compiler. DO NOT EDIT.

package itrfb

import (
	flatbuffers "github.com/google/flatbuffers/go"
)

type Grep struct {
	_tab flatbuffers.Table
}

func GetRootAsGrep(buf []byte, offset flatbuffers.UOffsetT) *Grep {
	n := flatbuffers.GetUOffsetT(buf[offset:])
	x := &Grep{}
	x.Init(buf, n+offset)
	return x
}

func GetSizePrefixedRootAsGrep(buf []byte, offset flatbuffers.UOffsetT) *Grep {
	n := flatbuffers.GetUOffsetT(buf[offset+flatbuffers.SizeUint32:])
	x := &Grep{}
	x.Init(buf, n+offset+flatbuffers.SizeUint32)
	return x
}

func (rcv *Grep) Init(buf []byte, i flatbuffers.UOffsetT) {
	rcv._tab.Bytes = buf
	rcv._tab.Pos = i
}

func (rcv *Grep) Table() flatbuffers.Table {
	return rcv._tab
}

func (rcv *Grep) Pattern() []byte {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(4))
	if o != 0 {
		return rcv._tab.ByteVector(o + rcv._tab.Pos)
	}
	return nil
}

func (rcv *Grep) MaxMatches() uint32 {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(6))
	if o != 0 {
		return rcv._tab.GetUint32(o + rcv._tab.Pos)
	}
	return 50
}

func (rcv *Grep) MutateMaxMatches(n uint32) bool {
	return rcv._tab.MutateUint32Slot(6, n)
}

func (rcv *Grep) CaseInsensitive() bool {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(8))
	if o != 0 {
		return rcv._tab.GetBool(o + rcv._tab.Pos)
	}
	return false
}

func (rcv *Grep) MutateCaseInsensitive(n bool) bool {
	return rcv._tab.MutateBoolSlot(8, n)
}

func GrepStart(builder *flatbuffers.Builder) {
	builder.StartObject(3)
}
func GrepAddPattern(builder *flatbuffers.Builder, pattern flatbuffers.UOffsetT) {
	builder.PrependUOffsetTSlot(0, flatbuffers.UOffsetT(pattern), 0)
}
func GrepAddMaxMatches(builder *flatbuffers.Builder, maxMatches uint32) {
	builder.PrependUint32Slot(1, maxMatches, 50)
}
func GrepAddCaseInsensitive(builder *flatbuffers.Builder, caseInsensitive bool) {
	builder.PrependBoolSlot(2, caseInsensitive, false)
}
func GrepEnd(builder *flatbuffers.Builder) flatbuffers.UOffsetT {
	return builder.EndObject()
}
