// Code generated by the FlatBuffers compiler. DO NOT EDIT.

package itrfb

import (
	flatbuffers "github.com/google/flatbuffers/go"
)

type Partition struct {
	_tab flatbuffers.Table
}

func GetRootAsPartition(buf []byte, offset flatbuffers.UOffsetT) *Partition {
	n := flatbuffers.GetUOffsetT(buf[offset:])
	x := &Partition{}
	x.Init(buf, n+offset)
	return x
}

func GetSizePrefixedRootAsPartition(buf []byte, offset flatbuffers.UOffsetT) *Partition {
	n := flatbuffers.GetUOffsetT(buf[offset+flatbuffers.SizeUint32:])
	x := &Partition{}
	x.Init(buf, n+offset+flatbuffers.SizeUint32)
	return x
}

func (rcv *Partition) Init(buf []byte, i flatbuffers.UOffsetT) {
	rcv._tab.Bytes = buf
	rcv._tab.Pos = i
}

func (rcv *Partition) Table() flatbuffers.Table {
	return rcv._tab
}

func (rcv *Partition) K() uint32 {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(4))
	if o != 0 {
		return rcv._tab.GetUint32(o + rcv._tab.Pos)
	}
	return 4
}

func (rcv *Partition) MutateK(n uint32) bool {
	return rcv._tab.MutateUint32Slot(4, n)
}

func (rcv *Partition) Method() []byte {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(6))
	if o != 0 {
		return rcv._tab.ByteVector(o + rcv._tab.Pos)
	}
	return nil
}

func (rcv *Partition) Overlap() uint32 {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(8))
	if o != 0 {
		return rcv._tab.GetUint32(o + rcv._tab.Pos)
	}
	return 0
}

func (rcv *Partition) MutateOverlap(n uint32) bool {
	return rcv._tab.MutateUint32Slot(8, n)
}

func (rcv *Partition) Semantic() bool {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(10))
	if o != 0 {
		return rcv._tab.GetBool(o + rcv._tab.Pos)
	}
	return false
}

func (rcv *Partition) MutateSemantic(n bool) bool {
	return rcv._tab.MutateBoolSlot(10, n)
}

func PartitionStart(builder *flatbuffers.Builder) {
	builder.StartObject(4)
}
func PartitionAddK(builder *flatbuffers.Builder, k uint32) {
	builder.PrependUint32Slot(0, k, 4)
}
func PartitionAddMethod(builder *flatbuffers.Builder, method flatbuffers.UOffsetT) {
	builder.PrependUOffsetTSlot(1, flatbuffers.UOffsetT(method), 0)
}
func PartitionAddOverlap(builder *flatbuffers.Builder, overlap uint32) {
	builder.PrependUint32Slot(2, overlap, 0)
}
func PartitionAddSemantic(builder *flatbuffers.Builder, semantic bool) {
	builder.PrependBoolSlot(3, semantic, false)
}
func PartitionEnd(builder *flatbuffers.Builder) flatbuffers.UOffsetT {
	return builder.EndObject()
}
