// Code generated by the FlatBuffers compiler. DO NOT EDIT.

package itrfb

import (
	flatbuffers "github.com/google/flatbuffers/go"
)

type Peek struct {
	_tab flatbuffers.Table
}

func GetRootAsPeek(buf []byte, offset flatbuffers.UOffsetT) *Peek {
	n := flatbuffers.GetUOffsetT(buf[offset:])
	x := &Peek{}
	x.Init(buf, n+offset)
	return x
}

func GetSizePrefixedRootAsPeek(buf []byte, offset flatbuffers.UOffsetT) *Peek {
	n := flatbuffers.GetUOffsetT(buf[offset+flatbuffers.SizeUint32:])
	x := &Peek{}
	x.Init(buf, n+offset+flatbuffers.SizeUint32)
	return x
}

func (rcv *Peek) Init(buf []byte, i flatbuffers.UOffsetT) {
	rcv._tab.Bytes = buf
	rcv._tab.Pos = i
}

func (rcv *Peek) Table() flatbuffers.Table {
	return rcv._tab
}

func (rcv *Peek) Start() uint64 {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(4))
	if o != 0 {
		return rcv._tab.GetUint64(o + rcv._tab.Pos)
	}
	return 0
}

func (rcv *Peek) MutateStart(n uint64) bool {
	return rcv._tab.MutateUint64Slot(4, n)
}

func (rcv *Peek) Length() uint32 {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(6))
	if o != 0 {
		return rcv._tab.GetUint32(o + rcv._tab.Pos)
	}
	return 0
}

func (rcv *Peek) MutateLength(n uint32) bool {
	return rcv._tab.MutateUint32Slot(6, n)
}

func PeekStart(builder *flatbuffers.Builder) {
	builder.StartObject(2)
}
func PeekAddStart(builder *flatbuffers.Builder, start uint64) {
	builder.PrependUint64Slot(0, start, 0)
}
func PeekAddLength(builder *flatbuffers.Builder, length uint32) {
	builder.PrependUint32Slot(1, length, 0)
}
func PeekEnd(builder *flatbuffers.Builder) flatbuffers.UOffsetT {
	return builder.EndObject()
}
