// Code generated by the FlatBuffers compiler. DO NOT EDIT.

package itrfb

import (
	flatbuffers "github.com/google/flatbuffers/go"
)

type Recurse struct {
	_tab flatbuffers.Table
}

func GetRootAsRecurse(buf []byte, offset flatbuffers.UOffsetT) *Recurse {
	n := flatbuffers.GetUOffsetT(buf[offset:])
	x := &Recurse{}
	x.Init(buf, n+offset)
	return x
}

func FinishRecurseBuffer(builder *flatbuffers.Builder, offset flatbuffers.UOffsetT) {
	builder.Finish(offset)
}

func GetSizePrefixedRootAsRecurse(buf []byte, offset flatbuffers.UOffsetT) *Recurse {
	n := flatbuffers.GetUOffsetT(buf[offset+flatbuffers.SizeUint32:])
	x := &Recurse{}
	x.Init(buf, n+offset+flatbuffers.SizeUint32)
	return x
}

func FinishSizePrefixedRecurseBuffer(builder *flatbuffers.Builder, offset flatbuffers.UOffsetT) {
	builder.FinishSizePrefixed(offset)
}

func (rcv *Recurse) Init(buf []byte, i flatbuffers.UOffsetT) {
	rcv._tab.Bytes = buf
	rcv._tab.Pos = i
}

func (rcv *Recurse) Table() flatbuffers.Table {
	return rcv._tab
}

func (rcv *Recurse) SubQuery() []byte {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(4))
	if o != 0 {
		return rcv._tab.ByteVector(o + rcv._tab.Pos)
	}
	return nil
}

func (rcv *Recurse) ContextKey() []byte {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(6))
	if o != 0 {
		return rcv._tab.ByteVector(o + rcv._tab.Pos)
	}
	return nil
}

func (rcv *Recurse) DepthHint() byte {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(8))
	if o != 0 {
		return rcv._tab.GetByte(o + rcv._tab.Pos)
	}
	return 3
}

func (rcv *Recurse) MutateDepthHint(n byte) bool {
	return rcv._tab.MutateByteSlot(8, n)
}

func RecurseStart(builder *flatbuffers.Builder) {
	builder.StartObject(3)
}
func RecurseAddSubQuery(builder *flatbuffers.Builder, subQuery flatbuffers.UOffsetT) {
	builder.PrependUOffsetTSlot(0, flatbuffers.UOffsetT(subQuery), 0)
}
func RecurseAddContextKey(builder *flatbuffers.Builder, contextKey flatbuffers.UOffsetT) {
	builder.PrependUOffsetTSlot(1, flatbuffers.UOffsetT(contextKey), 0)
}
func RecurseAddDepthHint(builder *flatbuffers.Builder, depthHint byte) {
	builder.PrependByteSlot(2, depthHint, 3)
}
func RecurseEnd(builder *flatbuffers.Builder) flatbuffers.UOffsetT {
	return builder.EndObject()
}
