// Code generated by the FlatBuffers compiler. DO NOT EDIT.

package itrfb

import (
	flatbuffers "github.com/google/flatbuffers/go"
)

type ToolRequest struct {
	_tab flatbuffers.Table
}

func GetRootAsToolRequest(buf []byte, offset flatbuffers.UOffsetT) *ToolRequest {
	n := flatbuffers.GetUOffsetT(buf[offset:])
	x := &ToolRequest{}
	x.Init(buf, n+offset)
	return x
}

func FinishToolRequestBuffer(builder *flatbuffers.Builder, offset flatbuffers.UOffsetT) {
	builder.Finish(offset)
}

func GetSizePrefixedRootAsToolRequest(buf []byte, offset flatbuffers.UOffsetT) *ToolRequest {
	n := flatbuffers.GetUOffsetT(buf[offset+flatbuffers.SizeUint32:])
	x := &ToolRequest{}
	x.Init(buf, n+offset+flatbuffers.SizeUint32)
	return x
}

func FinishSizePrefixedToolRequestBuffer(builder *flatbuffers.Builder, offset flatbuffers.UOffsetT) {
	builder.FinishSizePrefixed(offset)
}

func (rcv *ToolRequest) Init(buf []byte, i flatbuffers.UOffsetT) {
	rcv._tab.Bytes = buf
	rcv._tab.Pos = i
}

func (rcv *ToolRequest) Table() flatbuffers.Table {
	return rcv._tab
}

func (rcv *ToolRequest) Id() []byte {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(4))
	if o != 0 {
		return rcv._tab.ByteVector(o + rcv._tab.Pos)
	}
	return nil
}

func (rcv *ToolRequest) CmdType() CmdType {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(6))
	if o != 0 {
		return CmdType(rcv._tab.GetInt8(o + rcv._tab.Pos))
	}
	return 0
}

func (rcv *ToolRequest) MutateCmdType(n CmdType) bool {
	return rcv._tab.MutateInt8Slot(6, int8(n))
}

func (rcv *ToolRequest) PayloadType() CommandPayload {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(8))
	if o != 0 {
		return CommandPayload(rcv._tab.GetByte(o + rcv._tab.Pos))
	}
	return 0
}

func (rcv *ToolRequest) MutatePayloadType(n CommandPayload) bool {
	return rcv._tab.MutateByteSlot(8, byte(n))
}

func (rcv *ToolRequest) Payload(obj *flatbuffers.Table) bool {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(10))
	if o != 0 {
		rcv._tab.Union(obj, o)
		return true
	}
	return false
}

func (rcv *ToolRequest) DagPlan(obj *DAGPlan) *DAGPlan {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(12))
	if o != 0 {
		x := rcv._tab.Indirect(o + rcv._tab.Pos)
		if obj == nil {
			obj = new(DAGPlan)
		}
		obj.Init(rcv._tab.Bytes, x)
		return obj
	}
	return nil
}

func (rcv *ToolRequest) Timestamp() uint64 {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(14))
	if o != 0 {
		return rcv._tab.GetUint64(o + rcv._tab.Pos)
	}
	return 0
}

func (rcv *ToolRequest) MutateTimestamp(n uint64) bool {
	return rcv._tab.MutateUint64Slot(14, n)
}

func (rcv *ToolRequest) Depth() byte {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(16))
	if o != 0 {
		return rcv._tab.GetByte(o + rcv._tab.Pos)
	}
	return 0
}

func (rcv *ToolRequest) MutateDepth(n byte) bool {
	return rcv._tab.MutateByteSlot(16, n)
}

func (rcv *ToolRequest) SessionKey() []byte {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(18))
	if o != 0 {
		return rcv._tab.ByteVector(o + rcv._tab.Pos)
	}
	return nil
}

func (rcv *ToolRequest) ToolCallId() []byte {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(20))
	if o != 0 {
		return rcv._tab.ByteVector(o + rcv._tab.Pos)
	}
	return nil
}

func ToolRequestStart(builder *flatbuffers.Builder) {
	builder.StartObject(9)
}
func ToolRequestAddId(builder *flatbuffers.Builder, id flatbuffers.UOffsetT) {
	builder.PrependUOffsetTSlot(0, flatbuffers.UOffsetT(id), 0)
}
func ToolRequestAddCmdType(builder *flatbuffers.Builder, cmdType CmdType) {
	builder.PrependInt8Slot(1, int8(cmdType), 0)
}
func ToolRequestAddPayloadType(builder *flatbuffers.Builder, payloadType CommandPayload) {
	builder.PrependByteSlot(2, byte(payloadType), 0)
}
func ToolRequestAddPayload(builder *flatbuffers.Builder, payload flatbuffers.UOffsetT) {
	builder.PrependUOffsetTSlot(3, flatbuffers.UOffsetT(payload), 0)
}
func ToolRequestAddDagPlan(builder *flatbuffers.Builder, dagPlan flatbuffers.UOffsetT) {
	builder.PrependUOffsetTSlot(4, flatbuffers.UOffsetT(dagPlan), 0)
}
func ToolRequestAddTimestamp(builder *flatbuffers.Builder, timestamp uint64) {
	builder.PrependUint64Slot(5, timestamp, 0)
}
func ToolRequestAddDepth(builder *flatbuffers.Builder, depth byte) {
	builder.PrependByteSlot(6, depth, 0)
}
func ToolRequestAddSessionKey(builder *flatbuffers.Builder, sessionKey flatbuffers.UOffsetT) {
	builder.PrependUOffsetTSlot(7, flatbuffers.UOffsetT(sessionKey), 0)
}
func ToolRequestAddToolCallId(builder *flatbuffers.Builder, toolCallId flatbuffers.UOffsetT) {
	builder.PrependUOffsetTSlot(8, flatbuffers.UOffsetT(toolCallId), 0)
}
func ToolRequestEnd(builder *flatbuffers.Builder) flatbuffers.UOffsetT {
	return builder.EndObject()
}
