// Code generated by the FlatBuffers compiler. DO NOT EDIT.

package itrfb

import (
	flatbuffers "github.com/google/flatbuffers/go"
)

type ToolExec struct {
	_tab flatbuffers.Table
}

func GetRootAsToolExec(buf []byte, offset flatbuffers.UOffsetT) *ToolExec {
	n := flatbuffers.GetUOffsetT(buf[offset:])
	x := &ToolExec{}
	x.Init(buf, n+offset)
	return x
}

func FinishToolExecBuffer(builder *flatbuffers.Builder, offset flatbuffers.UOffsetT) {
	builder.Finish(offset)
}

func GetSizePrefixedRootAsToolExec(buf []byte, offset flatbuffers.UOffsetT) *ToolExec {
	n := flatbuffers.GetUOffsetT(buf[offset+flatbuffers.SizeUint32:])
	x := &ToolExec{}
	x.Init(buf, n+offset+flatbuffers.SizeUint32)
	return x
}

func FinishSizePrefixedToolExecBuffer(builder *flatbuffers.Builder, offset flatbuffers.UOffsetT) {
	builder.FinishSizePrefixed(offset)
}

func (rcv *ToolExec) Init(buf []byte, i flatbuffers.UOffsetT) {
	rcv._tab.Bytes = buf
	rcv._tab.Pos = i
}

func (rcv *ToolExec) Table() flatbuffers.Table {
	return rcv._tab
}

func (rcv *ToolExec) ToolName() []byte {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(4))
	if o != 0 {
		return rcv._tab.ByteVector(o + rcv._tab.Pos)
	}
	return nil
}

func (rcv *ToolExec) ArgsJson() []byte {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(6))
	if o != 0 {
		return rcv._tab.ByteVector(o + rcv._tab.Pos)
	}
	return nil
}

func ToolExecStart(builder *flatbuffers.Builder) {
	builder.StartObject(2)
}
func ToolExecAddToolName(builder *flatbuffers.Builder, toolName flatbuffers.UOffsetT) {
	builder.PrependUOffsetTSlot(0, flatbuffers.UOffsetT(toolName), 0)
}
func ToolExecAddArgsJson(builder *flatbuffers.Builder, argsJson flatbuffers.UOffsetT) {
	builder.PrependUOffsetTSlot(1, flatbuffers.UOffsetT(argsJson), 0)
}
func ToolExecEnd(builder *flatbuffers.Builder) flatbuffers.UOffsetT {
	return builder.EndObject()
}
