// Code generated by the FlatBuffers compiler. DO NOT EDIT.

package itrfb

import (
	flatbuffers "github.com/google/flatbuffers/go"
)

type ToolResponse struct {
	_tab flatbuffers.Table
}

func GetRootAsToolResponse(buf []byte, offset flatbuffers.UOffsetT) *ToolResponse {
	n := flatbuffers.GetUOffsetT(buf[offset:])
	x := &ToolResponse{}
	x.Init(buf, n+offset)
	return x
}

func GetSizePrefixedRootAsToolResponse(buf []byte, offset flatbuffers.UOffsetT) *ToolResponse {
	n := flatbuffers.GetUOffsetT(buf[offset+flatbuffers.SizeUint32:])
	x := &ToolResponse{}
	x.Init(buf, n+offset+flatbuffers.SizeUint32)
	return x
}

func (rcv *ToolResponse) Init(buf []byte, i flatbuffers.UOffsetT) {
	rcv._tab.Bytes = buf
	rcv._tab.Pos = i
}

func (rcv *ToolResponse) Table() flatbuffers.Table {
	return rcv._tab
}

func (rcv *ToolResponse) Id() []byte {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(4))
	if o != 0 {
		return rcv._tab.ByteVector(o + rcv._tab.Pos)
	}
	return nil
}

func (rcv *ToolResponse) Result() []byte {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(6))
	if o != 0 {
		return rcv._tab.ByteVector(o + rcv._tab.Pos)
	}
	return nil
}

func (rcv *ToolResponse) IsError() bool {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(8))
	if o != 0 {
		return rcv._tab.GetBool(o + rcv._tab.Pos)
	}
	return false
}

func (rcv *ToolResponse) MutateIsError(n bool) bool {
	return rcv._tab.MutateBoolSlot(8, n)
}

func (rcv *ToolResponse) LeakDetected() bool {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(10))
	if o != 0 {
		return rcv._tab.GetBool(o + rcv._tab.Pos)
	}
	return false
}

func (rcv *ToolResponse) MutateLeakDetected(n bool) bool {
	return rcv._tab.MutateBoolSlot(10, n)
}

func (rcv *ToolResponse) CostTokens() uint32 {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(12))
	if o != 0 {
		return rcv._tab.GetUint32(o + rcv._tab.Pos)
	}
	return 0
}

func (rcv *ToolResponse) MutateCostTokens(n uint32) bool {
	return rcv._tab.MutateUint32Slot(12, n)
}

func (rcv *ToolResponse) RedactedKeys(j int) []byte {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(14))
	if o != 0 {
		a := rcv._tab.Vector(o)
		return rcv._tab.ByteVector(a + flatbuffers.UOffsetT(j*4))
	}
	return nil
}

func (rcv *ToolResponse) RedactedKeysLength() int {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(14))
	if o != 0 {
		return rcv._tab.VectorLen(o)
	}
	return 0
}

func ToolResponseStart(builder *flatbuffers.Builder) {
	builder.StartObject(6)
}
func ToolResponseAddId(builder *flatbuffers.Builder, id flatbuffers.UOffsetT) {
	builder.PrependUOffsetTSlot(0, flatbuffers.UOffsetT(id), 0)
}
func ToolResponseAddResult(builder *flatbuffers.Builder, result flatbuffers.UOffsetT) {
	builder.PrependUOffsetTSlot(1, flatbuffers.UOffsetT(result), 0)
}
func ToolResponseAddIsError(builder *flatbuffers.Builder, isError bool) {
	builder.PrependBoolSlot(2, isError, false)
}
func ToolResponseAddLeakDetected(builder *flatbuffers.Builder, leakDetected bool) {
	builder.PrependBoolSlot(3, leakDetected, false)
}
func ToolResponseAddCostTokens(builder *flatbuffers.Builder, costTokens uint32) {
	builder.PrependUint32Slot(4, costTokens, 0)
}
func ToolResponseAddRedactedKeys(builder *flatbuffers.Builder, redactedKeys flatbuffers.UOffsetT) {
	builder.PrependUOffsetTSlot(5, flatbuffers.UOffsetT(redactedKeys), 0)
}
func ToolResponseStartRedactedKeysVector(builder *flatbuffers.Builder, numElems int) flatbuffers.UOffsetT {
	return builder.StartVector(4, numElems, 4)
}
func ToolResponseEnd(builder *flatbuffers.Builder) flatbuffers.UOffsetT {
	return builder.EndObject()
}
