// Code generated by the FlatBuffers compiler. DO NOT EDIT.

package itrfb

import (
	flatbuffers "github.com/google/flatbuffers/go"
)

type ToolSearch struct {
	_tab flatbuffers.Table
}

func GetRootAsToolSearch(buf []byte, offset flatbuffers.UOffsetT) *ToolSearch {
	n := flatbuffers.GetUOffsetT(buf[offset:])
	x := &ToolSearch{}
	x.Init(buf, n+offset)
	return x
}

func FinishToolSearchBuffer(builder *flatbuffers.Builder, offset flatbuffers.UOffsetT) {
	builder.Finish(offset)
}

func GetSizePrefixedRootAsToolSearch(buf []byte, offset flatbuffers.UOffsetT) *ToolSearch {
	n := flatbuffers.GetUOffsetT(buf[offset+flatbuffers.SizeUint32:])
	x := &ToolSearch{}
	x.Init(buf, n+offset+flatbuffers.SizeUint32)
	return x
}

func FinishSizePrefixedToolSearchBuffer(builder *flatbuffers.Builder, offset flatbuffers.UOffsetT) {
	builder.FinishSizePrefixed(offset)
}

func (rcv *ToolSearch) Init(buf []byte, i flatbuffers.UOffsetT) {
	rcv._tab.Bytes = buf
	rcv._tab.Pos = i
}

func (rcv *ToolSearch) Table() flatbuffers.Table {
	return rcv._tab
}

func (rcv *ToolSearch) Query() []byte {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(4))
	if o != 0 {
		return rcv._tab.ByteVector(o + rcv._tab.Pos)
	}
	return nil
}

func (rcv *ToolSearch) MaxResults() byte {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(6))
	if o != 0 {
		return rcv._tab.GetByte(o + rcv._tab.Pos)
	}
	return 10
}

func (rcv *ToolSearch) MutateMaxResults(n byte) bool {
	return rcv._tab.MutateByteSlot(6, n)
}

func ToolSearchStart(builder *flatbuffers.Builder) {
	builder.StartObject(2)
}
func ToolSearchAddQuery(builder *flatbuffers.Builder, query flatbuffers.UOffsetT) {
	builder.PrependUOffsetTSlot(0, flatbuffers.UOffsetT(query), 0)
}
func ToolSearchAddMaxResults(builder *flatbuffers.Builder, maxResults byte) {
	builder.PrependByteSlot(1, maxResults, 10)
}
func ToolSearchEnd(builder *flatbuffers.Builder) flatbuffers.UOffsetT {
	return builder.EndObject()
}
