// Code generated by the FlatBuffers compiler. DO NOT EDIT.

package mapopsfb

import (
	flatbuffers "github.com/google/flatbuffers/go"
)

type MapItemOutput struct {
	_tab flatbuffers.Table
}

func GetRootAsMapItemOutput(buf []byte, offset flatbuffers.UOffsetT) *MapItemOutput {
	n := flatbuffers.GetUOffsetT(buf[offset:])
	x := &MapItemOutput{}
	x.Init(buf, n+offset)
	return x
}

func FinishMapItemOutputBuffer(builder *flatbuffers.Builder, offset flatbuffers.UOffsetT) {
	builder.Finish(offset)
}

func GetSizePrefixedRootAsMapItemOutput(buf []byte, offset flatbuffers.UOffsetT) *MapItemOutput {
	n := flatbuffers.GetUOffsetT(buf[offset+flatbuffers.SizeUint32:])
	x := &MapItemOutput{}
	x.Init(buf, n+offset+flatbuffers.SizeUint32)
	return x
}

func FinishSizePrefixedMapItemOutputBuffer(builder *flatbuffers.Builder, offset flatbuffers.UOffsetT) {
	builder.FinishSizePrefixed(offset)
}

func (rcv *MapItemOutput) Init(buf []byte, i flatbuffers.UOffsetT) {
	rcv._tab.Bytes = buf
	rcv._tab.Pos = i
}

func (rcv *MapItemOutput) Table() flatbuffers.Table {
	return rcv._tab
}

func (rcv *MapItemOutput) Version() uint16 {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(4))
	if o != 0 {
		return rcv._tab.GetUint16(o + rcv._tab.Pos)
	}
	return 1
}

func (rcv *MapItemOutput) MutateVersion(n uint16) bool {
	return rcv._tab.MutateUint16Slot(4, n)
}

func (rcv *MapItemOutput) ItemIndex() uint32 {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(6))
	if o != 0 {
		return rcv._tab.GetUint32(o + rcv._tab.Pos)
	}
	return 0
}

func (rcv *MapItemOutput) MutateItemIndex(n uint32) bool {
	return rcv._tab.MutateUint32Slot(6, n)
}

func (rcv *MapItemOutput) Success() bool {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(8))
	if o != 0 {
		return rcv._tab.GetBool(o + rcv._tab.Pos)
	}
	return false
}

func (rcv *MapItemOutput) MutateSuccess(n bool) bool {
	return rcv._tab.MutateBoolSlot(8, n)
}

func (rcv *MapItemOutput) Attempts() uint16 {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(10))
	if o != 0 {
		return rcv._tab.GetUint16(o + rcv._tab.Pos)
	}
	return 0
}

func (rcv *MapItemOutput) MutateAttempts(n uint16) bool {
	return rcv._tab.MutateUint16Slot(10, n)
}

func (rcv *MapItemOutput) OutputJson() []byte {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(12))
	if o != 0 {
		return rcv._tab.ByteVector(o + rcv._tab.Pos)
	}
	return nil
}

func (rcv *MapItemOutput) ErrorText() []byte {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(14))
	if o != 0 {
		return rcv._tab.ByteVector(o + rcv._tab.Pos)
	}
	return nil
}

func (rcv *MapItemOutput) OutputHash() []byte {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(16))
	if o != 0 {
		return rcv._tab.ByteVector(o + rcv._tab.Pos)
	}
	return nil
}

func MapItemOutputStart(builder *flatbuffers.Builder) {
	builder.StartObject(7)
}
func MapItemOutputAddVersion(builder *flatbuffers.Builder, version uint16) {
	builder.PrependUint16Slot(0, version, 1)
}
func MapItemOutputAddItemIndex(builder *flatbuffers.Builder, itemIndex uint32) {
	builder.PrependUint32Slot(1, itemIndex, 0)
}
func MapItemOutputAddSuccess(builder *flatbuffers.Builder, success bool) {
	builder.PrependBoolSlot(2, success, false)
}
func MapItemOutputAddAttempts(builder *flatbuffers.Builder, attempts uint16) {
	builder.PrependUint16Slot(3, attempts, 0)
}
func MapItemOutputAddOutputJson(builder *flatbuffers.Builder, outputJson flatbuffers.UOffsetT) {
	builder.PrependUOffsetTSlot(4, flatbuffers.UOffsetT(outputJson), 0)
}
func MapItemOutputAddErrorText(builder *flatbuffers.Builder, errorText flatbuffers.UOffsetT) {
	builder.PrependUOffsetTSlot(5, flatbuffers.UOffsetT(errorText), 0)
}
func MapItemOutputAddOutputHash(builder *flatbuffers.Builder, outputHash flatbuffers.UOffsetT) {
	builder.PrependUOffsetTSlot(6, flatbuffers.UOffsetT(outputHash), 0)
}
func MapItemOutputEnd(builder *flatbuffers.Builder) flatbuffers.UOffsetT {
	return builder.EndObject()
}
