// Code generated by MockGen. DO NOT EDIT.
// Source: tasks_rl.go
//
// Generated by this command:
//
//	mockgen -source=tasks_rl.go -destination=mock_rl_store_test.go -package=cortex
//

// Package cortex is a generated GoMock package.
package cortex

import (
	context "context"
	reflect "reflect"
	time "time"

	ids "github.com/ZanzyTHEbar/dragonscale/pkg/ids"
	gomock "go.uber.org/mock/gomock"
)

// MockRLStore is a mock of RLStore interface.
type MockRLStore struct {
	ctrl     *gomock.Controller
	recorder *MockRLStoreMockRecorder
	isgomock struct{}
}

// MockRLStoreMockRecorder is the mock recorder for MockRLStore.
type MockRLStoreMockRecorder struct {
	mock *MockRLStore
}

// NewMockRLStore creates a new mock instance.
func NewMockRLStore(ctrl *gomock.Controller) *MockRLStore {
	mock := &MockRLStore{ctrl: ctrl}
	mock.recorder = &MockRLStoreMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockRLStore) EXPECT() *MockRLStoreMockRecorder {
	return m.recorder
}

// GetCompletedTasks mocks base method.
func (m *MockRLStore) GetCompletedTasks(ctx context.Context, agentID string, since time.Time) ([]TaskRecord, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetCompletedTasks", ctx, agentID, since)
	ret0, _ := ret[0].([]TaskRecord)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetCompletedTasks indicates an expected call of GetCompletedTasks.
func (mr *MockRLStoreMockRecorder) GetCompletedTasks(ctx, agentID, since any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetCompletedTasks", reflect.TypeOf((*MockRLStore)(nil).GetCompletedTasks), ctx, agentID, since)
}

// GetRetrievedMemories mocks base method.
func (m *MockRLStore) GetRetrievedMemories(ctx context.Context, taskID string) ([]RetrievedMemoryRecord, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetRetrievedMemories", ctx, taskID)
	ret0, _ := ret[0].([]RetrievedMemoryRecord)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetRetrievedMemories indicates an expected call of GetRetrievedMemories.
func (mr *MockRLStoreMockRecorder) GetRetrievedMemories(ctx, taskID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetRetrievedMemories", reflect.TypeOf((*MockRLStore)(nil).GetRetrievedMemories), ctx, taskID)
}

// GetTaskBaseline mocks base method.
func (m *MockRLStore) GetTaskBaseline(ctx context.Context, agentID string) (*TaskBaseline, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetTaskBaseline", ctx, agentID)
	ret0, _ := ret[0].(*TaskBaseline)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetTaskBaseline indicates an expected call of GetTaskBaseline.
func (mr *MockRLStoreMockRecorder) GetTaskBaseline(ctx, agentID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetTaskBaseline", reflect.TypeOf((*MockRLStore)(nil).GetTaskBaseline), ctx, agentID)
}

// ListActiveAgents mocks base method.
func (m *MockRLStore) ListActiveAgents(ctx context.Context, since time.Time) ([]string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListActiveAgents", ctx, since)
	ret0, _ := ret[0].([]string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListActiveAgents indicates an expected call of ListActiveAgents.
func (mr *MockRLStoreMockRecorder) ListActiveAgents(ctx, since any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListActiveAgents", reflect.TypeOf((*MockRLStore)(nil).ListActiveAgents), ctx, since)
}

// UpdateMemorySelfReport mocks base method.
func (m *MockRLStore) UpdateMemorySelfReport(ctx context.Context, memoryID ids.UUID, score int) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateMemorySelfReport", ctx, memoryID, score)
	ret0, _ := ret[0].(error)
	return ret0
}

// UpdateMemorySelfReport indicates an expected call of UpdateMemorySelfReport.
func (mr *MockRLStoreMockRecorder) UpdateMemorySelfReport(ctx, memoryID, score any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateMemorySelfReport", reflect.TypeOf((*MockRLStore)(nil).UpdateMemorySelfReport), ctx, memoryID, score)
}

// UpdateMemoryWeight mocks base method.
func (m *MockRLStore) UpdateMemoryWeight(ctx context.Context, memoryID ids.UUID, weight, credit float64) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateMemoryWeight", ctx, memoryID, weight, credit)
	ret0, _ := ret[0].(error)
	return ret0
}

// UpdateMemoryWeight indicates an expected call of UpdateMemoryWeight.
func (mr *MockRLStoreMockRecorder) UpdateMemoryWeight(ctx, memoryID, weight, credit any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateMemoryWeight", reflect.TypeOf((*MockRLStore)(nil).UpdateMemoryWeight), ctx, memoryID, weight, credit)
}

// UpdateTaskBaseline mocks base method.
func (m *MockRLStore) UpdateTaskBaseline(ctx context.Context, agentID string, baseline *TaskBaseline) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateTaskBaseline", ctx, agentID, baseline)
	ret0, _ := ret[0].(error)
	return ret0
}

// UpdateTaskBaseline indicates an expected call of UpdateTaskBaseline.
func (mr *MockRLStoreMockRecorder) UpdateTaskBaseline(ctx, agentID, baseline any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateTaskBaseline", reflect.TypeOf((*MockRLStore)(nil).UpdateTaskBaseline), ctx, agentID, baseline)
}
