// Code generated by MockGen. DO NOT EDIT.
// Source: tasks_audit_analysis.go
//
// Generated by this command:
//
//	mockgen -source=tasks_audit_analysis.go -destination=mock_audit_analysis_store_test.go -package=cortex
//

// Package cortex is a generated GoMock package.
package cortex

import (
	context "context"
	reflect "reflect"
	time "time"

	memory "github.com/ZanzyTHEbar/dragonscale/pkg/memory"
	gomock "go.uber.org/mock/gomock"
)

// MockAuditAnalysisStore is a mock of AuditAnalysisStore interface.
type MockAuditAnalysisStore struct {
	ctrl     *gomock.Controller
	recorder *MockAuditAnalysisStoreMockRecorder
	isgomock struct{}
}

// MockAuditAnalysisStoreMockRecorder is the mock recorder for MockAuditAnalysisStore.
type MockAuditAnalysisStoreMockRecorder struct {
	mock *MockAuditAnalysisStore
}

// NewMockAuditAnalysisStore creates a new mock instance.
func NewMockAuditAnalysisStore(ctrl *gomock.Controller) *MockAuditAnalysisStore {
	mock := &MockAuditAnalysisStore{ctrl: ctrl}
	mock.recorder = &MockAuditAnalysisStoreMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockAuditAnalysisStore) EXPECT() *MockAuditAnalysisStoreMockRecorder {
	return m.recorder
}

// GetHighTokenSessions mocks base method.
func (m *MockAuditAnalysisStore) GetHighTokenSessions(ctx context.Context, minTokens int64) ([]SessionSummary, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetHighTokenSessions", ctx, minTokens)
	ret0, _ := ret[0].([]SessionSummary)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetHighTokenSessions indicates an expected call of GetHighTokenSessions.
func (mr *MockAuditAnalysisStoreMockRecorder) GetHighTokenSessions(ctx, minTokens any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetHighTokenSessions", reflect.TypeOf((*MockAuditAnalysisStore)(nil).GetHighTokenSessions), ctx, minTokens)
}

// GetRecentAuditEntries mocks base method.
func (m *MockAuditAnalysisStore) GetRecentAuditEntries(ctx context.Context, since time.Time) ([]AuditEntry, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetRecentAuditEntries", ctx, since)
	ret0, _ := ret[0].([]AuditEntry)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetRecentAuditEntries indicates an expected call of GetRecentAuditEntries.
func (mr *MockAuditAnalysisStoreMockRecorder) GetRecentAuditEntries(ctx, since any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetRecentAuditEntries", reflect.TypeOf((*MockAuditAnalysisStore)(nil).GetRecentAuditEntries), ctx, since)
}

// InsertRecallItem mocks base method.
func (m *MockAuditAnalysisStore) InsertRecallItem(ctx context.Context, item *memory.RecallItem) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "InsertRecallItem", ctx, item)
	ret0, _ := ret[0].(error)
	return ret0
}

// InsertRecallItem indicates an expected call of InsertRecallItem.
func (mr *MockAuditAnalysisStoreMockRecorder) InsertRecallItem(ctx, item any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "InsertRecallItem", reflect.TypeOf((*MockAuditAnalysisStore)(nil).InsertRecallItem), ctx, item)
}

// StoreDetectedPattern mocks base method.
func (m *MockAuditAnalysisStore) StoreDetectedPattern(ctx context.Context, pattern DetectedPattern) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "StoreDetectedPattern", ctx, pattern)
	ret0, _ := ret[0].(error)
	return ret0
}

// StoreDetectedPattern indicates an expected call of StoreDetectedPattern.
func (mr *MockAuditAnalysisStoreMockRecorder) StoreDetectedPattern(ctx, pattern any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "StoreDetectedPattern", reflect.TypeOf((*MockAuditAnalysisStore)(nil).StoreDetectedPattern), ctx, pattern)
}
